### ISSUE TITLE
Access HTTP response headers

### ISSUE THREAD

**Issue by KaemmeA** [apache/cordova-plugin-inappbrowser#1011]
As `document.cookie` does not include HttpOnly cookies, Is there any way to use this plugin to access HTTP response headers, e.g. for accessing the Set-Cookie header?

**Comment by breautek** [comment]
A httpOnly cookie means its a cookie only meant to be accessed by the server. Browser user agents shouldn't expose these cookies to the clients scripting interface.

I don't think the underlying webview has the capability to read response headers of requests but even if it would be considered a security vulnerability if there was a way to expose httpOnly headers.

If you want to use cookie information in the clients, then the proper solution is for the server to remove the httpOnly flag when setting cookies.
