### ISSUE TITLE
Keychain not work with inappbrowser

### ISSUE THREAD

**Issue by harishk90** [apache/cordova-plugin-inappbrowser#1027]
I had integrated Keycloak login in my iOS app using inappbrowser.

Login is working correctly without any issues. However Keychain not asking to save username and password during login.

User needs to enter username and password every time because of this issue.

**Comment by jcesarmobile** [comment]
It's a limitation of the WKWebView the plugin uses, Apple didn't implement password saving for it.

This plugin that uses Safari View Controller should save passwords, but doesn't have the same features InAppBrowser has.

https://www.npmjs.com/package/cordova-plugin-safariviewcontroller
