### ISSUE TITLE
When can we expect latest 6.0.0 version release on npm?

### ISSUE THREAD

**Issue by ShahinBelim** [apache/cordova-plugin-inappbrowser#1036]
I have been using this plugin and find it incredibly valuable for my project. Thank you for your hard work on maintaining this plugin.

I saw the new version release 6.0.0 on GitHub but when I checked it on npm, it still shows the older version(5.0.0). Any plans to publish the latest version on npm?

**Comment by timbru31** [comment]
It's already available on npm: https://www.npmjs.com/package/cordova-plugin-inappbrowser/v/6.0.0
