### ISSUE TITLE
The www/inappbrowser.css file should be removed because it was only for the Windows platform

### ISSUE THREAD

**Issue by DAnn2012** [apache/cordova-plugin-inappbrowser#1037]
# Bug Report
The `www/inappbrowser.css` file should be removed because it was only for the Windows platform

### What is expected to happen?
The `www/inappbrowser.css` file should be removed because it was only for the Windows platform (which was removed in version 6.0.0 of the plugin)

### What does actually happen?

The file is still present in version 6.0.0 of the plugin

## Information

See https://github.com/apache/cordova-plugin-inappbrowser/commit/4b3c0f126ddb12c62ed3d4bd95322a6147389290

### Environment, Platform, Device

cordova-plugin-inappbrowser 6.0.0

### Version information

cordova-plugin-inappbrowser 6.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
good catch!
