### ISSUE TITLE
6.0.0 Update throws error while archiving iOS project: "'Cordova/CDVWebViewProcessPoolFactory.h' file not found"

### ISSUE THREAD

**Issue by TobiasHesselinkTopicus** [apache/cordova-plugin-inappbrowser#1040]
# Bug Report

### What is expected to happen?
A successfully build archive within Xcode or Ionic Appflow with the newest 6.0.0 cordova-inappbrowser package.

### What does actually happen?
Unable to create an archive within Xcode or Appflow. The following error occurred:

```
ios/capacitor-cordova-ios-plugins/sources/CordovaPluginInappbrowser/CDVWKInAppBrowser.m:22:9: 'Cordova/CDVWebViewProcessPoolFactory.h' file not found
** ARCHIVE FAILED **
```

![Screenshot of the error in Xcode](https://github.com/apache/cordova-plugin-inappbrowser/assets/80394646/c28f0d32-d136-47c0-8a99-2b59c58cf913)

## Information

Updated from 5.0.0 to 6.0.0.  Using Ionic and Angular.
As the version is recently released, I could not find much info on the internet about this issue. Although I saw someone else experiencing the exact same issue on stackoverflow: https://stackoverflow.com/questions/77541592/capacitor-browser-send-callback-data-to-ionic-application

### Command or Code

Install the 6.0.0 package. Sync the pods by running `ionic cap sync ios`. Then open Xcode and start a new Archive build.

### Environment, Platform, Device

MacOS. 
![Build stack](https://github.com/apache/cordova-plugin-inappbrowser/assets/80394646/d37b4c8f-92de-4acb-a727-cfbbfc70bec9)

### Version information

See above screenshot from build stack.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Duplicate: https://github.com/apache/cordova-plugin-inappbrowser/issues/1039
