### ISSUE TITLE
How to build this plugin for node_modules?

### ISSUE THREAD

**Issue by loremru** [apache/cordova-plugin-inappbrowser#1043]
Hey, I forked this plugin for my pet project. 

So I add to my package.json 
"@awesome-cordova-plugins/in-app-browser": "https://github.com/link-to-forked-plugin-on-git.git"

But this repository doesn't export anything, and files on npm is different. 
I have capacitor app, so I want to have same structure as on npm

How can I build this plugin?

**Comment by breautek** [comment]
I have no idea how capacitor works but the cordova way is to use `cordova plugin add ...`, e.g.:

`cordova plugin add https://github.com/link-to-forked-plugin-on-git.git`

If the plugin is already installed, it needs to be uninstalled first doing `cordova plugin remove @awesome-cordova-plugins/in-app-browser` (or whatever what the plugin id is)

You may have to resort to capacitor docs or their support channels to learn exactly how they interface with Cordova projects.

**Comment by jcesarmobile** [comment]
`@awesome-cordova-plugins` are typescript wrappers for Cordova plugins, that code is unrelated to this repository (`cordova-plugin-inappbrowser` repository).
If you want to make changes in `@awesome-cordova-plugins/in-app-browser` wrapper (typescript code) then the repository to clone and change is https://github.com/danielsogl/awesome-cordova-plugins.
If you want to make changes in `cordova-plugin-inappbrowser` code (iOS, or Android code), then this is the correct repository to clone and change, but no build is required.
