### ISSUE TITLE
window.open doesnt work inside the opened webview

### ISSUE THREAD

**Issue by AsimDawrat** [apache/cordova-plugin-inappbrowser#1046]
# Bug Report

## Problem
window.open(..) doesn't work webpage opened in InAppBrowser

### What is expected to happen?
window.open(..) inside the InAppBrowser WebView should work

### What does actually happen?
window.open(..) inside the InAppBrowser WebView doesnt work. There is no action performed

### Environment, Platform, Device

iOS and android

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
can you provide a sample app that reproduces the issue?

**Comment by jcesarmobile** [comment]
Closing since there was no response
