### ISSUE TITLE
UIApplication.openURL(_:) needs to migrate to the non-deprecated

### ISSUE THREAD

**Issue by kerituni12** [apache/cordova-plugin-inappbrowser#1078]
# Bug Report
UIApplication.openURL(_:) needs to migrate to the non-deprecated on IOS 18

### What is expected to happen?
The issue occurs because UIApplication.openURL(_:) has been deprecated in iOS and replaced by UIApplication.open(_:options:completionHandler:)

### Command or Code
```
- (void)openInSystem:(NSURL*)url
{
    if (@available(iOS 10.0, *)) {
        [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:^(BOOL success) {
            if (!success) {
                [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];
            }
        }];
    } else {
        // Fallback for older iOS versions
        if ([[UIApplication sharedApplication] openURL:url] == NO) {
            [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];
        }
    }
}
```

### Environment, Platform, Device
IOS 18 not working

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
It should have already been addressed and released in v6.0.0.

You can view the relevant changes here:

https://github.com/apache/cordova-plugin-inappbrowser/blob/rel/6.0.0/src/ios/CDVWKInAppBrowser.m#L297-L304
