### ISSUE TITLE
'Cordova/CDVWebViewDelegate.h' file not found

### ISSUE THREAD

**Issue by boris1690** [apache/cordova-plugin-inappbrowser#281]
Hi,

I have the following error 'Cordova/CDVWebViewDelegate.h' file not found, can anybody help me??

**Comment by janpio** [comment]
You have this error with what?
What platform? What Cordova CLI? What version of the plugin? What are you doing?

**Comment by jcesarmobile** [comment]
closing as there was no response and looks like a bad cordova-ios install
