### ISSUE TITLE
Authentication prompt not happening in inappbrowser

### ISSUE THREAD

**Issue by ambatidilip** [apache/cordova-plugin-inappbrowser#282]
I am trying make authentication to the server. When i open the url in browser it prompts for authentication. 
The same i have tried with inappbrowser but it wont prompts for authentication directly it redirects to unauthorised access. Unable to get authentication prompt to authenticate 

Below is the prompt when i open in browser

![image](https://user-images.githubusercontent.com/16309473/44201734-943f6780-a17c-11e8-858a-d52069686450.png)

**Comment by janpio** [comment]
Does the prompt work in the normal Android browser? 
In other browsers like Firefox for Android?

**Comment by ambatidilip** [comment]
Yes, I have opened the same in android chrome browser its showing prompt to enter the credentials.

**Comment by janpio** [comment]
> But i noticed one thing which is a text saying as The site says: "Protect:/"

Huh? Can you provide a screenshot?

Seems to me `cordova-plugin-inappbrowser` is not configured to prompt for authentication passwords. One reason could be to avoid users entering credentials in a way they don't intent to?

Is this only on Android or also on iOS?

You will have to find out how InAppBrowser creates the webview to display the pages, then see if there is a configuration option for that code to enable or disable the authentication prompts. Maybe this has to be added to this plugin via a Pull Request.

**Comment by janpio** [comment]
> but when i check in app using _blank i see only IOS loader screen not prompting signIn screen.

What does that mean exactly? Can you provide a screenshot?

Are you opening the page with the password prompt directly in InAppBrowser? Try opening a normal HTML page first that is not behind a password, then add a link to the page and click it. Is the behavior different?

**Comment by ambatidilip** [comment]
<img width="500" alt="screen shot 2018-08-16 at 8 42 06 pm" src="https://user-images.githubusercontent.com/16309473/44209070-e3919200-a194-11e8-91ac-4e228b41bab8.png">

Above is the screenshot for IOS. Coming to the scenario, I am loading inappbrowser on a click event
`function openBrowser() {
    showHelp(url);
}
var inAppBrowserRef;
var cookies;
var interval;
function showHelp(url) {

    var target = "_blank"; //_blank   _self  _system
    // var options = "location=no,hidden=yes;clearcache=yes;clearsessioncache=yes;";
    var options = "location=no,hidden=yes;";
    console.log('Opening Inapp browser ');
    inAppBrowserRef = cordova.InAppBrowser.open(url, target, options);
    inAppBrowserRef.addEventListener('loadstart', loadStartCallBack);
    inAppBrowserRef.addEventListener('loadstop', loadStopCallBack);
    inAppBrowserRef.addEventListener('loaderror', loadErrorCallBack);
    inAppBrowserRef.show();
}`

<img width="500" alt="screen shot 2018-08-16 at 8 46 24 pm" src="https://user-images.githubusercontent.com/16309473/44209386-e640b700-a195-11e8-9386-53e023c5c613.png">

i have opened a normal html which is google.com it is opening properly. i have loaded gmail it is also loaded properly. The only problem is when a server is directly requesting to signIn in order to access for a webpage.

**Comment by janpio** [comment]
Ok. Please create a webpage linking to the protected one and open that in InAppBrowser, then click the link.

**Comment by ambatidilip** [comment]
Yes, the page will return few info regarding the loggedIn by specific user and it is not hardcode credentials. I have tried the above mentioned scenario also and it behave the same. But finally i found some info which the pop-up raised because of **Windows based authentication** which is not a webpage authentication. Please check the below link for sample windows based authentication.

[Windows Based Authentication](https://youtu.be/texTsP4aYgQ)

**Comment by janpio** [comment]
No, the popup you are seeing looks like a normal ["Basic authentication"](https://en.wikipedia.org/wiki/Basic_access_authentication) - how this works in the backend doesn't matter. You can check the response headers in your browser's dev tools network panel to see if it contains `WWW-Authenticate: Basic`

**Comment by ambatidilip** [comment]
Correct, its a basic authentication.
<img width="919" alt="screen shot 2018-08-16 at 9 54 23 pm" src="https://user-images.githubusercontent.com/16309473/44212850-07f26c00-a19f-11e8-8083-26eb36f7d09c.png">

**Comment by janpio** [comment]
Ok, good to be sure.

Next thing to try: Do the URLs work if you supply the username and password in the URL: `https://username:password@example.org/page`. If that does, it might offer a workaround you could use. But try this first. (Should also work in desktop)

**Comment by ambatidilip** [comment]
I have tried it but results no change, its again redirecting to the login screen and prompts for credentials.

**Comment by ambatidilip** [comment]
No positive by adding credentials via url. Is there any other approach.

**Comment by janpio** [comment]
> No positive by adding credentials via url.

Tested both iOS and Android?
(I need an explicit answer before moving on to the next thing to try - otherwise we might miss a simple solution)

> Is there any other approach.

See my previous comment:

>> Can you maybe move the authentication to a different method, not Basic Auth but a login form?

**Comment by ambatidilip** [comment]
Yes, i have tested in Android and IOS results same error. 
I have created a form authentication, its working properly and i can get the required token.

**Comment by janpio** [comment]
Token? Please elaborate.

**Comment by janpio** [comment]
Ok, after some googling:

1. This exists to solve this specific problem: https://github.com/MicrosoftArchive/cordova-plugin-auth-dialog Unfortunately it is not very well maintained and outdated, but there are multiple forks with additional commit like e.g. https://github.com/michael79bxl/cordova-plugin-auth-dialog. Problem: The docs say this does not work in InAppBrowser, but I am not sure this is actually true (I found issues and comments that indicate that it indeed does work on Android, but maybe not on iOS).

2. Another "hack" that could work if there is only 1 page, and no links to other pages on it:
Create a simple website with a form that accepts username and password. When submitting this form, the "proxy" script takes the credentials and requests the correct website with the `Authorization` header directly, and return the HTML of the original page to the InAppBrowser which can then display it. (If there are more links on the page, one could also replace them with a different URL that again uses the "proxy" to get the original page with the credentials, modify the links and return to the browser.

3. If you want to work on the InAppBrowser plugin yourself, this might give you some ideas (at least for Android): https://stackoverflow.com/questions/38369522/inapp-browser-basic-authentication-not-working + https://stackoverflow.com/questions/36041760/open-inappbrowser-with-authorization-header

**Comment by ambatidilip** [comment]
On authentication success i will get user information along with user access token.

**Comment by janpio** [comment]
Oh, so the whole point was to get an authentication token via username + password, not load actual content in the InAppBrowser?

**Comment by ambatidilip** [comment]
Perfect.
