### ISSUE TITLE
No description for "replace?" parameter

### ISSUE THREAD

**Issue by de-dan** [apache/cordova-plugin-inappbrowser#295]
While `url`, `target` and `options` are documented, there is no description/documentation for the optional `replace` parameter in the index.d.ts file (line 45). The function is:
`open(url: string, target?: string, options?: string, replace?: boolean): InAppBrowser;`

I'm curious whats `replace` about.

**Comment by janpio** [comment]
From looking at the whole repo this seems to be something leftover in the TS definition: https://github.com/apache/cordova-plugin-inappbrowser/search?q=replace&unscoped_q=replace

**Comment by janpio** [comment]
Hey @timbru31, I just merged a PR about the typings from you - so you seem to know your way around them. Could you please take a look? Thanks.

**Comment by janpio** [comment]
No, we haven't updated the issue and PR templates properly. All on Github now, so go for it and adapt the templates as necessary 🚀
