### ISSUE TITLE
Typings does not export cordova.InAppBrowser.open

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-plugin-inappbrowser#300]
Hi,
This is a great plugin! thanks for all the hard work!
In the documentation it is suggested to do the following:
`window.open = cordova.InAppBrowser.open;`
However when using typescript this is not possible without using `any` or something similar.
Please add the relevant declaration to the types file.

**Comment by janpio** [comment]
There are already several typing related PRs. Can you check those to see if those fix the issue you are describing?

**Comment by HarelM** [comment]
Thanks for the super quick response.
Seems like the following should do the job:
#267

**Comment by HarelM** [comment]
Not sure I understand what you mean. can you please elaborate?
Do you want me to code-review it? It seems like the typings are matching the library code as far as I know.
