### ISSUE TITLE
pdf is not opening in android inappbrower using ionic 3. 

### ISSUE THREAD

**Issue by ansarikhurshid786** [apache/cordova-plugin-inappbrowser#309]
I am using ionic 3 plugin to view pdf inappbrowser. It is working fine in ios but not working in android. 

I am using following code : 

this.iab.create("pdfurlhere", "_blank").show();

I am getting any error and log in new window.

**Comment by dland512** [comment]
I am also seeing a similar issue with PDFs on Android. I don't get any errors, just a blank screen. If I change `_blank` to `_system` it works. Do I just have to do that for pdf on android?

**Comment by ansarikhurshid786** [comment]
@dland512 if your pdf on server try to use encodeduri like : encodeURI(uri), it work fine most of case. 

I want to give user best experience so I am downloading and opening in available pdf reader in user's device.

**Comment by jcesarmobile** [comment]
Android webview doesn't render PDF files.
So, yeah, use _system so it uses another app to open the PDF

**Comment by JPustkuchen** [comment]
If PDF files are linked in a page which is shown in the inAppBrowser, the inAppBrowser will simply do nothing when clicking the link (as far as I know). My solution uses "beforeload" to decide how to handle the link:
https://julian.pustkuchen.com/node/809

Perhaps this helps others who don't have the link in their application, but in inAppBrowser content, where other JS solutions fail.
