### ISSUE TITLE
InAppBrowser.java:260: error: cannot find symbol

### ISSUE THREAD

**Issue by fazamutash** [apache/cordova-plugin-inappbrowser#313]
I tried update the plugin to the latest version and tried to build the apk and I got this error.

F:\Work\androidProject\platforms\android\src\org\apache\cordova\inappbrowser\InAppBrowser.java:260: error: cannot find symbol

                    ((InAppBrowserClient)inAppWebView.getWebViewClient()).waitForBeforeload = false;
                                                     ^
  symbol:   method getWebViewClient()

  location: variable inAppWebView of type WebView

Any idea about this?
I am using Ionic 1 and platform android 6.1.0

Edit:
Downgrade to v3.0.0 and successfully built the apk. seems the error happened on v3.0.1-dev

**Comment by janpio** [comment]
3.0.0 is the latest released version of this. Were you trying to install `master`?

**Comment by jcesarmobile** [comment]
was fixed on https://github.com/apache/cordova-plugin-inappbrowser/pull/427
