### ISSUE TITLE
"delete window.open" does not work in Chrome/69

### ISSUE THREAD

**Issue by goffioul** [apache/cordova-plugin-inappbrowser#315]
I want to get rid of the override "window.open" on browser platform. But the suggested solution "delete window.open" does not work  in Chrome/69 and "window.open" ends being undefined.

**Comment by frederikbosch** [comment]
This is also not working on iOS 12, not tested earlier versions.

**Comment by frederikbosch** [comment]
I am sticking to calling `window.cordova.InAppBrowser.open(location, '_system');` instead of window.open.

**Comment by goffioul** [comment]
What I want is to restore the native `window.open` behavior, but that's not possible.

**Comment by frederikbosch** [comment]
@goffioul Maybe you can put this on top of your app. Since I am fine with `_system` I did not try it myself.

```
let originalOpen = window.open;
document.addEventListener('deviceready', () => {
  // cordova should be ready by now, restore window.open
 window.open = originalOpen;
});
```

**Comment by mohammadrafigh** [comment]
It's also not working on Firefox. overwriting window functions is really a bad idea.

**Comment by ibrahimAboelsuod** [comment]
> @goffioul Maybe you can put this on top of your app. Since I am fine with `_system` I did not try it myself.
> 
> ```
> let originalOpen = window.open;
> document.addEventListener('deviceready', () => {
>   // cordova should be ready by now, restore window.open
>  window.open = originalOpen;
> });
> ```

I can confirm this fix. I placed it at the bottom of body tag in `index.html` file.

**Comment by azens1995** [comment]
You can also get the original (native-code) function back with:

```window.open = cordova.require('cordova/modulemapper').getOriginalSymbol(window, 'window.open');

Well this solution was found somewhere in the old issues (Forgot where I found it), and it seems to work in our case. Hope it might help someone.

**Comment by goffioul** [comment]
Fixed by https://github.com/apache/cordova-plugin-inappbrowser/pull/600
