### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by jacobg** [apache/cordova-plugin-inappbrowser#319]
A new version hasn't been published to npm in 6 months. A commit for a serious bug has been made, and needs to be available:

https://github.com/apache/cordova-plugin-inappbrowser/pull/272/files

**Comment by janpio** [comment]
Releases happen, when the happen.

Feel free to help us with issues (answers, deciding if something is a real bug or just a support problem) and pull requests (reviews, comments on code, ...) to speed up the process to get there.

**Comment by brodybits** [comment]
I would favor a release once the ongoing bug fixes are integrated.

It is always possible to add this plugin from GitHub as follows (*not tested*):

    cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser

Even better may be to use the latest commit ID, explicitly, to avoid volatility (again *not tested*):

    cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser#27fe8ec
