### ISSUE TITLE
Cordova Inappbrowser adds a grey block on orientation change

### ISSUE THREAD

**Issue by Dev-CH** [apache/cordova-plugin-inappbrowser#322]
On orientation change, from portrait to landscape, a grey block appears in the top left hand corner of the screen.

> inappbrowser version - 3.0.0
> cordova version - 7.1.0

[example](https://stackoverflow.com/questions/46663649/ios-11-2-cordova-inappbrowser-adds-a-grey-block-on-orientation-change)

**Comment by skusVV** [comment]
Hello @Dev-CH.
I also got the same problem.
To fix this issue, I added the event handler to 'orientationchange' and manually changed styles.

Not the best solution, but the solution.

**Comment by krisz094** [comment]
> Hello @Dev-CH.
> I also got the same problem.
> To fix this issue, I added the event handler to 'orientationchange' and manually changed styles.
> 
> Not the best solution, but the solution.

I'm currently facing the same problem. 
What do you mean by manually changing styles?

**Comment by stefanmdt** [comment]
> Hello @Dev-CH.
> I also got the same problem.
> To fix this issue, I added the event handler to 'orientationchange' and manually changed styles.
> 
> Not the best solution, but the solution.

The bug is still there. Which styles can be used?

**Comment by jcesarmobile** [comment]
we have this issue to remove the bar, closing https://github.com/apache/cordova-plugin-inappbrowser/issues/604
