### ISSUE TITLE
usewkwebview = yes crash iOS 9.X

### ISSUE THREAD

**Issue by yelban** [apache/cordova-plugin-inappbrowser#323]
usewkwebview=yes will crash on iOS 9.0 ~ 9.3
10.3.1, 11.0.1, 12.0 work correctly.

Xcode debug console output
XApp[16531:942778] -[WKWebViewConfiguration setIgnoresViewportScaleLimits:]: unrecognized selector sent to instance 0x7fcabdd1fe00

XApp[16531:942778] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setIgnoresViewportScaleLimits:]: unrecognized selector sent to instance 0x7fcabdd1fe00'
...
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by NishVincent** [comment]
I dont think wkwebview will work on ios  9.0 - 9.3
it has to fallback to uiwebview

Would it be ok to try this option ?

const options = {
        location: 'yes',
        clearcache: 'yes',
        clearsessioncache: 'yes',
        enableViewportScale: 'yes'
      }

      if (ionic.Platform.isIOS() && parseInt(ionic.Platform.version()) > 9) {
        options.usewkwebview = 'yes'
      }

      $cordovaInAppBrowser.open(encodeURI(URL), '_blank', options);
