### ISSUE TITLE
Hide both location and toolbar on ios

### ISSUE THREAD

**Issue by yangnana11** [apache/cordova-plugin-inappbrowser#327]
Hello,

I would like to disappear the toolbar and url address for ios. But it seems it doesn't work.
```
inAppBrowserRef = cordova.InAppBrowser.open('url', '_blank', 'location=no, zoom=no, toolbar=no');
```
The toolbar just being there. What is the problem?

**Comment by thesourav123** [comment]
Same issue I am seeing on Android

**Comment by eros2187** [comment]
you solved? I'm trying to do the same on android but on ios no how can I do?

**Comment by eros2187** [comment]
> Ciao,
> 
> Mi piacerebbe scomparire la barra degli strumenti e l'indirizzo dell'URL per iOS. Ma sembra che non funzioni.
> 
> ```
> inAppBrowserRef = cordova.InAppBrowser.open('url', '_blank', 'location=no, zoom=no, toolbar=no');
> ```
> La barra degli strumenti è solo lì. Qual è il problema?

you solved? I'm trying to do the same on android but on ios no how can I do?

**Comment by yangnana11** [comment]
On Android, you just need to set location=no

For Ios:
Remove the ios platform first
```
cordova platform rm ios
```
Go to the plugin folder, modify the cordova-plugin-inappbrower\ios\CDVInAppBrowser.m and set the location and toolbar height to zero
```
#define    TOOLBAR_HEIGHT 0.0
#define    STATUSBAR_HEIGHT 20.0
#define    LOCATIONBAR_HEIGHT 0.0
```
Add the ios platform again, build and run it
```
cordova platform add ios
cordova build ios
cordova run ios
```
