### ISSUE TITLE
loadError raise NSURLErrorDomain error -999 on iOS

### ISSUE THREAD

**Issue by vdias38** [apache/cordova-plugin-inappbrowser#329]
Hi,

I've experienced error "NSURLErrorDomain error -999" on iOS (tested on iOS12) using cordova-plugin-inappbrowser@3.0.0 with cordova-ios@4.5.4

![image](https://user-images.githubusercontent.com/32454870/47361098-825fd080-d6a7-11e8-95c7-2f9876153c0a.png)

```
var ref = window.open(url, target, options);

ref.addEventListener('loadstart', loadStartCallBack);
ref.addEventListener('loadstop', loadStopCallBack);
ref.addEventListener('loaderror', loadErrorCallBack);
			
function loadErrorCallBack(params) {
  
  $('#status-message').text("");
  
  var scriptErrorMesssage =
  "alert('Sorry we cannot open that page. Message from the server is : "
  + params.message + "');"
  
  ref.executeScript({ code: scriptErrorMesssage }, executeScriptCallBack);
  
  ref.close();
  
  ref = undefined;
}

function executeScriptCallBack(params) {
  
  if (params[0] == null) {
    
    $('#status-message').text(
      "Sorry we couldn't open that page. Message from the server is : '"
      + params.message + "'");
  }
}
```
I've found a workaround on following [issue](https://github.com/dropbox/dropbox-sdk-js/issues/196#issuecomment-397460384). It works well only if I remove `ref.addEventListener('loaderror', loadErrorCallBack);`

**Comment by frederikbosch** [comment]
I am also having trouble with `Load Error`. For me it happens when loading an url that redirects http to http**s**.

**Comment by jcesarmobile** [comment]
999 happens when a request is canceled, so it makes sense that it happens when it redirects as some request that has started before the redirect will be canceled. 
But InAppBrowser should probably ignore it

**Comment by VisualMafia** [comment]
Add option for IOS: 'usewkwebview=yes'

Config:
<preference name="WKWebViewOnly" value="true" />

IOS 5.1.0 and higher

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
