### ISSUE TITLE
Change ios inappbrowser default value for browserOptions.usewkwebview

### ISSUE THREAD

**Issue by jonathanli2** [apache/cordova-plugin-inappbrowser#335]
For the new ios inappbrowser plugin, it uses usewkWebView to decide whether using UIWebView or WKWebView, and the default value is NO.

Assuming a cordova project currently uses UIWebView for inappbrowser plugin and cordova main webview. Later the project is upgraded to use wkwebview, usually the developers want to use wkwebview in both inappbrowser and main webview after the upgrading. In that case, the developer needs to update the project to explicitly set the browserOptions.usewkwebview in all the places when inappbrowser is opened. 

This change can be avoided if the default value of browserOptions.usewebview can be decided based on the main cordova UIWebView type. So in case the caller does not explicitly set the browserOptions.usewebview value, if the main cordova UIWebView uses wkwebview, then inappbrowser can automatically set usewkwebview to true. Otherwise setting it to false. 

With this approach, the project can be upgraded to use wkwebview without any change the code. While it still allows developers to explicitly set usewkwebview if the default behavior does not fit.

This approach is currently used in our cordova projects, but if this is a common issue for others, then it makes sense to have this logic implemented in inappbrowser plugin.
 
Thanks
Jonathan

**Comment by janpio** [comment]
WKWebView support in this plugin is very new, not even really released yet. Changing the default to use ti only makes sense after this new functionality has been tested a bit by a few users and apps.

**Comment by mtlehtin** [comment]
Hi!

When is 3.1.0 with WkWebView planned to be released?

We have a bug in our app with InAppBrowser + UiWebView combination. I tested with master-branch changes and the bug did not appear anymore. So I really liked to update the inappbrowser-plugin.

**Comment by janpio** [comment]
No ETA. You can fork `master` and use your fork if you want to pin a specific state.

**Comment by mtlehtin** [comment]
Ok. I'll give it a try. Master should be "stable"?

**Comment by janpio** [comment]
Not really, if we knew it was totally good we could "just" release it ;)

**Comment by bentleyo** [comment]
@janpio how far away is a release with wkwebview? What are the known problems?

**Comment by jcesarmobile** [comment]
usewkwebview option is gone, the plugin only uses WKWebView now, closing
