### ISSUE TITLE
Help: How to reference the definition file?

### ISSUE THREAD

**Issue by kabua** [apache/cordova-plugin-inappbrowser#346]
I hope this is a dumb `TS 101` question, but we can't seem to figure it out.

We are porting the the following code snippet to TypeScript: 
```
this._popup = cordova.InAppBrowser.open(params.url, this.target, this.features);
```

However, we are getting the following error:
```
[ts] Property 'InAppBrowser' does not exist on type 'Cordova'. [2339]
```
Therefore we ran:
```
npm i -D cordova-plugin-inappbrowser
```
Okay, we now have access to the `...\cordova-plugin-inappbrowser\index.d.ts` file but the issue still exists. We've tried all kinds of ways to using `import` but nothing seam to be working.

What are we doing wrong? 

As a work-a-round we are doing this:
```
const localCordova = <any> cordova;
this._popup = localCordova.InAppBrowser.open(params.url, this.target, this.features);
```

Thanks.

**Comment by jcesarmobile** [comment]
`/// <reference types="cordova-plugin-inappbrowser" />`

**Comment by g-mack** [comment]
Hi, I have the same problem after removing depricated npm package "@types/cordova-plugin-inappbrowser".

I already tried 
`/// <reference types="cordova-plugin-inappbrowser" /> `
which correctly imports relevant type information, but 
`cordova.InAppBrowser` 
throws exception "Property 'InAppBrowser' does not exist on type 'Cordova'."

I checked the index.d.ts files in your repository and saw that there was an update to the file 2 month ago which added 

`interface Cordova {
    InAppBrowser: InAppBrowser;
}`

**but I think this version is not yet pushed to NPM?**

BR,

Gerhard

**Comment by janpio** [comment]
Latest release is from April.

**Comment by jcesarmobile** [comment]
You can check the package details here
https://www.npmjs.com/package/cordova-plugin-inappbrowser

as you can see, latest release was 8 months ago, so yeah, those changes are not released yet
