### ISSUE TITLE
beforeload event throws "Method 'loadAfterBeforeload:' not defined in Plugin 'InAppBrowser'" when callback is called

### ISSUE THREAD

**Issue by guycalledseven** [apache/cordova-plugin-inappbrowser#349]
I am very interested in PR #276 (beforeload event) by @wvengen , but in current master it does not work anymore. PR did not work for me completely after it was merged but did not throw errors (after closing IAB it would cause major issues). But at some point it started reporting errors.

I pinpointed commit which broke functionality (at least for me on IOS) - https://github.com/apache/cordova-plugin-inappbrowser/commit/c41f5b51317e0070b3b163f5ccde52bc20ab0651

After this commit this is the error which shows when callback is called from inside the listener.
```
ERROR: Method 'loadAfterBeforeload:' not defined in Plugin 'InAppBrowser'
2018-11-20 15:12:48.310426+0100 IZZI[2373:503538] FAILED pluginJSON = ["INVALID","InAppBrowser","loadAfterBeforeload",["https:\/\/www.example.com\/"]]
```

example usage:
```
declare var window:any;
...
const app = window.cordova.InAppBrowser.open(url, "_blank", 'beforeload=yes');
app.addEventListener('beforeload', this.beforeloadCallback);
...
private beforeloadCallback(params, callback) {
	callback(params.url);
}
```

My `params` var contains: `{"type":"beforeload","url":"https://www.example.com/"}`
My `callback` var contains:

```
function (strUrl) {
strUrl = urlutil.makeAbsolute(strUrl);
exec(null, null, 'InAppBrowser', 'loadAfterBeforeload', [strUrl]);
}
```

**Comment by janpio** [comment]
So current master is broken for you on iOS?

**Comment by guycalledseven** [comment]
yes @janpio , calling `callback (e.url)` causes 
```
ERROR: Method 'loadAfterBeforeload:' not defined in Plugin 'InAppBrowser'
```

**Comment by dpa99c** [comment]
Looks to me like this was [merged across from master into the UIWebView implementation](https://github.com/apache/cordova-plugin-inappbrowser/pull/271/commits/19c6dfe1971818789a4b3e83f6f4b0793e401597#diff-7405c419b969bb1bdbbc1aaaa42ff10dR321) while on the [WKWebView PR](https://github.com/apache/cordova-plugin-inappbrowser/pull/271) branch (which is [now merged to master](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/ios/CDVUIInAppBrowser.m#L319)) but it hasn't yet been patched into the [WKWebView implementation](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/ios/CDVWKInAppBrowser.m#L372).

**Comment by dpa99c** [comment]
The `loadAfterBeforeload` method is not currently exposed in the [dispatcher interface](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/ios/CDVInAppBrowser.h), so won't currently be available to either implementation.

**Comment by dpa99c** [comment]
@janpio I'll put together a PR to resolve this, i.e. patch it into the WKWebView implementation and expose it in the dispatcher so it's usable via both implementations.

**Comment by dpa99c** [comment]
The above PR should fix it for both iOS implementations

**Comment by guycalledseven** [comment]
@dpa99c can confirm, your PR fixes it (tested your branch GH-349-loadAfterBeforeload_not_defined)

👍🙌🎉

**Comment by wvengen** [comment]
Thank you so much for fixing this :+1:
And good to hear there's interest in the feature :)

**Comment by milanorszagh** [comment]
Is it just me or is master currently broken for Android 7 and lower?
