### ISSUE TITLE
Doesn't support android devices with right to left orientation languages

### ISSUE THREAD

**Issue by transoceanic** [apache/cordova-plugin-inappbrowser#352]
The toolbar of such devices looks broken (no location field)
![image](https://user-images.githubusercontent.com/2249462/48892682-4905b680-ee47-11e8-8d4e-bd37dbadd714.png)

**Comment by janpio** [comment]
Can you possibly share a screenshot of the same screen with RTL disabled for context?

**Comment by transoceanic** [comment]
![image](https://user-images.githubusercontent.com/2249462/48899428-4069ac00-ee58-11e8-860b-3abad373ccca.png)

**Comment by janpio** [comment]
Thanks. 
As you are at it: Can you maybe test this in iOS as well?

Also, as I have no experience with RTL interfaces at all and you seem to have to - how _should_ the Android RTL interface look like if it wasn't broken?

What Android version and Android device are you testing with?

**Comment by transoceanic** [comment]
![screenshot_20181122-133435](https://user-images.githubusercontent.com/2249462/48900719-d5ba6f80-ee5b-11e8-8cac-e9b5b1cf0b5e.png)

**Comment by janpio** [comment]
Thanks, did you build this in Photoshop now or how did you get this correct screenshot?

Please also see my other questions.

**Comment by transoceanic** [comment]
I edited this plugin

**Comment by transoceanic** [comment]
iOS look correct
Android versin 7.0
Samsung Galaxy S7

**Comment by transoceanic** [comment]
How can I do this?

**Comment by janpio** [comment]
How many files did you have to change?

The generell process is as follows:
You create a "fork" of this repository, then you change something in it, then create a Pull Request back to this repository. We can then accept those changes.

If you only changed one or a few files, there is a simple way to achieve this: Go to the correct file in this repository and click the Edit pen. You can then copy over your code changes. Then save or submit those changes, it will create the fork you in the background and then even ask if you want to open a Pull Request. This should match this process: https://help.github.com/articles/editing-files-in-another-user-s-repository/

If this doesn't work for your (please try, it is a very useful skill to have!) you can also just attach your file to a comment here by dragging the file into the text area. This will upload the file, and someone else can create the PR then.
