### ISSUE TITLE
Android Class Not Found

### ISSUE THREAD

**Issue by karigarweb** [apache/cordova-plugin-inappbrowser#355]
Everything was working great on android before and it is still rendering perfectly on iOS but few days back when our packages got updated to latest version we started to get following exceptions in android:

> 11-23 17:46:51.936 7279-7364/com.grapplers.wrapper W/System.err: java.lang.ClassNotFoundException: org.apache.cordova.inappbrowser.InAppBrowser
> 11-23 17:46:51.963 7279-7364/com.grapplers.wrapper I/System.out: Error adding plugin org.apache.cordova.inappbrowser.InAppBrowser.

We tried basic troubleshooting techniques like:

- Reinstalling the inappbrowser plugin
- Removing & Adding back android platform
- Even tried this on fresh project but failed with same error

**Comment by janpio** [comment]
This was a bug of cordova-android 7.1.3 which was fixed with the release of 7.1.4. Make sure you are running this version of cordova-android and report back. Thanks.

**Comment by karigarweb** [comment]
Yes, this is fixed with the upgrade. Thank you 👍
