### ISSUE TITLE
open url about:blank doest trigger events

### ISSUE THREAD

**Issue by dmitryuk** [apache/cordova-plugin-inappbrowser#364]
`let browser = cordova.InAppBrowser.open('about:blank', '_blank', [
                    'location=yes',
                    'hideurlbar=yes',
                    'hidenavigationbuttons=yes',
                    'toolbarcolor=#8a3bab'
                ].join(','));`

After browser opened, loadstart and loaderror events doesn't trigger.

**Comment by dpa99c** [comment]
Can you give some more information:

- What platform were you testing on? (e.g iOS, Android)
- What platform version? (e.g. iOS 12.1)
- Was it a device or simulator?
- What version of this plugin were you testing?
