### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by dpa99c** [apache/cordova-plugin-inappbrowser#366]
Currently this repo has a [PR template](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/.github/PULL_REQUEST_TEMPLATE.md) but not an issues template, and as a result the issues opened are often lacking important information such as what platform was being tested and what version of the plugin, etc.

We should create on of these and then hopefully issues will be easier to diagnose/eliminate.

**Comment by janpio** [comment]
Work is in progress for this: https://github.com/apache/cordova-contribute/blob/master/github-templates.md
This part here is missing: https://github.com/apache/cordova-contribute/blob/master/github-templates.md#distribute-github-templates-to-all-repositories
Discussion about tool support for this ongoing here: https://lists.apache.org/thread.html/6dc36e320b810d41f28c5cdca136aeb8434adf94d8070ef54b35f25b@%3Cdev.cordova.apache.org%3E

**Comment by dpa99c** [comment]
That will be a massive help

**Comment by janpio** [comment]
If you are in a hurry, feel free to create a PR adding those here yourself, that can be merged pretty quickly. Thanks.

**Comment by dpa99c** [comment]
I'll leave it up to you guys since it looks like you're developing a standardised template for all the Cordova plugins, so I wouldn't want to screw up the conformity with my own quirky version 😉 

But I'll leave this open to capture the requirement anyway.

**Comment by janpio** [comment]
The first link I commented includes the templates, the are pretty much ready. I am currently just blocked by not wanting to copy that to 30 repos and branch, commit, push, and create a PR for them manually.

**Comment by timbru31** [comment]
@janpio - haven't you added an issue template to all repos?

**Comment by janpio** [comment]
I did and this is now in this repo as well:
![image](https://user-images.githubusercontent.com/183673/56666527-61a32280-66ac-11e9-8c9f-37240439ac56.png)

I think this can be closed then.

Did you observe an improvement in issue quality @dpa99c?
