### ISSUE TITLE
In-App Browser errors when using npm and webpack

### ISSUE THREAD

**Issue by datazen** [apache/cordova-plugin-inappbrowser#375]
I have a site that is Angularjs based and uses NPM and Webpack.   While the site runs fine in all browsers, it does not load within the in-app browser if suing any target other than _system.   If I use _self or _blank I get the following errors when loading:

INFO:CONSOLE(2)] "Uncaught SyntaxError: <unknown message reserved_word>", source: https://ser.vi/app.e75262e3.js (2)
I/chromium( 8992): 

[INFO:CONSOLE(2)] "Uncaught Error: [$injector:modulerr] Failed to instantiate module servi due to:
I/chromium( 8992): Error: [$injector:nomod] Module 'servi' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Angular sites that do not use webpack are not having any issues.   If I use webpack I get errors.   We are running on Heroku platform if that makes any difference.

Thanks in advance for any help.

**Comment by janpio** [comment]
What platform and version?

**Comment by datazen** [comment]
Jan,

It's Android platform with version "cordova-plugin-inappbrowser": "^3.0.0"

We have a few sites running Angularjs.   One uses webpack and the other
does not.   I can view the latter in the in-app browser with no issue.  If
I try to load the Angularjs site using webpack, I get errors.

These sites work:

https://google.com
https://hq.ser.vi

This one does not work:

https://ser.vi

Any ideas?

Thanks in advance.

Scott Logsdon
scott@ser.vi

**Comment by datazen** [comment]
Updated to new Angular 7 and have no issues now.   Just say no to AngularJS 1.x
