### ISSUE TITLE
No listener to the opened url in _system browser

### ISSUE THREAD

**Issue by engharb** [apache/cordova-plugin-inappbrowser#385]
Hello,
Here is my test
```
let browser = this.iab.create(myUrl, "_system");

browser.on('loadstart').subscribe(); // does not work
```

The event will never be fired by opening a url using system browser. I want to read the url and other features, but I do not have (or inAppBrowser does not have) control , listening to browser or triggering an event. 

Env:
- Ionic-core: 4,
- cordov,
- angular5,
- typescript

Do you have any suggestion?

**Comment by jcesarmobile** [comment]
_system opens the safari/chrome browsers, there is no way of listening for those events, it's documented that it only works for _blank
