### ISSUE TITLE
Plugin fails for osx platform under Xcode 10.1

### ISSUE THREAD

**Issue by Brianfit** [apache/cordova-plugin-inappbrowser#387]
Error message: 

> Plugin 'InAppBrowser' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml

config.xml:

` <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />`

CDVInAppBrowser.m and CDVInAppBrowser.h are present in the plugins directory.

**Comment by Brianfit** [comment]
Anyone have a workaround to sending a user from an OSX app to a web page without the plugin? I have compiled with legacy settings, confirmed the presence of the plugin file and the validity of the path, but the app complies fine then trips at run time  with the error that it's not a valid plugin, which we know is not the case, or that it can't be found, which I can't explain. Other plugins in the same directory are found and run without issue.

**Comment by comewalk** [comment]
Hi, FYI, I had same issue. I solved this like following diff. 

```diff
     <feature name="InAppBrowser">
-        <param name="ios-package" value="CDVInAppBrowser" />
+        <param name="ios-package" value="CDVWKInAppBrowser" />
     </feature>
```

**Comment by erisu** [comment]
[Cordova OSX](https://cordova.apache.org/announcements/2022/03/22/osx-deprecation.html) has been deprecated and is no longer supported making this issue obsolete.
