### ISSUE TITLE
Clear Cache not working on Windows

### ISSUE THREAD

**Issue by syedsaadmahmood** [apache/cordova-plugin-inappbrowser#393]
let browser = this.iab.create('url', '_blank', 'location=no,toolbar=yes,closebuttoncaption=Done,EnableViewPortScale=yes,clearcache=yes,clearsessioncache=yes');

The cache is cleared in IOS and Android but not on windows.

**Comment by syedsaadmahmood** [comment]
Well I found in the documentation that clear cache is not supported in windows. Is there any work around?

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
