### ISSUE TITLE
Spinner on iOS

### ISSUE THREAD

**Issue by JoshTor** [apache/cordova-plugin-inappbrowser#394]
Hi,
When I open a Cordova Inappbrowser on iOS, the spinner still showing even if i specified 
> hidespinner=yes

in the options. On Android, it works fine.
My call : 

`<a class="button tab-link" onclick="cordova.InAppBrowser.open('http://www.google.com/', '_blank', 'location=yes,toolbarposition=bottom ,closebuttoncaption=Retour, hidespinner=yes');">`

Using cordova-plugin-inappbrowser 3.0, cordova-ios 4.5.5, and framework7

**Comment by jcesarmobile** [comment]
hidespinner option is not released yet
