### ISSUE TITLE
window.open crashed mobile app

### ISSUE THREAD

**Issue by modimoni** [apache/cordova-plugin-inappbrowser#399]
On Google Pixel with Android Pie I am getting a app crash on window.open.

window.open(cordova.file.dataDirectory+"/test.html");

I download the test.html" inside the app and trying to open it , my expectation is to load it in the same instance or "_self"

The code was working fine till some additional plugins were added to my application. Do we  need any specific permission to have "_self" working . If I open with "_blank" and "_system" it works but that is not what I need.

Thanks
Modi

**Comment by dpa99c** [comment]
So you are running this to load `test.html` into the main Cordova app Webview?

    window.open(cordova.file.dataDirectory+"/test.html", "_self");

And presumably you have set:

    window.open = cordova.InAppBrowser.open;

If that's what you want to do (which seems a really bad idea), then use this:

    window.location = cordova.file.dataDirectory+"/test.html"

This plugin is not designed to be used to control the main app Webview,

**Comment by NiklasMerz** [comment]
@modimoni Is this issue solved for you? If the answer solves your problem, feel free to close the issue.

**Comment by jcesarmobile** [comment]
closing as there was no response
