### ISSUE TITLE
Opening external links in _blank Cordova inAppBrowser

### ISSUE THREAD

**Issue by vascosilvaa** [apache/cordova-plugin-inappbrowser#404]
I am trying to run a web application in a cordova webview. My only purpose is to have my responsive app running on devices with FCM notifications. FCM notifications and all the rest are working well at this moment.

I am using:

inAppBrowserRef = cordova.InAppBrowser.open('https://url.com', '_blank', 'toolbar=no');

My only problem now is when I open an external link, inside the "_blank" inappbrowser, it opens without location and options to back to my app on iOs, since there is no navigation buttons.

Is there any option to set that the links inside a _blank webview should open externally or in a _system webview?

Thanks for the help.

**Comment by jcesarmobile** [comment]
You can probably listen for loadStart event and do something with the url, but what you want it's not supported at the moment.
