### ISSUE TITLE
Does the window.open function get automatically replaced by this module's version?

### ISSUE THREAD

**Issue by FarhadG** [apache/cordova-plugin-inappbrowser#405]
It appears that we would need to automatically update the `window.open` with this module's version if we want to update it globally (i.e. `window.open = cordova.InAppBrowser.open;`), however, it seems to work right out of the box. What's the expected behavior?

**Comment by janpio** [comment]
From the docs:

> For backwards compatibility, this plugin also hooks `window.open`. However, the plugin-installed hook of `window.open` can have unintended side effects (especially if this plugin is included only as a dependency of another plugin). The hook of `window.open` will be removed in a future major release. Until the hook is removed from the plugin, apps can manually restore the default behaviour:
> 
> `delete window.open // Reverts the call back to its prototype's default`

So it is expected that InAppBrowser takes over.

**Comment by FarhadG** [comment]
Thank you!
