### ISSUE TITLE
Resize the IAB

### ISSUE THREAD

**Issue by piterio19** [apache/cordova-plugin-inappbrowser#409]
Hello,
After some reading I understand that IAB overlays the Cordova WebView completely.
I have AdMob ads showing at the bottom of my app using AdMob Pro plugin, so when I load the IAB they get hidden.

Is there any solution to this?
Otherwise can I clone the code of IAB and reduce the height of the IAB activity by those 50px I need? Where can I do that in the code?
Thanks a lot.

**Comment by jcesarmobile** [comment]
It's not possible.

You can clone and try to do it, but you'll have to figure out the where yourself.

**Comment by elrafael** [comment]
Open the file `InAppBrowser.java` and search for this code

```java
WindowManager.LayoutParams lp = new WindowManager.LayoutParams();
lp.copyFrom(dialog.getWindow().getAttributes());
lp.width = WindowManager.LayoutParams.MATCH_PARENT;
lp.height = WindowManager.LayoutParams.MATCH_PARENT;
```

It's near line 958
you'll need to change the lp.height attribute to something like this
```java
// lp.height = WindowManager.LayoutParams.MATCH_PARENT;
DisplayMetrics displayMetrics = new DisplayMetrics();
cordova.getActivity().getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);
int displayWidth = displayMetrics.widthPixels;
int displayHeight = displayMetrics.heightPixels - 200;
lp.height = displayHeight;
```

Import the Display Metrics on top of that file
```java
import android.util.DisplayMetrics;
```

**Comment by elrafael** [comment]
If you'll need align in the top and close the inappbrowser browser outside the inappbrowser, you could do this (``InAppBrowser.java``)

Search this code
```java
dialog = new InAppBrowserDialog(cordova.getActivity(), android.R.style.Theme_NoTitleBar);
dialog.getWindow().getAttributes().windowAnimations = android.R.style.Animation_Dialog;
```

Replace with this
```java
dialog = new InAppBrowserDialog(cordova.getActivity(), android.R.style.Theme_NoTitleBar);
dialog.getWindow().getAttributes().windowAnimations = android.R.style.Animation_Dialog;
dialog.getWindow().getAttributes().gravity = Gravity.TOP;
```

And in this code block
```java
dialog.setCancelable(true);
```

Add this
```java
dialog.setCanceledOnTouchOutside(true);
```

**Comment by markarupert** [comment]
I gave the code changes [elrafael](https://github.com/elrafael) posted above. I was able to get it to work and provide space at the bottom where I want to put buttons. But when I press the buttons it automatically closes the IAB. My goal is to use the buttons to go to different URL's and hide the currently opened one programmatically so I can keep the session when I come back.
