### ISSUE TITLE
inappbrowser with usewkwebview not open the links with <a href=.. target=_blank>

### ISSUE THREAD

**Issue by mosababubakr** [apache/cordova-plugin-inappbrowser#417]
My app using inappbrowser to open external link and work fine, and the page with that link has more links inside, 
After apple change the webview, I try to use usewkwebview=yes  in options, but there is a bug in the inappbrowser for links that opened as new tab:
e.g.:  <a href= target="_blank"></a>

Inappbrowser will not open any links with target=_blank.

So, if the user click on that link, it will not show anything, just like there is no any links.

This happened just for links with <a href= target="_blank"></a>

So, any website has links with target blank, will not open in inappbrowser if the option usewkwebview is set to yes.
<a href= target="_blank"></a> // in html <a> for links
(this mean for browser : to open the link in new tab, but for inappbroswer, it should open in the same window.).

I try to open many websites that have some links to open in new tab (with target=_blank) via inappbrowser, but nothing happened.

Apple change the webview and inappbrowser without usewkwebview=yes will not work for ios devices, so any websites has <a href with target=_blank will not open.

Inappbrowser before i set wkwebview to yes was work fine, but after apple change the webview, some websites not work, so i set to use wkwebview to yes and work fine except any links with target = _blank.

Please solve this issue as soon as possible.

Please note that i am using the master version of cordova inappbrowser plugin to test my app.

@dpa99c 
@timbru31 
@janpio

**Comment by dpa99c** [comment]
Please confirm if you are using `target=blank` or `target=_blank` since the latter is valid and the former is not - see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

**Comment by mosababubakr** [comment]
Hello  @dpa99c 
I am using target=_blank,

I try to open many websites that using some links to open in new tab, but inappbrowser with wkwebview=yes not open those links.

Regards

**Comment by dpa99c** [comment]
I could reproduce the issue on iOS/WKWebView and have implemented a solution based on https://stackoverflow.com/a/25853806/777265 as PR #418

**Comment by mosababubakr** [comment]
hello @dpa99c ,

Thank you for response,

Can you please tell me when this will affect the master version ? or how can i put the plugin with this implemented solution ?

**Comment by mosababubakr** [comment]
@dpa99c  @janpio  Thanks for solve the issue, but there still another issue with inappbrowser when wkwebview=yes.!
Issue details:
if you try to open external websites like: trivago.com , expedia.com , hotelscombined.com and try to search for hotels and try to make reservation or booking, blank screen appear and some websites display warning message.

Can you please try to open https://www.trivago.com/ in inappbrowser ? you will see what i mean, try to open any website like agoda.com or any booking websites, and try to make a booking, you can't make bookings, i don't know why this happened , I know that whitelist not affect inappbrowser, I think this behavior like you can't access websites like for bookings.

My app using affiliate program to compare prices from booking websites, after apple change the webview, I set in approwser to use wkwebview, but after this change, I can't make booking in hotels and travel sites. my app try to compare prices via inappbrowser.

Can you please check the problem ?

Try to open links in inappbrowser such as: 
https://www.agoda.com/
https://www.trivago.com/
https://www.expedia.com/

And try to make click on reserve room or book room button and you will see what i mean !

Thanks

**Comment by janpio** [comment]
Create a new issue for this new problem please.

**Comment by mosababubakr** [comment]
@janpio 
https://github.com/apache/cordova-plugin-inappbrowser/issues/422

**Comment by mosababubakr** [comment]
> Create a new issue for this new problem please.

Hello, @janpio  i create an issue about this, just for confirmation:
This new issue happened after you update the code.

I try to use an old plugin : https://github.com/dpa99c/cordova-plugin-inappbrowser-wkwebview
Work fine, but <a href target="_blank"> not work, so when you update the new code you make a new issue , can you please test the issue , just try to open any website inside inappbrowser, and you will see the issue

**Comment by mosababubakr** [comment]
@janpio @dpa99c please check the previous updated code, now: you can't open any websites, HEADER BROWSER HAVE AN ERROR
