### ISSUE TITLE
App using inappbrowser cannot be hosted in a cross-domain iframe

### ISSUE THREAD

**Issue by webprofusion-chrisc** [apache/cordova-plugin-inappbrowser#419]
If you attempt to use inappbrowser within an app (for mobile and web) and iframe the web version from
a different domain chrome will block the plugin load:
https://www.chromium.org/Home/chromium-security/corb-for-developers

This is caused by a check to window.parent for the ripple extension.

Use case: https://map.openchargemap.io - this app is available on android and iOS but is also available as a PWA which can be embedded by other sites.

Workaround: add a build step to remove inappbrowser for `browser` platform: `cordova remove plugin cordova-plugin-inappbrowser` - is there any other way to selectivity disable a plugin by platform?

**Comment by niklasdoerflerkrone** [comment]
I've faced exactly the same problem...
Are there any other solutions or fixes for this now?

**Comment by stefanmdt** [comment]
Same problem. Any news on that?

**Comment by csware** [comment]
A hack could be `perl -pi -e 's|if \(window.parent && !!window.parent.ripple\) \{|if (window.parent && false) {|' platforms/browser/www/plugins/cordova-plugin-inappbrowser/www/inappbrowser.js`
