### ISSUE TITLE
executeScript not working in ionic 3

### ISSUE THREAD

**Issue by karthikajjan** [apache/cordova-plugin-inappbrowser#421]
I am using this plugin in ionic 3.
Here is the piece of code

` const browser = this.iab.create('https://example.com, '_blank', {hidden:'yes'});

    browser.on('loadstop').subscribe(function(event) {
      setTimeout( () => {
        browser.executeScript({ 
          code: "document.body.innerHTML" 
        }).then((data)=>{
          console.log('script')
        });
      }, 2000);
    });`

loadstop event is working fine, but executeScript doesn't work.

![sage](https://user-images.githubusercontent.com/4723648/52557140-98d79680-2e14-11e9-90c8-59e1547d8f21.png)

**Comment by ianhowe76** [comment]
what platform is this on?

**Comment by karthikajjan** [comment]
> what platform is this on?

Facing same issue in both ios and android platform

**Comment by karthikajjan** [comment]
For android, it throws following error,
![sage](https://user-images.githubusercontent.com/4723648/53090129-717b7a80-3534-11e9-9633-7a7f8583af3a.png)

**Comment by pmurpmur** [comment]
I was able to circumvent this issue by not using the Ionic-Native library and interfacing with Cordova directly. In other words, try code similar to this:

```
const browser = cordova.InAppBrowser.open('https://example.com, '_blank');

browser.addEventListener('loadstop', () => {
  setTimeout(() => {
    browser.executeScript({ 
      code: 'document.body.innerHTML'
    }, (data) => {
      console.log('script')
    });
  }, 2000);
});
```

**Comment by karthikajjan** [comment]
Issue resoled while downgrade native inappbrowser

`npm install --save @ionic-native/in-app-browser@4`

**Comment by abdullahkaamil** [comment]
> 

have been dealing with executeScript problem for a week , thank you pmurpmur . 
adding settimeout() resolved the issue
