### ISSUE TITLE
Ionic - Not able to click on buttons or anything after closing InAppBrowser

### ISSUE THREAD

**Issue by ten80** [apache/cordova-plugin-inappbrowser#426]
## Problem
I have some weird bug in iOS on iPad Air 2. I use the InAppBrowser to open Google.com in a new window.
I click into the search field from Google.com the keyboard opens, then i click the close button from the InAppBrowser. The Browser is gone, but now i'm not able to click on buttons in my view, i'm also not able to scroll, i can do nothing. I happens not all the time, but every 2nd ord 3rd time.

xCode tells me nothing, no error or something.

Maybe someone could help me out,
because i need to fix this soon :(

Thanks in advance!!!

## Checklist

- [x] I searched for existing GitHub issues
- [x]  I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpa99c** [comment]
- What version of this plugin are you using?
- What version of iOS are you testing on?
- What `cordova-ios` platform version?
- What options are you passing to open the inappbrowser? e.g. `usewkwebview=yes`, `hidden=yes`, etc.

**Comment by ten80** [comment]
i'm using the newest version of the plugin on iOS 12.1.
i use 8.1.2 (cordova-lib@8.1.1) and this are my options:

        const browser = this.iab.create('https://www.google.com','_blank',{
            location:'no',
            mediaPlaybackRequiresUserAction: 'yes',
            clearcache: 'yes',
            clearsessioncache: 'yes',
            cleardata: 'yes',
            closebuttoncolor: '#FFFFFF',
            closebuttoncaption: 'Close',
            disallowoverscroll: 'yes',
            hidenavigationbuttons: 'no',
            navigationbuttoncolor: '#FFFFFF',
            toolbar: 'yes',
            toolbarcolor: '#E10000',
            toolbarposition: 'top'
        });

        browser.on('loadstop').subscribe(event => {
            browser.executeScript({code: '(function() { localStorage.clear(); return true; })()'});
        });

i also tried to make a alert box before opening, but after closing i'm also not able to click "okey" on the alert. example: alert("test");

**Comment by dpa99c** [comment]
Try using the newest development version on github master (3.1.0-dev):

    cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser

If you are including a WKWebView plugin in your project, set `usewkwebview=yes` in the inappbrowser options.

**Comment by ten80** [comment]
Still not working :(
I tried it with the 3.1.0-dev and added the option usewkwebview: 'yes'

**Comment by dpa99c** [comment]
Please try building and running my test harness project: 
https://github.com/dpa99c/cordova-plugin-inappbrowser-test

To eliminate any possible cause within your codebase.

**Comment by ten80** [comment]
Okey, after a big brainfuck, and testing, i started with a new ionic project, added all plugins, copied all files and somehow, i dont know why, the bug is gone 👍 
I'm sorry for "wasting" your time :(

**Comment by zettvs** [comment]
I experienced the same annoying bug today... It was only happening after I input something into a text field. I noticed some other nasty things happening after the device's keyboard shows and hides: many UI elements became unresponsive – it felt like something related to the resize of the webview.

Turned out I had an outdated `cordova-plugin-ionic-keyboard` installed (but somehow not even listed in `config.xml`) – removing and adding back the latest version of that plugin only fixed it for me.

**Comment by dpa99c** [comment]
Can this also now be closed? Since it's not related to a bug with this plugin...

**Comment by ten80** [comment]
> Can this also now be closed? Since it's not related to a bug with this plugin...

yes

**Comment by goynov** [comment]
Installing 3.1.0-dev solved the issue in my case:
https://github.com/apache/cordova-plugin-inappbrowser/issues/334

**Comment by jcesarmobile** [comment]
closing
