### ISSUE TITLE
inappbrowser not displayed correctly on iPhone X

### ISSUE THREAD

**Issue by mosababubakr** [apache/cordova-plugin-inappbrowser#428]
# Bug Report

### What is expected to happen?
Inappbrowser layout should display correctly in iPhone x after inappbrowser.show take the effect, I attached a screenshot from iPhone x regarding this issue.

![iphone-x-inappbrowser-new-issue](https://user-images.githubusercontent.com/47486787/52969350-bc708300-33b8-11e9-80da-b6786443ef1c.jpg)

Please try to open inappbrower and test from iphone x, and you will see the issue that the inappbrowser not fit the screen as well (upper side of screen).

### What does actually happen?
After inappbrowser window appear, the layout of inappbrowser not set correctly in the iphone X screen, specially in the upper side, under the status bar.
So the clock time, connection cellular and the battery status in the status appear as crossed to the upper side of inappbroswer.

Please refer to attachment image to see the issue.

## Information

I attached a screenshots regarding this issue.

* Please note that: this issue not appear on previous iphone versions like: 8, 7, 6 ...

### Environment, Platform, Device

IOS 12.1 - iPhone X

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Please, don’t ping people to get attention.

**Comment by janpio** [comment]
I removed all the people you pinged @mosababubakr from the post. Please don't do that.

**Comment by mosababubakr** [comment]
Hello @janpio 
I just made the mention to the Contributors to see this issue not for wasting the time, so, I fount a problem and mention the people who was in the Contributions list.

This issue should fix as soon as possible, because it make negative point to this plugin.

Regards
