### ISSUE TITLE
iOS - webView reboot

### ISSUE THREAD

**Issue by VincentChever** [apache/cordova-plugin-inappbrowser#429]
Hi,

I'm using webView to open url. This work great on Android, but on iOS the webView reboot all the time with the following info :

![capture d ecran 2019-02-20 a 16 12 33](https://user-images.githubusercontent.com/25710871/53102751-9d92fd80-352c-11e9-8002-45d571b973c0.png)

I've add the plugin cordova-plugin-wkwebview-engine for iOS and I open the url like that :

> var target = "_self";
> var options = "location=no,zoom=no,hidden=yes,clearcache=no,clearsessioncache=no";
> if(device.platform == "iOS"){
>         options += ",usewkwebview=yes";
> }
> ref = cordova.InAppBrowser.open(url, target, options );

Platform :
`cordova-ios 4.5.5`

Did I miss something ?

**Comment by janpio** [comment]
> I'm using webView to open url.

What does "webview" refer to here? This plugin?

> but on iOS the webView reboot all the time

What does that mean?

What should that log snippet show us?

**Comment by VincentChever** [comment]
Hi,
Sorry I'm new with Cordova so I may missing some steps.
Each time I'm using _self as target I got the `IAB.close() called but it was already closed` info and then the app restart. This only happen with _self and not with other targets.
I'm not sure that it's refered directly to this plugin

**Comment by janpio** [comment]
I am just asking questions, trying to understand what is going on.

> but on iOS the webView reboot all the time

and

> and then the app restart.

seem to describe two very different things for example.

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
`_self` doesn't open the InAppBrowser, but loads the web inside cordova webview, so that's probably what causes the reboots, hard to tell without knowing your code.

**Comment by VincentChever** [comment]
Hi,

You can find the reproduction repository here : https://github.com/VincentChever/Reproduction-sample

I figure it out that everything work well until I add the [cordova-plugin-remote-injection](https://www.npmjs.com/package/cordova-plugin-remote-injection?activeTab=readme)

I'm not sure but maybe it injects the file many times which could explain why the webView is rebooting
