### ISSUE TITLE
Statusbar BLACK

### ISSUE THREAD

**Issue by bruno-delfim** [apache/cordova-plugin-inappbrowser#430]
When calling inappbrowser with _blank the statusbar becomes black

**Comment by janpio** [comment]
Is this a feature request? Then please use https://github.com/apache/cordova-plugin-inappbrowser/issues/new?template=FEATURE_REQUEST.md to request it.
Is this a bug report? Then please use https://github.com/apache/cordova-plugin-inappbrowser/issues/new?template=BUG_REPORT.md to report it.
