### ISSUE TITLE
removeEventListener not working as expected

### ISSUE THREAD

**Issue by TachyonRSA** [apache/cordova-plugin-inappbrowser#432]
# Bug Report

### What is expected to happen?
Once `removeEventListener` is called, the event listener should be removed and not be triggered again.

### What does actually happen?
The `removeEventListener` method doesn't remove the actual event listener and it gets triggered again.

## Information

I am currently using Ionic 4 with Cordova using the latest `cordova-plugin-inappbrowser`.

### Command or Code

```
//Build up the HTML to be injected
      let html = `<form id="submitForm" name="submitForm" action="${responseData.url}" method="POST" > <input type="hidden" name="MD" value="${responseData.parameters[0].value}"> <input type="hidden" name="connector" value="${responseData.parameters[3].value}"> <input type="hidden" name="TermUrl" value="${responseData.parameters[2].value}"> <input type="hidden" name="PaReq" value="${responseData.parameters[1].value}"> <input type="submit" value="Send Request"> </form>`;
      //Check if it is 3D secure or not
      if (responseData.url != undefined && responseData.url != null) {
        //3D secure transaction
        let win = window.open('https://192.168.1.134:45455/api/v1/Test', '_blank');
        win.addEventListener('loadstop', (IABE) => {
          win.executeScript({ code: "document.write('" + html + "');" }, (res) => { 
            win.removeEventListener('loadstop', () => {}); 
            debugger;
          });
        });
```

### Environment, Platform, Device

Windows 10 Pro, debugging on a Samsung Galaxy S8+

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by MatthewPringle** [comment]
Why was this closed.

I can confirm removeEventListener does not work as expected
