### ISSUE TITLE
Using master branch (version `3.1.0-dev`) postmessage funcationality not working when opening new inAppbrowser as '_system'.

### ISSUE THREAD

**Issue by kissk01** [apache/cordova-plugin-inappbrowser#433]
# Bug Report
```
browser.on('message').subscribe((event) => {
      console.log('postmessage called')
}
```
is working as expected. When opening new inAppbrowser object using '_system'. Then closing it and coming back to previous inAppbrowser from which the link was opened. In that case postmessage listener is not working anymore.
## Problem
Postmessage is not working correctly in case which is subscribed above.
### What is expected to happen?
Postmessage is working when coming back from other inappbrowser.

### What does actually happen?
Postmessage listener is not working.

### Version information

Mac iOs, Android.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpa99c** [comment]
When you open InappBrowser as `_system` you are opening the page in the system browser app (Chrome on Android/Safari on iOS) so of course the postMessage API will not work as you are now viewing the page in a different app from the one which contains the InappBrowser plugin and cross-app communication is just not possible.

@janpio This can be closed as invalid

**Comment by jcesarmobile** [comment]
Yeah, same apply to events, I tried to document it long ago, but looks like it's still not clear.
