### ISSUE TITLE
How open URL inside a tab in ionic 4

### ISSUE THREAD

**Issue by anayarojo** [apache/cordova-plugin-inappbrowser#449]
I have the next code:

```typescript
import { Injectable } from '@angular/core';
import { Registry } from '../models/registry.model';
import { Storage } from '@ionic/storage';
import { NavController } from '@ionic/angular';

import { InAppBrowser, InAppBrowserOptions } from '@ionic-native/in-app-browser/ngx';

@Injectable({
  providedIn: 'root'
})

export class BrowserService {

  // More code...

  open() {
     const options: InAppBrowserOptions = {
         zoom: 'no',
         location: 'yes',
         toolbar: 'no'
     };
     this.inAppBrowser.create(registry.text, '_self', options);
  }

  // More code...

}

```

With the previous code I get next result:

![image](https://user-images.githubusercontent.com/6903495/54484983-2a7c5e80-482e-11e9-8d1a-30880af1c219.png)

But I need include the button tabs bar

![image](https://user-images.githubusercontent.com/6903495/54484991-6fa09080-482e-11e9-99b9-00efe8c44b9a.png)

Is it possible include the **InAppBrowser** response in a angular route?

Thanks

**Comment by huthief** [comment]
Is any solution?

**Comment by dupphil** [comment]
Got the same issue. 
A solution ?

**Comment by ifbbprochris** [comment]
any update? any solution? why did you close the issue?
