### ISSUE TITLE
_system loadstart does not fire on android

### ISSUE THREAD

**Issue by githubowl** [apache/cordova-plugin-inappbrowser#453]
# Bug Report

## Problem

I am using inAppBrowser for the oAuth flow of Google on Android and have to use _system because the _blank browser is rejected by Google on Android.

### What is expected to happen?

The loadstart event should fire when the page changes as it does for _blank

### What does actually happen?

Nothing. I have seen a work around of opening with _blank and switching to _system in the event listener but this also doesn't work.

The pages are presented and the flow works, but the event doesn't fire. I have version 3.0.0 of the plugin.

### Command or Code

      $scope.ref = cordova.InAppBrowser.open(url, '_system', 'location=no');
      $scope.ref.addEventListener('loadstart', loadstart);

### Environment, Platform, Device

Android

### Version information

Ionic 1.3.1
cordova-android 6.0.0
Microsoft Visual Studio 2017 Community Edition

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpa99c** [comment]
When you specify the `_system` target, this plugin opens the target URL in the **system browser app** (Chrome on Android, Safari on iOS). I.e. a totally different app from your app. 

Therefore of course the `loadstart` event is not fired because you've opened the page in a different app from yours and no such cross-app communication is possible between your app and the system browser app so as to fire events such as `loadstart`.

**Comment by janpio** [comment]
(Maybe this should be clarified in the documentation, that for using `_system` _none_ of the plugin's functionality will really work)

**Comment by githubowl** [comment]
ok, makes sense thanks. So is there any way of following the progress of the pages with _system? it would save on plugins if possible.

**Comment by jcesarmobile** [comment]
The docs say 
> loadstart: event fires when the `InAppBrowser` starts to load a URL.

And the target docs say 
> target: The target in which to load the URL, an optional parameter that defaults to _self. (String)
> _self: Opens in the Cordova WebView if the URL is in the white list, otherwise it opens in the InAppBrowser.
> _blank: Opens in the InAppBrowser.
> _system: Opens in the system's web browser.

So only _blank opens InAppBrowser and loadstart only fires for `InAppBrowser`. I think it's clear.
