### ISSUE TITLE
iOS location issue on uploading the appstore - ask for NSLocationAlwaysUsageDescription

### ISSUE THREAD

**Issue by yoavpa-tr** [apache/cordova-plugin-inappbrowser#464]
Hi,
I got the following message from apple once I uploaded the app to the app store.

> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Does your plugin use the device location / uses an API that uses the device location?

### Reproduction

I don't get any error once I build and run the app in debug/release mode.
only got the above mail from apple once I uploaded the app store. 

### Additional Information

* org.apache.cordova.inappbrowser version:  0.2.2 
* List of installed plugins:
code-push 2.0.6 "CodePushAcquisition"
com.elasticode.cordova 2.1.7 "Elasticode Cordova Plugin"
com.etoro.chinaupdateplugin 13.0.0 "ChinaUpdatePlugin"
cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appsflyer-sdk 4.4.15 "AppsFlyer"
cordova-plugin-code-push 1.11.13 "CodePush"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-enable-multidex 0.1.3 "Enable Multidex"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-intercom 6.2.0 "Intercom"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-wechat 2.6.0 "Wechat"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
org.apache.cordova.inappbrowser 0.2.2 "InAppBrowser"
phonegap-plugin-mobile-accessibility 1.0.4 "Mobile Accessibility"
urbanairship-cordova 7.3.0 "Urban Airship
* Cordova version: 7.0.0
* iOS/Android/Windows version: 12
* Does this reproduce on a debug build or release build? NO
* Does this reproduce on a simulator, or only on a physical device? NO

**Comment by timbru31** [comment]
I'm closing this issue since it seems stale and you've probably already solved your issue. Sorry for the slow response from our end!
