### ISSUE TITLE
Inappbrowser window close when the web view refresh automatically

### ISSUE THREAD

**Issue by mv83** [apache/cordova-plugin-inappbrowser#474]
Hi, I have this problem: I'm trying to open a web page with an inappbrowser window. The webpage refresh automatically every 30 seconds. But when the page refresh, the window stops immediately and is closed. It behaviour occurs only on Android devices.
Currently I'm using Cordova 9.0 with the inAppBrowser plugin version 3.0.0.

```
This is the code that allow me to open the window:
window.open(link,'_blank','location=yes,hidenavigationbuttons=yes,hideurlbar=yes,closebuttoncaption=Close,closebuttoncolor=#707070');
```

Thanks in advance

**Comment by janpio** [comment]
Use the bug report template please:
https://github.com/apache/cordova-plugin-inappbrowser/issues/new?template=BUG_REPORT.md
