### ISSUE TITLE
Support Custom SSL truststore on Android

### ISSUE THREAD

**Issue by don-spyker** [apache/cordova-plugin-inappbrowser#485]
# Feature Request

## Motivation Behind Feature
If the inappbrowser should connect to a website via https and the SSL certificate is self-signed or issued/created with a company's root certificate the inappbrowser is not opening the website. This is also the case if you install the custom certificate on the device. The access to the website works when using target '_self' or target '_system', but not when using target '_blank'.
The inappbrowser is not even handling the error, but that is handled in #292. This issue is about enabling the inappbrowser to use the a custom truststore.

On iOS the inappbrowser is already trusting all certificates that are enabled on the devices. This issue targets Android.

## Feature Description
Trust a custom certificate to avoid SSL errors while opening a website that is secured with a non public root CA.

## Alternatives or Workarounds
Use target '_self' or target '_system' -> not appropriate in all cases
Use public CA -> -> not appropriate in all cases

**Comment by chiluhimanshu2221** [comment]
This is not the plugin issue. Android had following handshake rules to communicate with self signed ssll . I have resolved my issue by using certificate inside my build. Please follow https://developer.android.com/training/articles/security-config

**Comment by timbru31** [comment]
Thanks @chiluhimanshu2221
