### ISSUE TITLE
ERROR 404, PAGE NOT FOUND NGINX

### ISSUE THREAD

**Issue by youssame** [apache/cordova-plugin-inappbrowser#489]
platform: IOS
IONIC 4
```
 const browser = this.iab.create('https://www.google.com/','_blank',null);
    browser.show();
```
i got 404 ERROR, PAGE NOT FOUND

ANY SOLUTIONS PLEAAASE ???

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support 😉 
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

Besides that, the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.
