### ISSUE TITLE
Version 3.1.0  is not available in NPM

### ISSUE THREAD

**Issue by mhirapra** [apache/cordova-plugin-inappbrowser#499]
# Feature Request

## Motivation Behind Feature

like to use 3.1.0 version

**Comment by erisu** [comment]
Version 3.1.0 is not officially release and is in a vote. 

Please keep monitoring npmjs for when it is released.

https://www.npmjs.com/package/cordova-plugin-inappbrowser

**Comment by sithwarrior** [comment]
@erisu I was to about to post the exact same request. Maybe leave the issue open, so ppl know that the version is still pending?
