### ISSUE TITLE
Launch inapp browser at app start (starting once in two)

### ISSUE THREAD

**Issue by ctaque** [apache/cordova-plugin-inappbrowser#506]
Hello,
I am making an app which basically launches an inapp browser at startup.
The code is : 

``` js
function onDeviceReady() {
    cordova.InAppBrowser.open('https://cine.boutique', '_blank', 'location=no,fullscreen=yes,zoom=no,hardwareback=no,footer=no,toolbar=no,hidespinner=yes');
}

document.addEventListener("deviceready", onDeviceReady, false);

```
The expected behaviour is the inapp browser is lauched every time at app start.
The found behaviour is : at app start, the page is blank, and the page appears at app focus (2nd display).

### Environment, Platform, Device

iOS 12.3

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by janpio** [comment]
>  The found behaviour is : at app start, the page is blank, and the page appears at app focus (2nd display).

What does this mean?

If you want your app to just show an external URL and don't even use the local webview, you can just redirect the webview to that remote URL: https://cordova.apache.org/docs/en/9.x/config_ref/index.html#content (Note that you might have to whitelist that URL then of course etc)

**Comment by ctaque** [comment]
I mean when the app process is killed and I launch the app, the page is blank. Then I go to another app or to the home page and reopen the app (without killing process) the browser goes to the url normally.
