### ISSUE TITLE
Build error on Phonegap Build

### ISSUE THREAD

**Issue by imperyal** [apache/cordova-plugin-inappbrowser#507]
Build on Phonegap Build is failing. Only the iOS build. 

Builds fine if version 3.0.0 of this plugin is used, but fails using version 3.1.0.

### In config.xml, adding this declaration reproduces the problem.
``` 
<platform name="ios">
    <plugin name="cordova-plugin-inappbrowser" spec="3.1.0" source="npm" />
</platform>
```

Only tested using Phonegap Build, versions:
cli-8.0.0 - iOS 4.5.4 - Android 7.0.0 - Windows 5.0.0

I think they are the most recent versions available on the PGB platform.

**Comment by janpio** [comment]
You should ask the Phonegap Build people about that, the plugin is fine.

What error are you getting?

**Comment by imperyal** [comment]
The end of the log:

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in CDVWKInAppBrowser.o
  "_OBJC_CLASS_$_WKUserContentController", referenced from:
      objc-class-ref in CDVWKInAppBrowser.o
  "_OBJC_CLASS_$_WKWebViewConfiguration", referenced from:
      objc-class-ref in CDVWKInAppBrowser.o
  "_OBJC_CLASS_$_WKProcessPool", referenced from:
      objc-class-ref in CDVWKInAppBrowser.o
  "_OBJC_CLASS_$_WKWebsiteDataStore", referenced from:
      objc-class-ref in CDVWKInAppBrowser.o
  "_WKWebsiteDataTypeCookies", referenced from:
      ___52-[CDVWKInAppBrowser openInInAppBrowser:withOptions:]_block_invoke.112 in CDVWKInAppBrowser.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by imperyal** [comment]
Do you want the full log? There are 205 references to inappbrowser on there. Maybe is some incompatibility with Cordova iOS 4.5.4?

**Comment by janpio** [comment]
We can't do support for external build services, so please talk to them.

**Comment by imperyal** [comment]
Ok, no problem. Thank you.
