### ISSUE TITLE
Incorrect TypeScript typings in version 3.1.0

### ISSUE THREAD

**Issue by kamilbrk** [apache/cordova-plugin-inappbrowser#514]
# Bug Report

## Problem

Since the change to type definitions here https://github.com/apache/cordova-plugin-inappbrowser/commit/a0c267fe36be9a97c974f73b9d2160eca54b9828 the project does not compile.

### What is expected to happen?

TypeScript project should compile without typings errors.

### What does actually happen?

TypeScript project compilation fails due to typings errors.

## Information

```
ERROR in /xyz/plugins/cordova-plugin-inappbrowser/types/index.d.ts(27,11):
TS2430: Interface 'InAppBrowser' incorrectly extends interface 'Window'.
  Types of property 'addEventListener' are incompatible.
    Type '(type: channel, callback: InAppBrowserEventListenerOrEventListenerObject) => void' is not assignable to type '{ <K extends "load" | "abort" | "afterprint" | "beforeprint" | "beforeunload" | "blur" | "canplay" | "canplaythrough" | "change" | "click" | "compassneedscalibration" | "contextmenu" | "dblclick" | ... 120 more ... | "unhandledrejection">(type: K, listener: (this: Window, ev: WindowEventMap[K]) => any, options?: boo...'.
      Types of parameters 'type' and 'type' are incompatible.
        Type '"statusTap"' is not assignable to type 'channel'.
```

Most likely due to the change whereby event listener types were extracted to a separate list of strings at the top of the file, however that list does not allow for an arbitrary `string`. PR incoming, need a ref number.

### Command or Code

Usual `npm` tasks to build a TS project.

### Environment, Platform, Device

macOS 10.14.6
node 10.16.0
npm 6.9.0

### Version information

```
    "cordova": "9.0.0",
    "cordova-android": "8.0.0",
    "cordova-plugin-inappbrowser": "3.0.0",
    "typescript": "3.5.3",
    "webpack": "4.38.0",
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Will the `statusTap` even fire when the cordova-plugin-statusbar plugin is installed?

**Comment by kamilbrk** [comment]
I am not quite sure why does it matter in this context, but yes.

<img width="547" alt="Screenshot 2019-08-01 at 17 28 30" src="https://user-images.githubusercontent.com/591349/62310614-cf1bd780-b481-11e9-978d-14430c9896b3.png">

I have the very same behaviour with `cordova-plugin-inappbrowser` 3.0.0 and with this PR (since 3.1.0 does not compile). As seen on the screenshot above, adding the event handler and then tapping few times successfully fires that event handler.

This is with `"cordova-plugin-statusbar": "2.4.3"`

**Comment by kamilbrk** [comment]
Most of typings on DefinitelyTyped add explicit `addEventListener`s, one by one. This seems to do the trick, rather than what happened here with `"one" | "two" | "three"`, no matter if it has my `| string` or not.

I agree, adding `string` at the end makes it a bit useless, so it's either splitting them all to separate explicit definitions, like any other package, or making it a bit useless with this. Either of them would fix compilation errors.

**Comment by timbru31** [comment]
I've had a thought about this issue again. I think the most elegant and smallest solution would be:

```ts
type channel = "loadstart" | "loadstop" | "loaderror" | "exit" | "beforeload" | "message" | "customscheme";

/**
* Adds a listener for an event from the InAppBrowser.
* @param type      loadstart: event fires when the InAppBrowser starts to load a URL.
*                  loadstop: event fires when the InAppBrowser finishes loading a URL.
*                  loaderror: event fires when the InAppBrowser encounters an error when loading a URL.
*                  exit: event fires when the InAppBrowser window is closed.
* @param callback  the function that executes when the event fires. The function is
*                  passed an InAppBrowserEvent object as a parameter.
*/
addEventListener(type: channel, callback: InAppBrowserEventListenerOrEventListenerObject): void;

/**
* Adds a listener for an event from the InAppBrowser.
* @param type      any custom event that might occur.
* @param callback  the function that executes when the event fires. The function is
*                  passed an InAppBrowserEvent object as a parameter.
*/
addEventListener(type: string, callback: InAppBrowserEventListenerOrEventListenerObject): void;
```

This allows the user to choose a (pre-)defined event or pass a custom string into the function. Visual Studio Code recognizes both overloads and provides correct intellisense:

![Screenshot 2020-01-03 at 15 34 44](https://user-images.githubusercontent.com/838003/71729018-9c15af80-2e36-11ea-8f28-f32d59149dbe.png)
![Screenshot 2020-01-03 at 15 34 51](https://user-images.githubusercontent.com/838003/71729019-9c15af80-2e36-11ea-9c8a-2d380c680c5f.png)


What is your opinion on my proposal?

**Comment by kamilbrk** [comment]
I forgot about this! Perfect, I can try this out later today, but that should do the trick anyway. Thanks a lot for getting this sorted!

**Comment by timbru31** [comment]
Any luck trying it out yet? ;)

**Comment by kamilbrk** [comment]
> Any luck trying it out yet? ;)

Apologies for letting this slip for that long.

Yes, this would work. I have updated my fork, pulled it into my local Cordova project and it's now building successfully without type errors, whereas apache/master still has an issue as it stands.

`"cordova-plugin-inappbrowser": "git+https://github.com/kamilbrk/cordova-plugin-inappbrowser.git#dddf696a1af1c0d5b3bd9eb2c228b11b71638aaa"`
