### ISSUE TITLE
Inappbrowser scales my external link differently between _self and _blank

### ISSUE THREAD

**Issue by tonetechnician** [apache/cordova-plugin-inappbrowser#519]
# Bug Report

## Problem

Viewport scaling differences when opening external links in _blank and _self.

### What is expected to happen?

I expect that the viewport scaling between _self and _blank should be consistent.

### What does actually happen?

When I load an external browser link in _self, the content of the link is scaled too large (it zooms in to cut out majority of my page). When I open the link using _blank, the content of the link is scaled to the correct size for my device.

This cannot be corrected with the viewport metadata tag. If I change settings in viewport metadata, the cordova web view remains too large whilst the content is resized. This means that I am still able to pan the page around blank space before finding my page.

### Commands that I've run with 

I've tried running the .open function with various different parameters. These are shown below 

```
cordova.InAppBrowser.open(url, "_self", "location=no,status=no,menubar=no,toolbar=no,zoom=yes,useWideViewPort=yes")
cordova.InAppBrowser.open(url, "_self", "location=no,status=no,menubar=no,toolbar=no,zoom=yes,useWideViewPort=no")
```

With _blank engage, I run this command and it rescales correctly

```
cordova.InAppBrowser.open(url, "_blank", "location=no,zoom=no,fullscreen=yes,status=no,menubar=no,toolbar=no");
```

### Environment, Platform, Device
*Cordova:* v9.0.0 (cordova-lib@9.0.1)
*Android:* v8.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by tonetechnician** [comment]
EDIT ALERT: 

I've included an edit showing the commands that I've run.

**Comment by jcesarmobile** [comment]
options are only available for _blank
