### ISSUE TITLE
Property 'InAppBrowser' does not exist on type 'Cordova'

### ISSUE THREAD

**Issue by veswanthRaju** [apache/cordova-plugin-inappbrowser#520]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
