### ISSUE TITLE
Depreciated API error from Apple

### ISSUE THREAD

**Issue by benvallack** [apache/cordova-plugin-inappbrowser#532]
It looks like the plugin is causing a warning from Apple about the UIWebView API usage:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs .

Will this be removed from future versions of the plugin?

Any quick way to remove it when building the binary?

**Comment by timbru31** [comment]
Discussion is over here: https://github.com/apache/cordova-ios/issues/661

**Comment by jcesarmobile** [comment]
Reopening since the other issue is just for cordova-ios, but InAppBrowser will also need an update to remove UIWebView code

**Comment by spinninghamster** [comment]
Agreed. Looks like this plugin needs to be updated to remove all references of UIWebView in order not to be rejected from iOS.

**Comment by kinoli** [comment]
This is pretty important, the plugin is rendered insufficient without it. Can we get this expedited please?

**Comment by timbru31** [comment]
We are aware of this situation, but as of now it is **JUST** a warning, Apple will still accept apps and updates with UIWebView refernces. We do not know when they change the policy to a rejection.

The discussion about our roadmap is here, feel free to participate :) https://github.com/apache/cordova-discuss/pull/110

**Comment by ermik** [comment]
`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs `

**Comment by ath0mas** [comment]
Please @jcesarmobile @timbru31 would #584 be a solution for now?
it is not as _destructive_ as #535, and **cordova-ios** officially added the "WKWebViewOnly" preference few weeks ago with https://github.com/apache/cordova-ios/pull/715

**Comment by sebj54** [comment]
Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020. I just got this warning by email after submitting an app:

![image](https://user-images.githubusercontent.com/5880435/75981314-8c712080-5ee4-11ea-8caf-0d0355925f63.png)

**Comment by NiklasMerz** [comment]
Please use the compiler flag to fix this error. See https://github.com/apache/cordova-ios/pull/715

The next major version of the plugin probably will remove UIWebView. See #635
