### ISSUE TITLE
Inappbrowser 3.1.1 dev not adding to Phonegap Build project.

### ISSUE THREAD

**Issue by MarcusRhodes** [apache/cordova-plugin-inappbrowser#549]
I need to add inappbrowser v3.1.1 to my phonegap app in order to make postMessage work, but phonegap doesn't add the plugin to my project when I try to build it with build.phonegap.com. Additionally, I had to add it manually to my source code to get it to run on my emulator. Any tips on how to fix or work around this?

**Comment by jcesarmobile** [comment]
Ask on phonegap forums, this is not an issue on the plugin, closing,
