### ISSUE TITLE
`AppendUserAgent` not working on ipadOS

### ISSUE THREAD

**Issue by lovelyelfpop** [apache/cordova-plugin-inappbrowser#557]
It's always "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)"

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
