### ISSUE TITLE
`AppendUserAgent` not working for wkwebview on iPadOS

### ISSUE THREAD

**Issue by lovelyelfpop** [apache/cordova-plugin-inappbrowser#560]
# Bug Report
`AppendUserAgent` not working for wkwebview on iPadOS

### What is expected to happen?
`AppendUserAgent` should append custom string to navigator.userAgent.

### What does actually happen?
navigator.userAgent is still the same as the orignal one.

## Information
On iPadOS, the orignal userAgent is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)`, 
We configured `<preference name="AppendUserAgent" value=" myapp" />`, but the userAgent doesn't change.

### Command or Code
`<preference name="AppendUserAgent" value=" myapp" />`

### Environment, Platform, Device
xcode 11.1
iPad pro 9.7 inch (ios 13.1)

### Version information
cordova 9.0.0
cordova-ios 5.0.1
cordova-plugin-inappbrowser 3.1.0

## Checklist

- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above
- [x] I searched for existing GitHub issues

**Comment by lovelyelfpop** [comment]
It seems `CDVUserAgentUtil.setUserAgent` not working for wkwebview, the right way to override userAgent is `[self.webView setCustomUserAgent:newUserAgent]`

**Comment by timbru31** [comment]
PR's welcome!

**Comment by jcesarmobile** [comment]
should be fixed on master

**Comment by shrivallabhDeshmukh** [comment]
Is this issue fix?

**Comment by lovelyelfpop** [comment]
@shrivallabhDeshmukh Yes, it's fixed, I just tried it 2 days ago

**Comment by shrivallabhDeshmukh** [comment]
Thanks for the update  @lovelyelfpop  :)
