### ISSUE TITLE
[android] Inappbrowser does not support new android devices with notch

### ISSUE THREAD

**Issue by mosababubakr** [apache/cordova-plugin-inappbrowser#563]
# Bug Report

### What is expected to happen?
inappbrowser should support the new android devices that came with notch screen 
Like: // StatusBar.overlaysWebView(true) \\

### What does actually happen?
There is an Empty solid blank black bar appear in new android devices with notch.

{note}: this problem also appear in the main app.

![Untitled-1](https://user-images.githubusercontent.com/47486787/67791602-647a3800-fa80-11e9-9407-fd715b5ff590.jpg)

### Command or Code

var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes');

### Environment, Platform, Device

- Android devices like Xiaomi or any new android notch devices.

### Version information

- Inappbrowser plugin 3.1.0 or MASTER VERSION
- Phonegap CLI 9.0.0 (Cordova android 8.0.0)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jubarbie** [comment]
I still have this issue on my Android 12 device.
I use cordova 11.1 and the latest version of the InAppBrowser plugin.

This is the options I use :
`'location=no,toolbar=no,fullscreen=yes,useWideViewPort=yes'`

See the white space on the top and bottom of the screen:
![Screenshot_20230510-162632_PelureViewer](https://github.com/apache/cordova-plugin-inappbrowser/assets/17431806/159e8144-e941-4653-88a3-6d578372d0ab)

The main app is running in full screen as expected. It's only the InAppBrowser that is not fully full screen.
