### ISSUE TITLE
Status Bar rotating even if screen rotation is lock

### ISSUE THREAD

**Issue by rricamar** [apache/cordova-plugin-inappbrowser#564]
# Bug Report

## Problem
Hi everybody,

After updating to version 3.1.0 (previously using 3.0.0), after the inApp browser is shown (we use it for login purposes), the status bar starts to rotate with the device, even if it was locked  before. We know that it is due the inApp since if we try before show it everything works fine.

Thanks in advance for any solution/help 👍 

### Version information

- Operating System: Ios 13
- Xcode version: 11

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by rricamar** [comment]
Hi Again,

Any help 😢 ?

**Comment by rricamar** [comment]
Hi, Im leaving a video with the issue, as you can see, even in the screen orientation is locked through configuration the status bar is rotating. This after the in app is shown:

[2020-02-05 17.05.09.MP4.zip](https://github.com/apache/cordova-plugin-inappbrowser/files/4160560/2020-02-05.17.05.09.MP4.zip)

**Comment by jcesarmobile** [comment]
closing in favor of https://github.com/apache/cordova-plugin-inappbrowser/issues/623 since it has more comments and reactions
