### ISSUE TITLE
[android] {option: location=no} will hide the done button

### ISSUE THREAD

**Issue by mosababubakr** [apache/cordova-plugin-inappbrowser#574]
# Bug Report

## Problem
This is an old problem and now it is the time to explain it.

### What is expected to happen?
When you set location=no, the done button should be appear and only the location bar should be hidden.

### What does actually happen?
-------------------------
*According to the plugin Readme.md (DOCUMENTATION):

All platforms support:

location: Set to yes or no to turn the InAppBrowser's location bar on or off.
-----------------------
But this not true for android,

When you set location=no the done button disappeared in android.

(on ios works well, only hide url location without affect the done button).

## Information

Location option should be work as ios.

Current situation:
#### ios
- location=no // mean: url location bar is hidden.
- location=yes // mean: url location bar is visible.

#### android
- location=no // mean: the done button is hidden.
- location=yes // mean: the done button is visible.

Correct situation for #### android should be like:
- location=no // on android should hide the url location bar only without affect (done button) as ios situation.

### Command or Code

on android try:

First (set location to yes):

var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes');

Second(set location to no):

var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=no');

### Environment, Platform, Device

any android device.

### Version information

- phonegap cli / cordova cli 9.0.0
- cordova-plugin-inappbrowser latest version (master version) and all versions.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by cemerson** [comment]
This appears to still be an issue as of 12/2023. Was there a solution/workaround here or is there no way to get the close button to display but not the location bar on Android/Cordova/InAppBrowser?
