### ISSUE TITLE
onResume event triggered when page loads

### ISSUE THREAD

**Issue by unugurhamit** [apache/cordova-plugin-inappbrowser#577]
- [ ] Bug Report
- [ ] Feature Request
- [X ] Support Question

## Description
We have a Cordova application uses your plugin and we noticed that (after updating it to version 3.1.0)
onResume function in cordova index.js is triggered when any web page in the application refreshes.

We excepted that onResume should only be triggered when the application comes to foreground.

Do you have any idea about why this event is triggered on each page load ?

### Environment, Platform, Device

Android, cordova,Samsung S7 Edge 

### Version information
Cordova: 9.0.0, The plugins are (with the most uptodate versions)
cordova-background-geolocation-lt
cordova-plugin-background-fetch
cordova-plugin-battery-status
cordova-plugin-camera
cordova-plugin-cocoalumberjack
cordova-plugin-dialogs
cordova-plugin-geolocation
cordova-plugin-inappbrowser
cordova-plugin-statusbar
cordova-plugin-whitelist
cordova-plugin-wkwebview-engine
cordova-plugin-network-information
cordova-plugin-splashscreen
pushwoosh-cordova-plugin
cordova-plugin-globalization

Other Frameworks: -
Mac OS with Android Studio

## Checklist
- [X ] I searched for already existing GitHub issues about this
- [X ] I updated all Cordova tooling to their most recent version
- [ X] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by unugurhamit** [comment]
- [ ] Bug Report
- [ ] Feature Request
- [X ] Support Question

## Description
We have a Cordova application uses your plugin and we noticed that (after updating it to version 3.1.0)
onResume function in cordova index.js is triggered when any web page in the application refreshes.

We excepted that onResume should only be triggered when the application comes to foreground.

Do you have any idea about why this event is triggered on each page load ?

### Environment, Platform, Device

Android, cordova,Samsung S7 Edge 

### Version information


- [X ] I searched for already existing GitHub issues about this
- [X ] I updated all Cordova tooling to their most recent version
- [ X] I included all the necessary information above

**Comment by unugurhamit** [comment]
> Thanks a lot for your issue, however the issue template exists for a reason 😉
> It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.
> 
> Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

I edited the issue
