### ISSUE TITLE
Inappbrowser issue

### ISSUE THREAD

**Issue by santoshkumar1292** [apache/cordova-plugin-inappbrowser#579]
I am loading one application in inappbrowser in ionic 4,this application includes pages which contain download pdf from base64 data received from api.It is working in browser but in inappbrowser download is not working.

**Comment by timbru31** [comment]
Like I've said in #578 - unless you follow the issue template, there is not much we can do to help you.

**Comment by santoshkumar1292** [comment]
Can you tell me where I will get issue template

**Comment by timbru31** [comment]
When you create a new issue it asks for what type and after that the form is pre-filled with the template :)
