### ISSUE TITLE
Download is not working in a link opened in inappbrowser in ionic 4

### ISSUE THREAD

**Issue by santoshkumar1292** [apache/cordova-plugin-inappbrowser#580]
# Bug Report

## Problem
I am loading an website in inappbrowser in ionic 4,the website consist of number of pages which contains links to download pdf,It is downloading in chrome browser but not in inappbrowser.

### What is expected to happen?
It should download in inappbrowser

### What does actually happen?
It is not downloading

## Information

open any website in inappbrowser which consist of pdf download ,and try to download pdf.

### Environment, Platform, Device

android

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by Hadatko** [comment]
Hi, check this: https://getsatisfaction.com/apperyio/topics/in_app_browser_download_links

**Comment by jcesarmobile** [comment]
It’s already reported
https://github.com/apache/cordova-plugin-inappbrowser/issues/311
