### ISSUE TITLE
inappbrowser plugin not working on IOS 13+ version for ionic app

### ISSUE THREAD

**Issue by Anish-ichigo** [apache/cordova-plugin-inappbrowser#582]
I am facing same issue after upgrade inappbrowser plugin,webview plugin & viceversa.
But still there is no solution.
So, please help me to solve this issue.
"cordova-plugin-inappbrowser": "^3.1.0",

**Comment by Anish-ichigo** [comment]
For Ionic 3

**Comment by mosababubakr** [comment]
use master version 
https://github.com/apache/cordova-plugin-inappbrowser.git#master

**Comment by Amatewasu** [comment]
@mosabab Hi, thank your for your answer. You could you describe a bit more the way of doing it?
When I replace `"cordova-plugin-inappbrowser": "git+https://github.com/apache/cordova-plugin-inappbrowser.git"` by `"cordova-plugin-inappbrowser": "git+https://github.com/apache/cordova-plugin-inappbrowser.git#master"` in my package.json file (then I execute npm install obviously), I trigger the following error when I execute `npm list --depth=0`: `ERR! missing: cordova-plugin-inappbrowser@git+https://github.com/apache/cordova-plugin-inappbrowser.git#master, required by myappname@0.0.1`.

**Comment by mosabab** [comment]
> @mosabab Hi, thank your for your answer. You could you describe a bit more the way of doing it?
> When I replace `"cordova-plugin-inappbrowser": "git+https://github.com/apache/cordova-plugin-inappbrowser.git"` by `"cordova-plugin-inappbrowser": "git+https://github.com/apache/cordova-plugin-inappbrowser.git#master"` in my package.json file (then I execute npm install obviously), I trigger the following error when I execute `npm list --depth=0`: `ERR! missing: cordova-plugin-inappbrowser@git+https://github.com/apache/cordova-plugin-inappbrowser.git#master, required by myappname@0.0.1`.

Put the 
https://github.com/apache/cordova-plugin-inappbrowser.git
Without #master

**Comment by webteambel** [comment]
Hi, 

We have the same issue, and we won't use the branch master , is there any update coming to "npm" version (3.1.1 ..) ?

**Comment by mosabab** [comment]
> Hi,
> 
> We have the same issue, and we won't use the branch master , is there any update coming to "npm" version (3.1.1 ..) ?

you can use https://github.com/apache/cordova-plugin-inappbrowser.git from github

**Comment by jcesarmobile** [comment]
closing since it's fixed in master, install from github or wait for the next release
