### ISSUE TITLE
Post message in latest stable?

### ISSUE THREAD

**Issue by JohnathanWhite** [apache/cordova-plugin-inappbrowser#590]
Hey there! I am currently using 3.1.1-dev for the post message feature. When will this be available in the stable version?

**Comment by timbru31** [comment]
This should be in the 3.1.0 release. If it does not work for you, please fill in the issue template and preferably create a minimum reproducible example. (More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)

Thanks!

**Comment by JohnathanWhite** [comment]
Thank you!
