### ISSUE TITLE
Version 3.2.0 is failed to install

### ISSUE THREAD

**Issue by arnoldsi** [apache/cordova-plugin-inappbrowser#605]
The latest version in npm is 3.1.0
https://www.npmjs.com/package/cordova-plugin-inappbrowser

This causing build error:

> 2020-01-07T15:01:34.3052237Z fetch: Installing cordova-plugin-inappbrowser@3.2.0 to /home/vsts/work/r1/a/_eToro_etoro-wallet/wrapper
2020-01-07T15:01:34.3052597Z Running command: npm install cordova-plugin-inappbrowser@3.2.0 --save
2020-01-07T15:01:34.3052929Z Command finished with error code 1: npm install,cordova-plugin-inappbrowser@3.2.0,--save
2020-01-07T15:01:34.3053375Z Failed to restore plugin "cordova-plugin-inappbrowser" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-inappbrowser@3.2.0 via registry.

cordova cli: 9.0.0
android: 7.1.2

**Comment by timbru31** [comment]
3.2.0 is still in the voting process, it's not yet published to npm. Please see this and the following comments: https://github.com/apache/cordova-plugin-inappbrowser/pull/584#issuecomment-571024787

**Comment by brodybits** [comment]
FYI we are now in the process of publishing 3.2.0. As I said in <https://github.com/apache/cordova-plugin-inappbrowser/pull/584#issuecomment-572202818>:

> Release discussions and voting threads generally happen on the mailing list. It is also fine to contact us by Slack in case of any questions. Links to find the mailing list and Slack channel are in the footer of cordova.io which redirects to: cordova.apache.org
> 
> In general, we would appreciate a reasonable amount of patience since Apache Cordova is maintained by a bunch of generally overworked volunteers. But please do feel free to follow up with us in case of any unreasonable delays.

**Comment by brodybits** [comment]
And now published :tada:
