### ISSUE TITLE
http url are not opening only a blank white screen appears

### ISSUE THREAD

**Issue by LalitKushwah** [apache/cordova-plugin-inappbrowser#619]
# Bug Report
I am using InAppBrowser in ionic and facing this problem that when I open url starting with http the a white screen appears only but when I use https url then it is working fine.
### What is expected to happen?
It should open the url starting from http.

### What does actually happen?
A white screen appears when any http url is used

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Is this on Android? You should check that you allow "clear text". https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

**Comment by jcesarmobile** [comment]
Yeah, not a bug in the plugin, closing.
