### ISSUE TITLE
camera and mic

### ISSUE THREAD

**Issue by xale76** [apache/cordova-plugin-inappbrowser#620]
Hello my cordova app uses cordova-plugin-inappbrowser to show remote pages. One of these is a page with WebRTC javascript plugin that requests access for mic and camera (video call).
If I open this page from normal browser, even on the phone, everything works well: the first time I'm asked to allow browser to use cam and mic. 
If I call it within my app (by opening it with inappbrowser) the page stucks because I think I'm not prompted if I want to allow browser to use cam and mic.
How's happening?
Thank you

**Comment by MatthewPringle** [comment]
I am having this issue as well.

It seems from other posts that the Camera doesn't not work with Android without having to edit the code of the plugin.

**Comment by jcesarmobile** [comment]
The template is there for a reason, your issue lacks of essential information.
