### ISSUE TITLE
InAppBrowser' does not exist on type 'Cordova

### ISSUE THREAD

**Issue by victororlyk** [apache/cordova-plugin-inappbrowser#621]
# Bug Report
InAppBrowser' does not exist on type 'Cordova
## Problem
The problem says that I 
### What is expected to happen?
We should be  able to use 
```
cordova.InAppBrowser.open(url, '_system');
```

### What does actually happen?
it throws an error in console and does not compile

## Information

version of the plugin is
"cordova-plugin-inappbrowser": "^3.2.0",

### Command or Code

cordova.InAppBrowser.open(url, '_system');

### Environment, Platform, Device

macOs Catalina.
npm -6.10.0

### Version information

I am using capacitor as my core
@capacitor/android": "^1.4.0",
    "@capacitor/core": "1.3.0",
    "@capacitor/ios": "^1.4.0",
"@ionic/react": "^4.11.8",
"cordova-plugin-safariviewcontroller": "^1.6.0",
Other cordova plugins works good with capacitor

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Not a problem on the plugin
