### ISSUE TITLE
InAppBrowser exc_bad_instruction error

### ISSUE THREAD

**Issue by ugurcagridogan** [apache/cordova-plugin-inappbrowser#622]
# Bug Report
exc_bad_instruction error occures on IOS.
## Problem
The given code below works on android but not on ios.
### What is expected to happen?
We should be able to use the code like this:
```
openLoginBrowser() {
    const browser = this.inapp.create('...URL_HERE...', '_blank', {
      zoom: 'no',
      hideurlbar: 'yes'
    });
    browser.on('loadstart').subscribe(response => {
      ...
    });
  }
```
we should be able to open an inappbrowser with/without options.

### What does actually happen?
When the app runs this error popups and app crashes:
> exc_bad_instruction (code=exc_i386_invop subcode=0x0)

### Environment, Platform, Device

macOS Majove (Xcode 11), tested on IOS 12+ devices

### Version information

"@ionic/angular": "^4.7.1",  
"@ionic-native/in-app-browser": "^5.20.0",  
"cordova-plugin-inappbrowser": "^3.2.0",  
"@capacitor/cli": "^1.2.1",  
"@capacitor/android": "^1.2.0",
"@capacitor/core": "^1.2.1",
"@capacitor/ios": "^1.3.0",

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all capacitor tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
It seems you run Capacitor. Can you please try this in a plain new Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by ugurcagridogan** [comment]
i think my previous search terms were not enough. i just noticed this topic (your fix) on capacitor [github page](github.com/ionic-team/capacitor/issues/2315). the error occures at the same point with same code. i will try to update capacitor related packages as soon as i can and share the results.

**Comment by ugurcagridogan** [comment]
updated all capacitor packages to v1.5.0. the problem has been partially solved. now the inappbrowser can be opened but "sometimes" view doesn't refresh. the events are triggered, but the only thing i can see is the loading icon and "done" button.

**Comment by jcesarmobile** [comment]
Not a problem on the plugin
