### ISSUE TITLE
Windows: inappbrowser.css link added multiple times

### ISSUE THREAD

**Issue by regnete** [apache/cordova-plugin-inappbrowser#624]
# Bug Report

### What is expected to happen?
The reference to inappbrowser.css should be added once to the document, regardless how often the inappbrowser is openend and closed.

### What does actually happen?
Everytime the inappbrowser is opened an additional reference to inappbrowser.css is added to the document.

## Information

This line is causing the ussie:
https://github.com/apache/cordova-plugin-inappbrowser/blob/09ad59f7ef177007c5ed603147cff335d7cfaafa/src/windows/InAppBrowserProxy.js#L150

It should be called once on the first time opening the inappbrowser and then never again until the app is restarted.

### Environment, Platform, Device

Windows

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
