### ISSUE TITLE
beforeload not firing when opening .pdf files

### ISSUE THREAD

**Issue by Webrow** [apache/cordova-plugin-inappbrowser#628]
# Bug Report

## Problem
beforeload events do not fire unless a webpage is loaded. Its not working for example with .pdf files

### What is expected to happen?
beforeload to fire before downloading a .pdf

### What does actually happen?
beforeload does not fire 

### Command or Code

```
// Add beforeload event handler which is called before each new URL is loaded into the InAppBrowser Webview
      browser.addEventListener("beforeload", function(params, callback) {
console.log("Firing before load")
        // If the URL being loaded is a PDF
        if (params.url.match(".pdf")) {
console.log("I am matching pdf ")
          // Open PDFs in system browser (instead of InAppBrowser)
          cordova.InAppBrowser.open(params.url, "_system");
console.log("shouldve opened a proper browser now")
        } else {
          // Invoke callback to load this URL in InAppBrowser
          callback(params.url);
        }
      });
```

### Environment, Platform, Device

Iphone 11 pro max, 13.3 simulator 

### Version information

cordova cli 9.0 
ionic v1 
cordova iap 3.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by wvengen** [comment]
Just to check: did you use the `beforeload` option when opening the inAppBrowser?

**Comment by Webrow** [comment]
Yes! I did not at first. I will close this issue nevertheless. Im picking this up in 3 weeks during the sprint. Ill workout an example and see if I am doing everything correct to not waste people their time!
