### ISSUE TITLE
window.performance.mark is not available in iphone

### ISSUE THREAD

**Issue by masscustsoft** [apache/cordova-plugin-inappbrowser#630]
I open a help page from confluence, it works fine with android but failed on iphone.

I inspected that the js refer to window.perfornance object with is unavailable in our plugin.

May I know if/where I can make a workaround for it like define: window.performance={mark:function(){}} ?

thank you,
Jason Song

**Comment by jcesarmobile** [comment]
seems to be there on WKWebView, since we just removed UIWebView this can be closed
