### ISSUE TITLE
InAppBrowser in not opening the URL in windows 

### ISSUE THREAD

**Issue by cah-ram-thaker** [apache/cordova-plugin-inappbrowser#631]
# Bug Report
in Windows OS , InAppBrowser

## Problem
InAppBrowser in not opening the URL(https://login.cardinalhealth.net/) in windows 

### What is expected to happen?
The page should need to load.

### What does actually happen?
The white screen is only displayed in In-app browser 

## Information

We are using cordova and AnagularJs for windows (8.1+)and IOS(Ipad) app development. 

### Command or Code

var inAppBrowser = cordova.InAppBrowser.open
        ("https://login.cardinalhealth.net/",
            '_blank', 'location=yes');

### Environment, Platform, Device
Windows 8.1 , Windows 10 

### Version information
Cordova: Cordova CL (5.4.1)
Other Frameworks: AngularJS
Operating System: Visual Studio, Xcode etc.
User inappbrwser : 3.2.0 version 

## Checklist

- [x] I searched for existing GitHub issues 
- [x] I updated all Cordova tooling to most recent version 
- [x] I included all the necessary information above

**Comment by Jahrenski** [comment]
Same happens with Ionic 5 / Angular 9 - Cordova 9.0.0 on windows 7.0.1
InAppBrowser 3.2.0

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
