### ISSUE TITLE
iOS zoom

### ISSUE THREAD

**Issue by oscarsales** [apache/cordova-plugin-inappbrowser#636]
# Feature Request

## Motivation Behind Feature
A client is asking me to be able to zoom in and out the web content. This is possible in android, but unfortunately not in iOS.

## Feature Description
If zoom is possible in a native iOS project, it should be also possible with this plugin. It's inconsistent that you can do something in one platform, and not in the other, using the same plugin.

## Observations
Enable Viewport Scale does nothing.

UPDATE: zoom **worked** only after using enableviewportscale=yes **with** usewkwebview=yes

But now the appbrowser closes immediately after opening. To solve this error, upgrade to version 3.2.0 (I had 3.1.0):
cordova plugin rm cordova-plugin-inappbrowser --save
cordova plugin add cordova-plugin-inappbrowser --save

**Comment by jcesarmobile** [comment]
So, is everything ok after you updated to 3.2.0? looks like it is, but not sure why you didn't close the issue then.

**Comment by oscarsales** [comment]
Yes, sorry, as I just created the issue the same day, I left it open just in case someone had something to say or ask about it. I will close it right now.

Conclusion: solution to be able to zoom in and out in iOS:
- enableviewportscale=yes + usewkwebview=yes
- plugin version >= 3.2.0.

**Comment by molinet88** [comment]
What about disable zooming? I'm unable to disable it in iOS.
I've tried:
```
usewkwebview="yes"
enableViewportScale="no"
```
Tested on iPhone 7 Plus using plugin version 4.0.0.
In Android is working fine.
