### ISSUE TITLE
InAppBrowser: var ref = cordova.InAppBrowser.open(url, target, options); getting error :'cordova' is not defined  no-undef

### ISSUE THREAD

**Issue by mayursarode4** [apache/cordova-plugin-inappbrowser#640]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
Using var ref = cordova.InAppBrowser.open(url, target, options); getting error :'cordova' is not defined  no-undef in ./src/App.js

How to solve this issue, I'm using this plugin for react-cordova app development and need to call specific secure url in webView using InAppBrowser
### Environment, Platform, Device

Android 7.+, iOS 10.+ or 13.+
    

### Version information

"Cordova": "9.0.0 (cordova-lib@9.0.1)",
"cordova-android": "^8.1.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-wkwebview-engine": "^1.2.1",

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
if cordova is not defined, you probably forgot to add the cordova.js script tag
