### ISSUE TITLE
Statusbar with Capacitor not working

### ISSUE THREAD

**Issue by benvallack** [apache/cordova-plugin-inappbrowser#641]
# Bug Report
Status bar doesn't seem to work when using the Capacitor version of ionic. 

## Problem
Status bar loads fine and looks good with the normal ionic pages, but as soon as the inappbrowser view loads, it sort of covers up the native status bar with a white bar, oddly it seems to sometimes go all the way across but other times stil show the time and date over grey. If I scroll I can actually see the page content go up behind the statusbar. It's just a question of getting a consistent background colour and ideally starting off by showing the webpage behind the statusbar instead of needing to be scrolled before it floats behind. 

### What is expected to happen?
Consistent statusbar display, either ideally floating over the in app browser view or just above it. 

### What does actually happen?
Broken status bar with white background (so white text in dark mode doesn't show up). 

## Information

Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v12.14.1 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
see https://github.com/apache/cordova-plugin-inappbrowser/issues/604
