### ISSUE TITLE
iOS / XCode: CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist

### ISSUE THREAD

**Issue by nnimis** [apache/cordova-plugin-inappbrowser#644]
# Bug Report
The plugin doesn't work with iOS on the latest version

## Problem
When building on Xcode everything is fine, but in runtime when trying to use an instance of the inappbrowser it fails with the error '**CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.**'
Needed to rollback to the version 3.1.0, but I would like to use this new version with the WKWebViewOnly flag because of Apple's notice:

> 'ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.'

### What is expected to happen?
It should open the browser as expected, with the parameters given.

### What does actually happen?
It fails during runtime with the error described above.

## Information
Already tried to fix it on the XCode side with no luck (I'm not a native Apple developer though, not even close...). Links like this one: https://stackoverflow.com/questions/17384523/cordova-ios-plugins-not-found/20576744#20576744 didn't helped unfortunatelly.
What drives me nuts is that the error is being thrown in runtime, the build passes just fine.
It only happens when using `<preference name="WKWebViewOnly" value="true" />`

### Environment, Platform, Device
macOS Catalina 10.15.3 (19D76)
Xcode 11.3.1 (11C504)

### Version information
npm@6.13.4
node@13.3.0
cordova-ios@5.1.1
cordova@9.0.0

## Checklist
- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Do you have the WKWebView plugin installed?

**Comment by nnimis** [comment]
@NiklasMerz that's true, thank you so much! Is there any place in the doc. saying that you must have that plugin installed for using the WKWebViewOnly flag? Is my first cordova App, sorry if this is a stupid question. Just trying to avoid any other noob to fail the same way I did :)

**Comment by NiklasMerz** [comment]
This is kind of an interim solution. I hope we can post the instructions I suggested here soon:
https://github.com/apache/cordova-docs/pull/1066

The next version of cordova-ios won't need that.

I hope this helps.

**Comment by NiklasMerz** [comment]
The blog post is published https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html
