### ISSUE TITLE
Still getting UIWebView even after updating to cordova-ios 5.1.1 and plugin to 3.2.0

### ISSUE THREAD

**Issue by akashdeepsharma1991** [apache/cordova-plugin-inappbrowser#651]
# Bug Report
Still able to see many instance of UIWebview in the plugin
## Problem
Getting the decprecate error while uploading the build on app store
### What is expected to happen?

![Screenshot 2020-03-24 at 1 09 12 PM](https://user-images.githubusercontent.com/33919907/77400442-2c79e580-6dd1-11ea-819a-f9296a601a0a.png)

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
PR #584 added **only** a variable (which you need to set) to hide the UIWebView at compilation, the current npm release still contains these classes in the source code.
The git master has and the next major release will completely remove UIWebView from the code base. If you've set `WKWebViewOnly`, then another plugin caused the deprecation warning and you need to search Xcode for further references.

**Comment by akashdeepsharma1991** [comment]
hii can you tell what variable need to set kind a new here.

**Comment by akashdeepsharma1991** [comment]
again removed the platform added the ios folder but still getting the same thing check the screenshot for the same.

![Screenshot 2020-03-24 at 2 45 15 PM](https://user-images.githubusercontent.com/33919907/77408802-44a43180-6dde-11ea-8738-4202c4072e9b.png)

**Comment by timbru31** [comment]
Please read my comment again. The source code still has the UIWebView classes. And my comment contains the required variable, too. Also please read https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

**Comment by akashdeepsharma1991** [comment]
i have followed all the step shown given in the ablove link. in my previous screenshot you can see 
CDVUIInAppBrowser.m file with UIWebView. Why is that still coming please help

**Comment by erisu** [comment]
The flag does not delete `UIWebView` from code. 

As @timbru31 said:
> PR #584 added only a variable (which you need to set) to hide the UIWebView at compilation

It only *hides* the `UIWebView` from the compiled app.

When you submit the app, with this flag defined, you will not get the warning from any of Cordova's official plugins or platform. 

If you are still getting the warning, you have a third-party plugin with the code that is not wrapped with the flag. You will need to talk with the third-party plugin developers to fix this.

As for the complete removal of `UIWebView` from code, it will not be done until the next major release.

There is no ETA on the next major release.

**Comment by akashdeepsharma1991** [comment]
oki so i will able to see the code in xcode while complie it would get hide.. ?

**Comment by erisu** [comment]
Yes, you will still see it in Xcode. It will be removed from the compile app.
