### ISSUE TITLE
window.handleOpenURL is triggered in WKWebView for system browser calls

### ISSUE THREAD

**Issue by j--w** [apache/cordova-plugin-inappbrowser#652]
# Bug Report
When triggering a url to open in the `_system` browser through IAB with WKWebView window.handleOpenURL is called. If using UIWebView this does not happen. This appears to be a regression as this [issue](https://issues.apache.org/jira/browse/CB-14234)  was fixed with [this PR](https://github.com/apache/cordova-plugin-inappbrowser/pull/278) but it appears the check never made it into [CDVWKInAppBrowser.m](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/ios/CDVWKInAppBrowser.m#L360)

## Problem
I believe there should be a check around the postNotification eg: `if ([[UIApplication sharedApplication] openURL:url] == NO)`

### What is expected to happen?

window.handleOpenURL is not called

### What does actually happen?

window.handleOpenURL is not called

### Command or Code
I created a repo to reproduce
https://github.com/j--w/iab-handleopenurl-bug/blob/master/www/js/index.js#L30

### Version information
Cordova CLI: 7.1.0
Cordova IOS: 5.1.1
XCode 11.2.1
Cordova InAppBrowser 3.2.0
OSX

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by timbru31** [comment]
PRs very welcome and thanks for following the issue template and providing a repro!

**Comment by j--w** [comment]
I'll work on a PR for this now

**Comment by rolinger** [comment]
@j--w @timbru31 - looks like this bug is back.  I am on inappbrowser ~4.0.0 and cordova-plugin-ionic-webview ~5.0.0 and this bug just happened to me.
