### ISSUE TITLE
iOS WKWebView | Not able to open the Pop up window screen

### ISSUE THREAD

**Issue by shrivallabhDeshmukh** [apache/cordova-plugin-inappbrowser#661]
# Bug Report
When trying to open below link from inAppBrowser nothing is happening.
https://www.linkedin.com/uas/connect/user-signin?trk=applyWithLinkedin
## Problem
Provided link is getting open in popup window hence not able to load this link in inappbrowser.
### What is expected to happen?
Link should get open in inAppBrowser.

### What does actually happen?
Currently nothing is happening.

## Information

Try opening any popup window link through in App browser
https://www.linkedin.com/uas/connect/user-signin?trk=applyWithLinkedin

### Environment, Platform, Device

Facing issue in iOS 
### Version information

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can you try to explain the problem a bit better or provide a sample app?

**Comment by shrivallabhDeshmukh** [comment]
I just got fix for this issue.
The Problem was if you try to open popup window inside WkWebView inAppBrowser, it was not working.
I have added below method in CDVWKInAppBrowserUIDelegate class.

`- (WKWebView *)webView:(WKWebView *)webView createWebViewWithConfiguration:(WKWebViewConfiguration *)configuration forNavigationAction:(WKNavigationAction *)navigationAction windowFeatures:(WKWindowFeatures *)windowFeatures
{
  if (!navigationAction.targetFrame.isMainFrame) {
    [webView loadRequest:navigationAction.request];
  }

  return nil;
}`
This will be come the similar behavior like UIWebView which always open new window in the current frame.

**Comment by franjoespejo** [comment]
Please do, I think I am facing the same issue. Thanks

**Comment by shrivallabhDeshmukh** [comment]
hi @franjoespejo  Please review my PR
https://github.com/apache/cordova-plugin-inappbrowser/pull/681

**Comment by yuzhakovvv** [comment]
@franjoespejo @shrivallabhDeshmukh any updates here? :)

**Comment by shrivallabhDeshmukh** [comment]
I have already raised the PR https://github.com/apache/cordova-plugin-inappbrowser/pull/681 

@franjoespejo  can you review?

**Comment by shefromhobbiton** [comment]
But how does this load the Home Screen after logging in?  My screen is blank after successful log in. Thanks!

**Comment by shrivallabhDeshmukh** [comment]
May be redirection issue @shefromhobbiton

**Comment by shefromhobbiton** [comment]
@shrivallabhDeshmukh my apologies. Can you please direct me to where I can the redirection solution?  Thank you so much.  The thing is, I am loading a URL with google/fb login.  My solution was to add a customer user agent.  It did work, but it did not redirect to where it is supposed to go. Thanks!

**Comment by dylanfpaul** [comment]
> Hi @jcesarmobile thanks for your reply. I just got fix for this issue. The Problem was if you try to open popup window links such as Facebook login , google login etc. inside WkWebView inAppBrowser, it was not working. I have added below method in CDVWKInAppBrowserUIDelegate class.
> 
> ```
>  - (WKWebView *)webView:(WKWebView *)webView createWebViewWithConfiguration:(WKWebViewConfiguration *)configuration forNavigationAction:(WKNavigationAction *)navigationAction windowFeatures:(WKWindowFeatures *)windowFeatures
> {
>   if (!navigationAction.targetFrame.isMainFrame) {
>     [webView loadRequest:navigationAction.request];
>   }
> 
>   return nil;
> } 
> ```
> 
> This will be come the similar behavior like UIWebView which always open new window in the current frame. I could raise PR for this issue if you need . Please let me know.

If I were to patch this in from a cordova hook, which hook would it be? after_platform_add?
