### ISSUE TITLE
Property 'InAppBrowser' does not exist on type 'CordovaPlugins'

### ISSUE THREAD

**Issue by shivangimittal41** [apache/cordova-plugin-inappbrowser#671]
# Bug Report

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Please fill the form out.

**Comment by timbru31** [comment]
And then we are happy to re-open it :)

**Comment by guitorioadar** [comment]
For temporary use you can use

`// @ts-ignore`
