### ISSUE TITLE
How to show website title instead of url in ionic inappbrowser?

### ISSUE THREAD

**Issue by KyawNaingThuUcsy** [apache/cordova-plugin-inappbrowser#676]

**Comment by KyawNaingThuUcsy** [comment]
$window.open(encodeURI(ENV.liveSite), '_blank', 'location=yes,clearcache=yes,clearsessioncache=yes,hideurlbar=yes,toolbarcolor=#e85147');

Is there an option to enable my issue?

**Comment by jcesarmobile** [comment]
no, it's not possible
