### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs

### ISSUE THREAD

**Issue by danishashfaq** [apache/cordova-plugin-inappbrowser#677]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
After updating InAppBrowser plugin with commit [remove UIWebView](https://github.com/apache/cordova-plugin-inappbrowser/commit/6c55e6172c80386cb0150e7cbc48317ed8c32e5b) I am still getting Deprecated API Usage warning of UIWebView from Apple. Can anyone please guide me what I have to do? Is that commit is for avoiding this warning?
## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
You need to use `cordova-ios@5.1.1` with a wkwebview plugin, along with the [WKWebViewOnly](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) preference.

If you're still getting the deprecation warning after this, then chances are you have another plugin installed still references `UIWebView`, a common group of plugins that I see when people run into this are social media plugins.

If you require any further support on this issue, I invite you to use our [slack](http://slack.cordova.io/) channel.

If you think you've found a bug, then please open a new ticket with all the requested information filled out.

Thanks.

**Comment by danishashfaq** [comment]
Thanks @breautek for your response. 
I would like to know is it neccessary to move to cordova-ios@5.1.1 (I am curious if I update it, then I have to update other plugins of project as well, that takes lot of time to resolve all dependencies). And if I have to update cordova-ios@5.1.1 so can you guide me what updates required in my package.json.
[package.json.txt](https://github.com/apache/cordova-plugin-inappbrowser/files/4520742/package.json.txt)

Initially I suppose that UIWebView used only in InAppBrowser, so I update only InAppBrowser plugin (as it have an update in which UIWebView removed). But After running **grep -r "UIWebView" .** command on project I found so many references in different plugins including socialsharing, firebase etc (too many search results, I don't exactly know if it's better approach to find references of UIWebView plugin?)

**Comment by NiklasMerz** [comment]
You need to update all plugins to versions that fixed the UIWebView issue. Then I would suggest removing the ios platform and add it in the latest version with the CLI.

Again please go to the Cordova Slack for those questions. Other people recently asked for support and the answers might help you, too.
