### ISSUE TITLE
Apple rejected my binary after inAppBrowser plugin

### ISSUE THREAD

**Issue by yigitbacakoglu** [apache/cordova-plugin-inappbrowser#680]
After I added this plugin, apple rejects my binary upload.

ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Is there any setting to figure this out?

`

{
  "name": "xxxx",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/android": "^2.0.0-beta.1",
    "@capacitor/core": "^2.0.0-beta.1",
    "@capacitor/ios": "^2.0.0-beta.1",
    "@ionic-native/barcode-scanner": "^5.21.6",
    "@ionic-native/base64-to-gallery": "^5.23.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/facebook": "^5.22.0",
    "@ionic-native/file": "^5.23.0",
    "@ionic-native/file-transfer": "^5.23.0",
    "@ionic-native/http": "^5.23.0",
    "@ionic-native/in-app-browser": "^5.24.0",
    "@ionic-native/onesignal": "^5.24.0",
    "@ionic-native/qr-scanner": "^5.21.6",
    "@ionic-native/splash-screen": "^4.20.0",
    "@ionic-native/status-bar": "^5.21.5",
    "@ionic/angular": "^4.7.1",
    "@ionic/pwa-elements": "^1.4.2",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "cordova-base64-to-gallery": "^4.1.3",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-advanced-http": "^2.4.1",
    "cordova-plugin-facebook4": "^6.3.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "core-js": "^2.5.4",
    "ngx-image-cropper": "^3.1.1",
    "onesignal-cordova-plugin": "^2.9.0",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "uninstall": "0.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@capacitor/cli": "^2.0.0-beta.1",
    "@ionic/angular-toolkit": "^2.1.1",
    "@ionic/lab": "3.1.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "phonegap-plugin-barcodescanner": {},
      "cordova-plugin-facebook4": {
        "APP_ID": "xxxx",
        "APP_NAME": "xxxx"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-base64-to-gallery": {},
      "cordova-plugin-advanced-http": {},
      "onesignal-cordova-plugin": {}
    },
    "platforms": [
      "browser"
    ]
  }
}
`

Thanks

**Comment by breautek** [comment]
Use `cordova-ios@5.1.1` and the latest version of `cordova-plugin-inappbrowser@3.2.0` along with the [WKWebViewOnly](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) flag.

You'll need a [wkwebview plugin](https://github.com/apache/cordova-plugin-wkwebview-engine), but I see that you're already using `cordova-plugin-ionic-webview`, as long as that's up to date I think that's fine, but not 100% sure. You may need to ask ionic if they reference the `UIWebView` in their webview. 

If you still see the deprecation warning using the versions I mentioned, then you have other plugins referencing `UIWebView`. Social media plugins are some common ones that gets people.

I'm not sure how to get your frameworks to use the versions listed above. You may need to contact the appropriate capacitor support channels to learn more about that. Alternatively, people in our #cordova-ios [slack](http://slack.cordova.io/) channel may be able to help as well.
