### ISSUE TITLE
inappbrowser@3.2.0 gets broken on iOS by cordova-plugin-ionic-webview@4.2.0

### ISSUE THREAD

**Issue by jachstet-sea** [apache/cordova-plugin-inappbrowser#684]
# Bug Report

## Problem

When using inappbrowser@3.2.0 and cordova-plugin-ionic-webview@4.2.0 on iOS, the inAppBrowser opens but does not load the URL specified. In stays on `about:blank`.
Downgrading cordova-plugin-ionic-webview to 4.1.3 fixes the problem.
Might be related to https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/539

### What is expected to happen?
The specified URL opens properly.

### What does actually happen?
InAppBrowser stays on `about:blank`

## Information
see above

### Command or Code
`window.cordova.InAppBrowser.open(SOMEURL, '_blank', 'hidden=no,location=no,clearsessioncache=yes,clearcache=yes,toolbar=no,footer=yes,hardwareback=no');`

### Environment, Platform, Device
Cordova CLI 9.0.0
cordova-ios 5.1.1 with `WKWebViewOnly = true` in config.xml
XCode 11.4.1

### Version information
See above

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
The problem is the webview plugin, is already reported there
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/551

Also, it's not a problem if you use master branch of InAppBrowser plugin, so there is nothing to change here.

**Comment by jachstet-sea** [comment]
Okay, didn't see that one. Thanks for pointing me there!
