### ISSUE TITLE
InAppBrowser is in desktop mode on iPadOS 13

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-plugin-inappbrowser#687]
# Bug Report

## Problem
We are using a framework that detects the device and selects a theme for the OS. It looks like since iPadOS came out iPads are detected as desktop browsers on our webpage.

### What is expected to happen?
iPad should identify themselves as iOS devices. The useragent should say something like iPad, iOS like before.

### What does actually happen?
iPads get a macOS like useragent for the InAppBrowser window and an iPad user agent for the main Cordova Webview.

###### Cordova Webview
`Mozilla/5.0 (iPad; CPU OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

###### IAB
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

## Information

I found a WWDC talk about changes to the webview Apple is introducing to the iPad: https://developer.apple.com/videos/play/wwdc2019/203/?time=379

**I think we should allow setting the `preferredContentMode` for the IAB webview (and maybe even cordova-ios)**

I think there are some options:

* Set it to mobile to have the same behavior as previos iOS versions
* Add an option to the IAB options
* Add a config.xml preference and use it in IAB and possibly cordova-ios

If we add something like this what would be the default? "recommened" - the iOS default chooses the mode that it thinks are optimal. Setting the default to "mobile" would avoid breaking changes.

### Environment, Platform, Device

iOS/iPadOS

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Not really sure why the webview is returning `Mozilla/5.0 (iPad; CPU OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148` on cordova webview, but on cordova-ios 6.x it returns the other one.
So would make sense to do this as a config.xml preference that affects both cordova webview and InAppBrowser. Or separate preferences for each.
If not, a browser option should be used for IAB.

**Comment by NiklasMerz** [comment]
I think it might have something to do with `applicationNameForUserAgent`. If cordova-ios 6.x changes this, we should consider an option.

I think I would prefer a config.xml preference for both.

**Comment by NiklasMerz** [comment]
Preference is done for InAppBrowser. **cordova-ios and documentation is TODO**

**Comment by loganaaaflag** [comment]
I think we're running into this issue with an app we're developing. Is there any workaround as of now, or should I just track PR #688 ? 

Thanks!

**Comment by NiklasMerz** [comment]
Yeah the PRs should be good. We just need to fix our tests and create a release. You can use a fork with this change until the release is ready.

**Comment by taras101** [comment]
I have been having an issue with a pre-existing Ionic3 app that I am trying to send in an update to apple and is being rejected as stuck on splash on Ipad ios 13+. All other devices build and work well. I get no errors in safari or xcode. It seems to get stuck at IAB. I have added the fork and <preference name="PreferredContentMode" value="mobile" />. It is still hanging. Am I missing something?
