### ISSUE TITLE
inappbrowser set and get cookie

### ISSUE THREAD

**Issue by Bhagirath123** [apache/cordova-plugin-inappbrowser#689]
can it is possible for the set and get cookie in inappbrowser
i am use ionic v3 and inappbrowser plugin version is 3.2.0

**Comment by mc-perry** [comment]
Yes, it is possible by injecting code into your iab using document:

```
const cookie = 'document.cookie = "cookiekey=cookievalue;"';
this.browser.executeScript({ cookie });
```

**Comment by timbru31** [comment]
Closing as this issue is missing the required template and has a solution posted.
