### ISSUE TITLE
Unable to fetch redirect url on loaderror event after migrating from UIWebView to WKWebview.

### ISSUE THREAD

**Issue by sreekar89** [apache/cordova-plugin-inappbrowser#690]
# Bug Report
Unable to fetch redirect url on loaderror event after migrating from UIWebView to WKWebview.
no console log errors 

## Problem
Trying to login with social (yahoo & outlook) using inappbrowser to fetch token. after login & allowing permissions screen is not going anywhere. after some research found out that on loaderror event url is not redirect which was given & working earlier.

### What is expected to happen?
able proceed login using inappbrowser.

### What does actually happen?
can't move further after allow access permissions screen.

### Command or Code

function yahooLogin() {
		// perform some asynchronous operation, resolve or reject the promise when appropriate.
		return $q(function(resolve, reject) {
	   
		document.addEventListener('deviceready', function() {

		let codeUrl = "https://api.login.yahoo.com/oauth2/request_auth?client_id=XXXXXX&redirect_uri=https%3A%2F%2Flocalhost%3A8100&response_type=code&language=en-us";
		
		$scope.yahooRedirectUrl = 'https://localhost:8100/';
		var yahoobrowserRef = cordova.InAppBrowser.open(codeUrl, "_blank", "location=yes,clearsessioncache=yes,clearcache=yes");
	
		yahoobrowserRef.addEventListener("loaderror", (event) => {
		  if ((event.url).indexOf($scope.yahooRedirectUrl) === 0) {
			yahoobrowserRef.removeEventListener("exit", (event) => { });
			yahoobrowserRef.close();
			let code = getParameterByName('code', event.url);
			if (code) {
			  resolve(code);
			} else {
			  reject("Problem authenticating with Yahoo");
			}
		  }
		  else{
			  console.log("error");
		  }
		});
		yahoobrowserRef.addEventListener("exit", function (event) {
		  reject("The Yahoo sign in flow was canceled");
		});
	  });
	});

	  }

### Environment, Platform, Device

Ionic v1 , ios

### Version information

 "cordova-ios": "^5.1.0",
"cordova-plugin-ionic-webview": "4.2.0",
"cordova-plugin-inappbrowser": "^3.2.0",

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by sreekar89** [comment]
flaw on myside. listening to the wrong events.
works fine. updated version.
closing the issue.

**Comment by andy-fitch** [comment]
Hey Sreekar89, I'm having the exact same problem you describe capturing an oauth callback url from Salesforce into a hybrid app. Can you tell me how you fixed this - what event did you wire up?

**Comment by sreekar89** [comment]
> Hey Sreekar89, I'm having the exact same problem you describe capturing an oauth callback url from Salesforce into a hybrid app. Can you tell me how you fixed this - what event did you wire up?
> I'm guessing you moved it to loadstart then filtered on your callback url.

Yes exactly, glad you figured it out.
