### ISSUE TITLE
Unable to get a basic Cordova app approved by Apple - ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by thekamaclub** [apache/cordova-plugin-inappbrowser#696]
### Issue Type
Apple rejects a sample Cordova app due to "ITMS-90809: Deprecated API Usage" regarding UIWebView

- [x] Support Question

## Description
I created a Cordova app, included iOS platform, installed "cordova-plugin-wkwebview-engine", included one "window.open" line attempting to open a web page. Once distributing to App Store using XCode, I received a message from Apple stating that the app cannot include UIWebView plugin.

## Information
I made sure that no other plugin is installed.
I believe that Cordova internally uses UIWebView, resulting in Apple rejecting the most basic Cordova app.

### Command or Code
Terminal:
Cordova create xxx
Cordova platform add ios
Cordova plugin add cordova-plugin-wkwebview-engine

Config.xml:
```
<feature name="CDVWKWebViewEngine">
  <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />

```
index.html:
`<p>Please read our <a style="text-decoration: underline"  onclick="openTermsOfUse()"><b>Terms of Use</b></a></p>`

index.js:
```
function openTermsOfUse() {
var popupWindow;
popupWindow = window.open('https://xxx.com/terms', '_blank', 'toolbar=0,location=0,directories=0,status=1,menubar=0,titlebar=0,scrollbars=1,resizable=1');
try {
popupWindow.focus();
alert('Please unable Popups');
} catch (e) {
alert('Please unable Popups');
}
}
```

### Environment, Platform, Device
macOS Catalina (10.15.4), IntelliJ IDEA, XCode 11.4.1, newest Cordova.

**Comment by timbru31** [comment]
Please follow https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html - if the issue persists, you can try to completely remove the ios platform and re-add it. When the issue still persists, another non Apache Cordova plugin causes the warning and you need to identify and contact their author(s).

**Comment by thekamaclub** [comment]
Thank you timbru31.
I tried again what you just explained - 
I created a clean Cordova app, added iOS, added wkwebviewonly, included a short code that opens a link, submitted to Apple - and got rejected over ITMS-90809: Deprecated API Usage.

Any other idea?

**Comment by thekamaclub** [comment]
Thank you timbru31, now the app isn't rejected.

I need to open a link on my index.js file, do you know how to use wkwebview to do so?
I tried
`cordova.wkwebview.open`
but it didn't work.
Any suggestions?
