### ISSUE TITLE
how can I send custom message from my in app-browser to my ionic app

### ISSUE THREAD

**Issue by eshiett1995** [apache/cordova-plugin-inappbrowser#697]
I am trying to send a custom payload from my js inside my inAppBrowser to my ionic app. I already know how to send data to the inAppbrowser using: 

    iab.executeScript({code:`alert(2)`});

but sending data back is not properly documented, on the github site I saw:

    inAppBrowserRef.addEventListener('message', messageCallBack);
the above only shows how to make your ionic receive it, but does not show how the javascript is sending it. Please I need help on how to make the inAppbrowser send this custom message.

**Comment by timbru31** [comment]
Use `webkit.messageHandlers.cordova_iab.postMessage(stringifiedMessageObj);` - this will show up in your `messageCallBack`

**Comment by eshiett1995** [comment]
> Use `webkit.messageHandlers.cordova_iab.postMessage(stringifiedMessageObj);` - this will show up in your `messageCallBack`

this doesn't work in android, I have tried millions of times

**Comment by timbru31** [comment]
Then please create a new issue, follow the issue template and include a minimal reproduction repository. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by saixin** [comment]
i have the same issue, says "messageHandlers is undefined", have you solved it?
