### ISSUE TITLE
In app browser plugin message event not working in IOS

### ISSUE THREAD

**Issue by supriyamalusare** [apache/cordova-plugin-inappbrowser#698]
We are using Inappbrowser plugin and we are posting message to inapp browser .
To Listen message we are using below code - 
 this.browser.on("message").subscribe(() => {
       alert("message received")
      })

Above code is working in android but for ios it is not working
 
   We are using below plugin details -
    "@ionic-native/in-app-browser": "^5.23.0",

Ionic version - 4

IOS platform version - 5.1.1

Xcode -10.1

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
