### ISSUE TITLE
Inn App Browser dont work in Cordova Apache 9 for android Platform

### ISSUE THREAD

**Issue by thewebmaster509** [apache/cordova-plugin-inappbrowser#699]
Hi , so i'm building an app for android n i want to show a webpage inside the app , i use the cordova-plugin-inappbrowser but unfortunately nothing happend , its look like the plugin was'nt installed but the plugin is installed very well .
Can someone help me plz !

**Comment by breautek** [comment]
Please edit or recreate the issue with the issue form filled out. Without that information we cannot help you as it contains important information about how we can reproduce your issue.
