### ISSUE TITLE
Ionic: InAppBrowser is not assignable to type 'Provider'

### ISSUE THREAD

**Issue by Sunny41** [apache/cordova-plugin-inappbrowser#702]
First of all, I actually wanted to use the themeable Browser. But this plugin is no longer maintenanced and on top of that, it uses the UIWebView instead of the WKWebView, that Apple requires. 

Nevertheless, I tried to integrate InAppBrowser like the docs for Ionic said. 
Installing wasn't that big of a deal but using it in the app.modul.ts.
I imported the plugin with
import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';

and

import { InAppBrowser } from '@ionic-native/in-app-browser';

nothing seems to help.

Version:
@ionic-native/in-app-browser@5.25.0

Error Code:

Type 'InAppBrowserOriginal' is not assignable to type 'Provider'.
  Type 'InAppBrowserOriginal' is missing the following properties from type 'FactoryProvider': provide, useFactoryts(2322)
Ionic Info:

Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
not related to this plugin

**Comment by Sunny41** [comment]
> not related to this plugin

excuse me? 
when not related to this plugin, where else???

**Comment by jcesarmobile** [comment]
¯\_(ツ)_/¯ 
If you don't know what are you using or how, not our problem, sorry

**Comment by Sunny41** [comment]
Ok, let's not be rude to each other. 
I know what I am using and I would say I know how. 
I already opened an issue at ionic's github and lets see if they are able to help. 
I followed this doc and the install went fine. 
https://ionicframework.com/docs/native/in-app-browser 

I don't know if you're familiar with ionic, 
but I had to integrate the plugin in the app.module as a provider, so that I can use the plugin further in my project. 
But here I stuck with the error message mentioned above.

**Comment by timbru31** [comment]
Then the correct repo is probably https://github.com/ionic-team/ionic-native/

**Comment by zulkarnainshah** [comment]
@Sunny41  did you find any solutions?

**Comment by jerinho** [comment]
> 



> ¯_(ツ)_/¯ If you don't know what are you using or how, not our problem, sorry

can you at least have some manners and answer it gently and profesionally?. ok let me try to do your job communicate with people

this issue is about ionic-native's in-app-browser, the npm package that dependents to cordova's in-app-browser. it's ionic framework team who should be informed about this issue not cordova's. ask them to put some documentation about their recent backward incompatibility update. thank you
