### ISSUE TITLE
WK_WEB_VIEW_ONLY not working (Expected value in expression) 

### ISSUE THREAD

**Issue by Macfa** [apache/cordova-plugin-inappbrowser#703]
I was using IOS 5.0.1 UIWEBVIEW.  
Reported Apple's warning to switch to WKWEview  
The UIwebview was changed to WKwebview.  

the process of handling a matter  
1. Changed to the latest version of plug-in, such as in-app browser, whitelist, fcm, etc.  
```Cordova plugin remove codeova-plugin-inappbrowser```
```Cordova plugin added codeova-plugin-inappbrowser```

2. Installing Cordova WKWebView Engine plug-in
```Cordova plugin added codeova-plugin-wkwebview-engine```

3. Change to the latest version of the IOS platform
Compress IOS folder (ios2 folder name)
```Cordova plugin save```
```Cordova platform rm ios```
```Cordova platform added iOS```
Extract the iOS2 folder and move the data inside to the newly created iOS folder

4. Add wk engine
codeova project/ config.xml
```
nplatform name="ios">
<feature name="CDVWKWebViewEngine"
<param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
<preference name="WKWebViewOnly" value="True" />
</platform>
```

codeova project/staging folder/config.xml
```
nplatform name="ios">
<feature name="CDVWKWebViewEngine"
<param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
<preference name="WKWebViewOnly" value="True" />
</platform>
```

<img width="1188" alt="스크린샷 2020-05-14 오후 7 03 06" src="https://user-images.githubusercontent.com/14198111/81921416-8ea6d800-9615-11ea-8cd6-914ec327385c.png">

I don't know if I should say WK_WEB_VIEW_ONLY in the files related to UIWebview, but I checked the addition.

I worked on the project clean and built it.
But there's a warning like above.

How should I deal with this problem?

here is my platform info
```
android 8.0.0
ios 5.1.1
```

here is my plugin info
```
com.cordova.plugins.cookiemaster 1.0.0 "CookieMaster"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-selector 1.0.0 "File Selector"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-gallery-refresh 1.0.55 "GalleryRefresh"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-second-webview 2.11.4 "Cordova Second Webview"
cordova-plugin-spinner 1.1.0 "Spinner Plugin"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-video-thumbnail 2.0.1 "Video Thumbnail"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
es6-promise-plugin 4.2.2 "Promise"
jaeger.Html5Video 1.2.2 "Html5Video"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
```

**Comment by timbru31** [comment]
> <preference name="WKWebViewOnly" value="True" />

Not 100% sure if case sensitivity is important, but can you try `true` instead of `True`?

**Comment by Macfa** [comment]
@timbru31 
Thank you
i'll try

**Comment by jcesarmobile** [comment]
when you put your ios2 backup into the ios folder you remove the needed changes

**Comment by Macfa** [comment]
@jcesarmobile 
thank you reply,

After I erased the iOS platform and reinstalled it, I moved only the www and platform_www folders. Does that mean you shouldn't do that?

Then, when I install the iOS platform, do I have to move each file?

**Comment by jcesarmobile** [comment]
those folders are generated by cordova, you don't have to copy them, you should never modify anything inside platforms folder

**Comment by Macfa** [comment]
@jcesarmobile 
thanks,
How do I move the files from the existing folder? How do I move files and existing data, such as ions and splash icons, into a newly created iOS folder?

**Comment by Macfa** [comment]
I don't know exactly why.
I deleted the project, unzipped the existing project that I had backed up, and then proceeded with the text in the original text again (the file transfer part in the original has only moved the minimum required files, and the setup file has not been moved. ) So it was handled normally.

Thank you for all your answers.
