### ISSUE TITLE
ITMS-90809: Deprecated API Usage (Apple Store issue)

### ISSUE THREAD

**Issue by xale76** [apache/cordova-plugin-inappbrowser#704]
"App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability."

Hello, this is the message I get when I include InAppBrowser in my project. I already included cordova-plugin-wkwebview-engine and put usewkwebview=yes in options, in example

var ref = cordova.InAppBrowser.open(urlfatt, '_blank', location=no,closebuttoncaption=chiudi,usewkwebview=yes');

but I still get the issue: I think because the plugin itself has test.js that open example pages without usewkwebview parameter.
how to fix it? is there a way to set a general option for all calls to InAppBrowser?

**Comment by breautek** [comment]
See https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

Also, you need to use the latest version of inappbrowser for it to respect the wkwebviewonly flag.

**Comment by xale76** [comment]
Hello I build my apps by Phonegap and I can use CLI-9.0.0 that means cordova-ios-5.0.1. I can install a mac machine by myself to build, but in that case what CLI version I need to use to have cordova-ios-5.1.1? is there any solution?

**Comment by breautek** [comment]
Last i heard phonegap has yet to update their packages to use 5.1.1, so you must use cordova cli and build your app locally.

Cordova@9 is the latest cli and recommended.

**Comment by xale76** [comment]
I don't understand I made what you said but I still got the warning. With your advices, I still need to put parameter usewkwebview=yes in the InAppBrowser.open parameters?
