### ISSUE TITLE
Auth Dialog support in IOS

### ISSUE THREAD

**Issue by SnpDeveloper** [apache/cordova-plugin-inappbrowser#705]
Hello team,
First of all, thanks for providing this useful feature. 

I am trying to do basic authentication (windows based authentication) with inAppBrowser in my app. To make it work I added cordova-plugin-auth-dialog plugin,  
When the url is requested auth dialog automatically popup inside inappbrowser waited for its response...All seems to work in Android.

On the other hand in IOS inAppBrowser opens. i can see its waiting with right url for authentication. But no auth dialog opens.

Can someone give a pointer where i am going wrong? or is there easier way of implementing the same?

 

Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by timbru31** [comment]
Apache Cordova uses GitHub Issues as a feature request and bug tracker only.
For usage and support questions, please check out the resources below. Thanks!

You can get answers to your usage and support questions about Apache Cordova on:

Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag cordova
If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

Ionic Framework
Ionic Community Forum
Ionic Worldwide Slack
PhoneGap
PhoneGap Developer Community
