### ISSUE TITLE
Camera and WebRTC not working in Signed/Release application, but working in Debug mode

### ISSUE THREAD

**Issue by josemolmomillan** [apache/cordova-plugin-inappbrowser#708]
# Bug Report

## Problem

I have a phonegap app using inappbrowser plugin loading an external webportal. This webportal is using in a iframe (uri in the same domain) a js app for chat and videoconference.

All permissions for Android, WebApp, and iframe are setup in the different layers: phonegap app, webportal and subportal-iframe.

IF the app is built as Debug mode in PGB, Camera Access and Webrtc in iframe is working perfectly.

When I built the application as Release/SignedByKey in PGB, camera and webrtc IS NOT working

In order to grant the application permissions, I have added the following code in src/android/InAppChromeClient.java

   @Override
    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    public void onPermissionRequest(PermissionRequest request) {
        request.grant(request.getResources());
    }

Built app as debug mode works fine, BUT not app as Release mode.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
