### ISSUE TITLE
App doesn't close dialog box when tried to hit back button

### ISSUE THREAD

**Issue by hanenouche** [apache/cordova-plugin-inappbrowser#710]
# Bug Report
Hi, Backbutton works fine on android, but if we open a dialog box within the inappbrowser, the app goes back to the previous page, but it should close the dialog box 
It there any fix for this issue?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
