### ISSUE TITLE
cordova-ios@6.0.0 compatibility

### ISSUE THREAD

**Issue by doug1e** [apache/cordova-plugin-inappbrowser#712]
# Bug Report

## Problem

Hi there,
I have an ionic project for iOS and switched to cordova-ios@6.0.0 

cordova-ios@6.0.0 dropped UIWebView and I suppose that is why I am getting the below error message:
```
cordova-plugin-inappbrowser/CDVWKInAppBrowser.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```
I have the below in my config.xml but did not seem to help
```
<preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

### What is expected to happen?
Smooth build when cordova-ios@6.0.0 is used with an ionic project

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by brodybits** [comment]
cordova-ios@6 dropped UIWebView, which is reflected in PR #635. New major release of this plugin is still under discussion.

You should be able to install from GitHub or configure to use WKWebView until the new major release is published.

**Comment by breautek** [comment]
It's a known issue and I believe it's fixed in master.

The release is currently in the voting process, so we should see a release in the next few days **assuming** there are no objections.

In the meantime, you can try nightly/master just to see if your problem will actually be solved in the upcoming release.

**Comment by brandon-bt** [comment]
Tried using what's in master and am getting this same error, myself.

**Comment by doug1e** [comment]
Thanks a lot for the quick replies, I do appreciate it. 

As you probably will see this type of questions more often given the switch of cordova-ios, could you please describe the steps to get non-UIWebView from Github?
I am not so experienced in this and I am sure your feedback will help many others who are in the same situation as I am.

I could not get the configuration to use WKWebView to work. I added the flags to config as mentioned above and webview is installed by default at ionic but no luck, I still see UIWebView references when I do a grep under the platform/ios folder.

So how do I get the non-UIWebView from Github? Is there a branch where I can download the code? If so, what should I put in package.json and config.xml? Is there a way to do this via "ionic cordova plugin add" and "npm install" commands?

Thanks,

Doug

**Comment by brandon-bt** [comment]
@doug1e Remove your current version of the InAppBrowser plugin and install the current code from master using the following command:

`ionic cordova plugin rm cordova-plugin-inappbrowser`
`ionic cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser.git`

Then I would suggest removing and re-adding ios as a platform to your ionic project:

`ionic cordova platform rm ios`
`ionic cordova platform add ios@latest`

**Comment by doug1e** [comment]
Many thanks Brandon. I get the following error though:

> cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser.git
Failed to fetch plugin https://github.com/apache/cordova-plugin-inappbrowser.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/apache/cordova-plugin-inappbrowser.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by HansKrywaa** [comment]
I get `'Cordova/CDVUserAgentUtil.h' file not found` after the switch to 6.0.0

**Comment by nvhau** [comment]
> I get 'Cordova/CDVUserAgentUtil.h' file not found after the switch to 6.0.0

I have the same issue and I try to install the plugin from the master with the command:
ionic cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser.git
then I can build and start the app but I cannot touch or do anything.
I don't know what is happening?

**Comment by doug1e** [comment]
I can confirm that @brandon-bt 's method works so I am closing this.
I submitted the binary and has not received the immediate decline so I assume all is well.
Thanks for all the help folks!

**Comment by breautek** [comment]
Just a reminder that using `master` is not supported or recommended for production releases of your app. I would keep an eye out. We're just busy preparing releases for other plugins that also needs to be updated for `cordova-ios@6` support, but the release discussion was started for inappbrowser

**Comment by doug1e** [comment]
Thanks @breautek

**Comment by klochko7** [comment]
Hi all! I have an ionic project for iOS and switched to cordova-ios@6.0.0 too.  What can I do to fix this issue? I try to remove cordova-plugin-inappbrowser and install ionic cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser.git. It dose not help. Could anyone please  give a link on working plugin version?


The following build commands failed:
	CompileC /Users/ionicdev/Library/Developer/Xcode/DerivedData/-ahsyiltcpfmmghflubkwkmbxpsbm/Build/Intermediates.noindex/.build/Debug-iphonesimulator/.build/Objects-normal/x86_64/CDVFileTransfer.o /Users/Guest/Public/Ionic\ 4//platforms/ios//Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by dickverweij** [comment]
*Bunp* 
Is there a fix for building cordova-ios 6.0.1 and latest inappbrowser?

**Comment by breautek** [comment]
> _Bunp_
> Is there a fix for building cordova-ios 6.0.1 and latest inappbrowser?

Latest version of `cordova-ios` is 6.1.0. I'd try that. If you still have an issue, then please open a new issue.

**Comment by Pratz007-tech** [comment]
on adding cordova-ios@6.0.1 getting similar kind of error for file-transfer plugin : ios/myApp/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65.

**Comment by Pratz007-tech** [comment]
> Hi all! I have an ionic project for iOS and switched to cordova-ios@6.0.0 too. What can I do to fix this issue? I try to remove cordova-plugin-inappbrowser and install ionic cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser.git. It dose not help. Could anyone please give a link on working plugin version?
> 
> The following build commands failed:
> CompileC /Users/ionicdev/Library/Developer/Xcode/DerivedData/-ahsyiltcpfmmghflubkwkmbxpsbm/Build/Intermediates.noindex/.build/Debug-iphonesimulator/.build/Objects-normal/x86_64/CDVFileTransfer.o /Users/Guest/Public/Ionic\ 4//platforms/ios//Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Hi were you able to resolve this issue ? Please let me know. Thanks!!

**Comment by appsOne** [comment]
Same issue here with cordova-plugin-file-transfer

**Comment by Pratz007-tech** [comment]
> Same issue here with cordova-plugin-file-transfer

Exactly do let me know any solutions for i Regards, Pratiksha

**Comment by timbru31** [comment]
The corresponding issue for the file-transfer-plugin is at https://github.com/apache/cordova-plugin-file-transfer/issues/258 - please do not hijack this issue, which was about the InAppBrowser, with issues about other plugins.

**Comment by anshu300** [comment]
facing same issude

he following build commands failed: /Users/RK/Documents/IONIC/ionic/wema-test/platforms/ios/wemalife-app/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

“@ionic-native/file-transfer”: “^5.27.0”,

“cordova-plugin-file-transfer”: “^1.7.1”,

build fail in ios

Ionic:

Ionic CLI : 5.4.16 (/usr/local/lib/node_modules/ionic) Ionic Framework : ionic-angular 3.9.2 @ionic/app-scripts : 3.2.4

Cordova:

Cordova CLI : 10.0.0 Cordova Platforms : ios 6.1.0 Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, (and 23 other plugins)

Utility:

cordova-res : not installed native-run : not installed

System:

ios-sim : 8.0.2 NodeJS : v12.18.3 (/usr/local/bin/node) npm : 6.14.6 OS : macOS Catalina Xcode : Xcode 11.6 Build version 11E708

**Comment by breautek** [comment]
> The corresponding issue for the file-transfer-plugin is at apache/cordova-plugin-file-transfer#258 - please do not hijack this issue, which was about the InAppBrowser, with issues about other plugins.
