### ISSUE TITLE
InAppBrowser not working with cordova-ios 6

### ISSUE THREAD

**Issue by paulstelzer** [apache/cordova-plugin-inappbrowser#713]
# Bug Report

### What is expected to happen?

Building the app with cordova-ios 6 should work with cordova plugin in app browser.

### What does actually happen?

If I am building the app with cordova-ios 6, then an error while building in xcode occurs that he cannot find some methods. If I am removing the cordova plugin in app browser everything works again

## Information

cordova-ios 6.0.0

**Comment by breautek** [comment]
Should be fixed in `4.0.0` (currently unreleased). You can test against `cordova-plugin-inappbrowser@nightly` if you want to confirm the upcoming release will solve your problem.

Meanwhile, keep an eye out for the production release, I can't give a specific ETA at this time.

**Comment by paulstelzer** [comment]
Thank you!
