### ISSUE TITLE
open crashing on ios 9 after update to cordova-ios 5.1

### ISSUE THREAD

**Issue by powysm** [apache/cordova-plugin-inappbrowser#721]
# Bug Report

### What is expected to happen?
Before updating to cordova-ios 5.1.1 from 4.5.5 inappbrowser open worked as expected on all ios versions. After updating is fine ios 10+ but ios 9 fails when using inapprbrowser open.

### What does actually happen?

I get the following error messages when trying to execute 'cordova.InAppBrowser.open'
> 2020-06-09 09:55:46.704 S4C Clic[27228:1828640] -[UIApplication openURL:options:completionHandler:]: unrecognized selector sent to instance 0x7fd6ae205570
> 2020-06-09 09:55:46.710 S4C Clic[27228:1828640] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[CDVWKWebViewEngine webView:decidePolicyForNavigationAction:decisionHandler:] was not called'

### Command or Code

inappbrowser.open

### Environment, Platform, Device

ios 9 device and simulator

### Version information

xcode 11.1
Cordova 8.1.2, cordova-ios 5.1.1
cordova-android-support-gradle-release 3.0.0 "cordova-android-support-gradle-release"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-webview 2.5.2 "cordova-plugin-ionic-webview"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-listpicker 2.2.2 "ListPicker"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Officially, with cordova-ios@5 we upgraded the minimum OS to 10.0 (that's a breaking change and one of the reasons for the v5 release).

See https://github.com/apache/cordova-ios/pull/409
