### ISSUE TITLE
executeScript with hidden set to yes

### ISSUE THREAD

**Issue by jdpsbh** [apache/cordova-plugin-inappbrowser#725]
Hello,
executeScript is not working when Inappbrowser hidden option is set to yes. Is this a normal behavior?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by timbru31** [comment]
Additionally, I'd recommend asking question in our [Slack community](http://slack.cordova.io) instead.
