### ISSUE TITLE
executeScript with hidden set to yes

### ISSUE THREAD

**Issue by jdpsbh** [apache/cordova-plugin-inappbrowser#726]
Hello, executeScript is not working when Inappbrowser hidden option is set to yes. Is this a normal behavior?

<pre>
let ceiLogin = true; 
let ceiNavegador;

ceiNavegador = cordova.InAppBrowser.open(url, '_blank', 'hidden=yes');
ceiNavegador.addEventListener('loadstop', ceiLoadStopCallBack);

function ceiLoadStopCallBack(){ 
     if(ceiLogin == true){ 
          ceiLogin = false; 
          ceiNavegador.executeScript({ code: 'window.location = "here_goes_my_new_url";' }); 
     }else{
           alert("This is the login page"); 
     }
 }
</pre>

The alert "This is the login page" is not firing, meaning, I guess, the code window.location is not executing.

But, if i set hidden to NO, the alert is firing. 
ceiNavegador = cordova.InAppBrowser.open(url, '_blank', 'hidden=no';

Thanks!

**Comment by timbru31** [comment]
You still fail to provide a valid issue that follows the template. What operating system? Which versions of Cordova are you using? What's the version of the installed plugin? Without these information it's impossible for us to help.
