### ISSUE TITLE
[iOS] Set StatusBarStyle from config.xml

### ISSUE THREAD

**Issue by mrbberra** [apache/cordova-plugin-inappbrowser#728]
# Feature Request

## Motivation Behind Feature
With the merge of [GH-656](https://github.com/apache/cordova-plugin-inappbrowser/pull/656), the status bar now shows up with the color of the app status bar, which I've been setting using [cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar). The InAppBrowser, however, still overrides the text in the status bar with `UIStatusBarStyleDefault` (black text), which is a problem if the status bar has a dark background color.

## Example
```
  StatusBar.styleLightContent();
  StatusBar.backgroundColorByHexString("#281e36");
```
<img width="459" alt="Screen Shot 2020-06-12 at 1 13 09 PM" src="https://user-images.githubusercontent.com/10442753/84533846-8db5a480-acae-11ea-89d7-cdbff41e4119.png">
<img width="467" alt="Screen Shot 2020-06-12 at 1 13 16 PM" src="https://user-images.githubusercontent.com/10442753/84533802-7c6c9800-acae-11ea-88ac-75ba1277e490.png">

## Feature Description
Set IAB iOS status bar color from the cordova config file. I'm imagining something like `<preference name="InAppBrowserStatusBarStyle" value="lightcontent" />`

I've got some work on this I've started I can submit a PR for- just changing the `preferredStatusBarStyle`. I guess a more complex implementation would be to add a method to modify it dynamically (since you can modify the status bar color dynamically using that plugin)... seems like overkill to me though.

**Comment by mosabab** [comment]
You are right.

The latest PR which remove the fake statusbar generate a new issue like what you mentioned.

I think the best way to solve this new issue is to make a new options for inappbrowser like:
Statubar.lightcontent / dark theme
Statusbar.darkcontent / light theme
....
And so....

Because with introduced dark theme for iPhone devices i think it is important now to change the way that inappbrowser show the statusbar.

**Comment by DaveRand** [comment]
I have a similar requirement except I need to set the statusbar background color dynamically as well as setting the statusbar text color to white.

**Comment by mosabab** [comment]
I have same issue here for dark theme, because statusbar at inappbrowser plugin always read the default style (black text).

**Comment by herne12** [comment]
Have you been able to fix the incident?
