### ISSUE TITLE
Fails to open map app for ios

### ISSUE THREAD

**Issue by SumeetHindinkeri** [apache/cordova-plugin-inappbrowser#733]
After I upgraded Inappbrowser plugin from 3.2.0 to 4.0.0. The below code does not open the map app.

 window.open('maps://?q=' + destination, '_system') is not working for ios.

## Problem
When I upgrade to 4.0.0 the map app does not open for ios. Also  when I downgrade the version of inappbrowser to 3.2.0 it is working as expected.Though I need the update 4.0.0 for other page which fixed the status bar style issue.

### What is expected to happen?
It should open the map app from the iPhone with respective latitude ,longitude coordinates.

### What does actually happen?
I am getting unhandled promise rejection error.

### Command or Code
window.open('maps://?q=' + destination, '_system');

### Environment, Platform, Device
ios version: 13.5.1
Device: iPhone X

### Version information
Ionic:

   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res (update available: 0.15.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/sumeet/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.13.1 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
The `window.open` clobber was removed in #600, you need to use `cordova.InAppBrowser.open`

**Comment by SumeetHindinkeri** [comment]
@timbru31  thanks for you quick response. cordova.InAppBrowser.open worked for me.
