### ISSUE TITLE
Using UIWebView

### ISSUE THREAD

**Issue by ladaniavadh** [apache/cordova-plugin-inappbrowser#742]
Hello,
I am using the latest 4.0.0 version of plugin since it showing the reference  of using UIWebView in grep command and that's why my app is getting rejected from IOS.
Any solution how can I solve this error?
![Screenshot 2020-06-27 at 10 30 39 AM](https://user-images.githubusercontent.com/30779077/85971586-2c4e3f00-b9eb-11ea-834c-cd57e097930a.png)

**Comment by timbru31** [comment]
The codebase has no UIWebView references anymore. You might need to remove and re-add the iOS platform. Besides that, the issue template is mandatory for any help.
