### ISSUE TITLE
Webrtc does not work inside inappbrowser

### ISSUE THREAD

**Issue by BaukaKZ** [apache/cordova-plugin-inappbrowser#749]
Webrtc does not work inside inappbrowser although the application has access to the microphone and camera

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
