### ISSUE TITLE
WKWebview cookie sometimes can't be get after upgrade to Cordova 6.1.0

### ISSUE THREAD

**Issue by xinhuadian** [apache/cordova-plugin-inappbrowser#751]
# Bug Report

## Problem
Try to get the cookie of inappbrowser. But sometimes can't get correct cookie.
This issue happen after upgrade cordova to Cordova ios 6.1.0. and inappbrowser upgrade to 4.0.0
### What is expected to happen?

Use  blow code to get cookies in decidePolicyForNavigationAction of CDVWKInAppBrowser

WKHTTPCookieStore *wkWebViewCookieStore =[[[theWebView configuration] websiteDataStore] httpCookieStore];
 [wkWebViewCookieStore getAllCookies:^(NSArray* wkcookies) {
        for (NSHTTPCookie* cookie in wkcookies)
               {
                   NSLog(@"wk cookie name is %@",cookie.name);
               }
    }];

### What does actually happen?
Some times the wkcookies can't get the correct cookie.
And this issue not always happen,  but sometimes.   in my test ,50% percentage happen.

## Information

This issue not happen after downgrade the cordova ios to 5.1 and still use inappbrowser 4.0.0(after resolve some compile error).

### Command or Code

Please see above 

### Environment, Platform, Device

Cordova 9.0.0, Cordova ios 6.1.0, xcode 11.5. 
Iphone simulator(13.5) and Iphone X (13.5)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mitsoe** [comment]
Hey @NiklasMerz , any timeline for the 4.0.1 release?

**Comment by NiklasMerz** [comment]
Sorry we don't give any release dates. This issue is not addressed yet. Pull requests welcome.

**Comment by NiklasMerz** [comment]
I am now affected by this problem. I am working on a pull request right now.

Seems like the new `CDVWebViewProcessPoolFactory` is not public and the imports won't work the same. I just need to figure out how to solve this and this may require an updated version of cordova-ios.

**Comment by XandiKarlen** [comment]
@NiklasMerz We also had a problem just recently with managing the session cookie between different instances of the InAppBrowser. What we did was changing up the import in the `CDVWKInAppBrowser.m` to use
`../../../CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewProcessPoolFactory.h` instead of the one currently used and also change the instance of the `sharedFactory`.

Maybe this will help

**Comment by NiklasMerz** [comment]
I found a fix but this also requires a fix in cordova-ios. Let's see how the reviews go there.
