### ISSUE TITLE
Opening links in the systembrowser stopped working on Android with plugin version 4.0.0

### ISSUE THREAD

**Issue by moschkom** [apache/cordova-plugin-inappbrowser#760]
# Bug Report

## Problem
Opening links in the systembrowser stopped working on Android with plugin version 4.0.0

### What is expected to happen?
Using the target '_system' should open a link in the system browser. With version 3.2.0 this was working. With version 4.0.0 it is not working on Android anymore. iOS is still working.

### What does actually happen?
The link is opened within the app. Its the same behaviour as if the target '_blank' is used.

### Environment, Platform, Device
I tested with Android 8.0.0 and 5.1.1 .

### Version information
"cordova": "~9.0.0",
"cordova-android": "~8.1.0",
"cordova-plugin-inappbrowser": "~4.0.0",

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Can you share the code you are using to open the link? There are nearly no Android changes: https://github.com/apache/cordova-plugin-inappbrowser/compare/rel%2F3.2.0...rel%2F4.0.0#diff-6b96481eda04f0b853d9e7b6637d167b - **except** removing the `window.open` override.

**Comment by moschkom** [comment]
We use GWT. Our code calls this method:
```
@Override
public void openURLInSystemBrowser(String url) {
	inAppBrowser.open(url, "_system", null);
}
```
Which then calls this implementation:
```
public native JavaScriptObject open0(String url, String windowName, String windowFeatures)/*-{
	return $wnd.open(url, windowName, windowFeatures);
}-*/;
```

I think I see the Problem. We still rely on `window.open`. Thanks for the hint. I will try to replace this code with `cordova.InAppBrowser.open`. 

Any idea why it is working on iOS as before?

**Comment by timbru31** [comment]
I think iOS just handles the `_system` differently. But that are OS internals. I’ll close the issue as we’ve identified where the actual problem is.
