### ISSUE TITLE
Unable to Paste into input field

### ISSUE THREAD

**Issue by joeldhenry** [apache/cordova-plugin-inappbrowser#762]
# Bug Report
Unable to copy/paste username/email/password into form field 

When selecting an input, normally a popup allows you to select/copy/paste however in IAB you are unable to do this\

Cordova: 10.0.0
Cordova-iOS: 6.1.0
Cordova-android: 9.0.0
Other Frameworks: Angular
Operating System: iOS/Android

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by ivanlondono** [comment]
Disable select touch and hold and highlight colors, in css file
also you can set that in a specific form field

```
html {
    -webkit-user-select: none;
    -webkit-touch-callout: none;
    -webkit-tap-highlight-color:rgba(0,0,0,0);
}
```
and if you still want it to work for input then just add 
```
input {
    -webkit-user-select: auto !important;
    -webkit-touch-callout: default !important;
}
```
