### ISSUE TITLE
Auto rotate to landscape in iOS

### ISSUE THREAD

**Issue by spassvogel** [apache/cordova-plugin-inappbrowser#773]
# Bug Report

### What is expected to happen?
on iOS (iPhone) I expect to open an inAppBrowser in portrait mode and have it rotate to landscape mode when the phone rotates

### What does actually happen?
The status bar does rotate but the actual inAppBrowser stays fixed in portrait mode

![image](https://user-images.githubusercontent.com/985892/92226829-9ed51280-eea5-11ea-9712-46638735a6e2.png)

### Command or Code
    this.inAppBrowserRef = cordova.InAppBrowser.open(url, '_blank', 'location=no,hidespinner=yes,toolbar=no');

### Environment, Platform, Device
iPhone 5s iOS 12.4.8

### Version information

xcode 11.7
cordova-plugin-inappbrowser: 4.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Demo project is at: https://github.com/spassvogel/iab-test

**Comment by x-freed** [comment]
Did you find any solution / workaround for this bug ?

**Comment by spassvogel** [comment]
I resorted to using a regular iFrame, unfortunately.

**Comment by weiz18** [comment]
Hey,

We are having the same issue here as well. 
Commenting out line 206 (https://github.com/Yoobic/cordova-plugin-inappbrowser/blob/master/src/ios/CDVWKInAppBrowser.m#L206) seems to resolve the issue, but I'm not sure of the potential side effect this will have. If anyone can help would be nice

**Comment by x-freed** [comment]
@weiz18 thanks, it worked. In the meantime I found also another less robust workaround:
`supportedInterfaceOrientations` should return directly allowed orientations for the app (https://github.com/Yoobic/cordova-plugin-inappbrowser/blob/master/src/ios/CDVWKInAppBrowser.m#L1263)
In my case: return UIInterfaceOrientationMaskAllButUpsideDown;

**Comment by spassvogel** [comment]
Would be nice to get some feedback from the developers of cordova-plugin-inappbrowser on this.

**Comment by NielCloete** [comment]
For any future lurkers who don't want to fork, I managed to solve this by creating a little Swift extension class in the XCode project.

Add this to the swift file:
`import Foundation
import CordovaPlugins

extension CDVWKInAppBrowserViewController {
    override open var shouldAutorotate: Bool {
        return true
    }
    
    override open var supportedInterfaceOrientations : UIInterfaceOrientationMask {
        return .allButUpsideDown
    }
}`

**Comment by jcesarmobile** [comment]
This isn't a plugin issue but a Capacitor issue, the problem doesn't manifest in Cordova apps.

This PR in Capacitor should fix the issue https://github.com/ionic-team/capacitor/pull/5070
