### ISSUE TITLE
“self.webView.allowsBackForwardNavigationGestures = YES” not working

### ISSUE THREAD

**Issue by AlwaysLoveme** [apache/cordova-plugin-inappbrowser#781]
# Bug Report
“self.webView.allowsBackForwardNavigationGestures = YES” not working on ios
### What is expected to happen?
“self.webView.allowsBackForwardNavigationGestures = YES” is working on ios

### What does actually happen?
“self.webView.allowsBackForwardNavigationGestures = YES” not working on ios

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
