### ISSUE TITLE
Apple decline my app because UIWebView is no longer accepted

### ISSUE THREAD

**Issue by DigitalBorder** [apache/cordova-plugin-inappbrowser#783]
Hi,
i have install last version of cordova-plugin-inappbrowser in my ionic 4 app.

I have published it to Appstore and it was rejected.

How can i use WkWebView?
Thank you!

**Comment by breautek** [comment]
> How can i use WkWebView?

Easiest way is to upgrade to the latest version of `cordova-ios`.

**Comment by DigitalBorder** [comment]
Ok thank you very much!
