### ISSUE TITLE
Close the browser with this.inAppBrowserRef.executeScript

### ISSUE THREAD

**Issue by marcelonnunes** [apache/cordova-plugin-inappbrowser#789]
How do I add a script to "this.inAppBrowserRef.executeScript" so that I can close the browser and return to my application by clicking a button on my page? How to create a script to capture the button click event? Thank you.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
