### ISSUE TITLE
inAppBrowser capacitor not opening on iOS (works fine on android) 

### ISSUE THREAD

**Issue by skytrendma** [apache/cordova-plugin-inappbrowser#793]
# Bug Report

## Problem

Although it works perfectly on Android, the .open doesn't do anything on iOS. 

The logs read : 
To Native Cordova -> InAppBrowser Open InAppBrowser192389540 [options: url, .......]

But nothing happens. Tried using the .show() method, and using hidden:no but still doesn't work. 

### What is expected to happen?

Should open the URL when the function fires

### What does actually happen?

Nothing, just that log I sent above

## Information

I followed the instructions on the official site, installed 
@ionic-native/in-app-browser 
cordova-plugin-inappbrowser
used ionic cap sync (on both the PC for Android and the MAC for iOS)

### Command or Code

`            const browser = this.iab.create(url, '_self', {
                location: 'no',
                hidden: 'no', // hides the browser but still loads the page
                hideurlbar: 'yes',
                zoom: 'no',

            });

            browser.on('loadstart').subscribe(event => {

                if (event.url.includes('auth/federated-login')) {
                    browser.close();

                    let slug = event.url.split(".com").pop();
                    const formattedUrl = this.router.parseUrl(slug);
                    this.router.navigateByUrl(formattedUrl);
                }
            });`

### Environment, Platform, Device

Catalina XCODE - Iphone SE (real phone) - 

### Version information

Angular 10 / Ionic 5 / Capacitor 6.10

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
This is a Capacitor issue, not an issue on the plugin.
On Capacitor `_self` doesn't work because that's for opening on the Cordova WebView and Capacitor uses a different WebView.

**Comment by AbdallahFathoom** [comment]
Any solution regarding this
