### ISSUE TITLE
I want to make window.open in a web page work on ios

### ISSUE THREAD

**Issue by nrikiji** [apache/cordova-plugin-inappbrowser#797]
Plugin version 4.0.0 has changed to use WkWebview.

This caused the javascript code window.open in the webpage to not work.

Is there any way to work around this?

**Comment by jcesarmobile** [comment]
it's not related to using WKWebView, window.open was removed on purpose, see https://github.com/apache/cordova-plugin-inappbrowser/pull/600

You can still get the old behavior by doing this, but it's not recommended.
https://github.com/apache/cordova-plugin-inappbrowser#windowopen

**Comment by nrikiji** [comment]
@jcesarmobile 

Thank you.

This was talking about the window.open embedded in the webpage.

I believe that this needs to be addressed as shown on the page below. Is this behavior also intentional?

https://stackoverflow.com/questions/50559666/window-open-is-not-working-in-wkwebview ...

**Comment by jcesarmobile** [comment]
in that case, can you provide a sample app?

**Comment by nrikiji** [comment]
This is the case with the html I tried

```
<button onclick="window.open('myapp://')">open myapp</button>
```

**Comment by nrikiji** [comment]
Supplementary. I don't think this Html will work either.
```
<a href="・・・" target="_blank">Linke</a>
```

**Comment by acran** [comment]
I opened issue #830 which may be a duplicate of this one, @nrikiji could you check if we're referring to the same issue?
If so @jcesarmobile you can find a sample app here: https://github.com/acran/cordova-inappbrowser-mailto-bug-sample

**Comment by jcesarmobile** [comment]
closing in favor of #830 since looks the same and that one has a sample app
