### ISSUE TITLE
Opening a url in InAppBrowser with target as _blank not working on latest versions of iphones 

### ISSUE THREAD

**Issue by priyankabakkar** [apache/cordova-plugin-inappbrowser#802]
In my case I am using Iphone 11 pro Max.
In our application we open a login url and get back login response in our application.
So using _self will not solve our purpose.
Earlier it was working fine with _blank but suddenly in latest Iphones it stoped working.. It opens login url in InappBrowser but do not return response to original app. 

Kindly give me some solution on this.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
