### ISSUE TITLE
Pull/Swipe to Refresh the view

### ISSUE THREAD

**Issue by sahraouijamel** [apache/cordova-plugin-inappbrowser#807]
Hi,
I need to refresh my app view. i have tried a pull to refresh jqeury plugin, but it's not really perfect.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
