### ISSUE TITLE
HELP: InAppBrowser showing on top of InterstitialAds

### ISSUE THREAD

**Issue by joaolori** [apache/cordova-plugin-inappbrowser#810]
Hello,

Looking for some advice, I am using inappbrowser with admob plugin, what I notice is, when I open the inappbrowser and admob interstitial ad, the in appbrowser is appearing on top of the ad.

Any tip we can make it the other way around? where should I look into?

Thanks in advance

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
