### ISSUE TITLE
Window.open typings file requires an update

### ISSUE THREAD

**Issue by wrightsonm** [apache/cordova-plugin-inappbrowser#811]
# Bug Report

### What is expected to happen?

Since https://github.com/apache/cordova-plugin-inappbrowser/pull/600  window.open is no longer overridden by InAppBrowser.
I think the typings file for Window.Open is no longer correct and window.open should be removed from the file below:

https://github.com/apache/cordova-plugin-inappbrowser/blob/master/types/index.d.ts

### What does actually happen?
N/A

## Information
N/A

### Command or Code
N/A

### Environment, Platform, Device
All platforms

### Version information
Cordova 10
Android 9.0.0
IOS 6.1.1
Cordova-plugin-inappbrowser@4.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Indeed, the open method needs to be moved to the `InAppBrowser` interface. PR's welcome.
