### ISSUE TITLE
inAppBrowser _system not opening one website correct

### ISSUE THREAD

**Issue by AlonsoFon** [apache/cordova-plugin-inappbrowser#813]
When i try to use this: 

 this.iab.create("https://www.achievesolutions.net/achievesolutions/en/shell/Home.do", "_system", 'location=no'); 

On ionic, this open webview not in browser has expected. Others websites open correct, i try alot of possible solutions i found and no got any working, something went wrong with websites end in ".do" i cant find how make it work.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
