### ISSUE TITLE
Problem with Capital Letters in Package Name

### ISSUE THREAD

**Issue by Woean** [apache/cordova-plugin-inappbrowser#814]
Hello,

when I try to build my app, I always get this error: 

Discovered plugin "InAppBrowser". Adding it to the project
Failed to restore plugin "InAppBrowser". You might need to try adding it again. Error: Error: Command failed with exit code 1: npm view InAppBrowser --json
npm ERR! code E404
npm ERR! 404 'InAppBrowser' is not in the npm registry.
npm ERR! 404 name can no longer contain capital letters
npm ERR! 404
npm ERR! 404  'InAppBrowser@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Do you know this problem or do you have a solution for it?

**Comment by timbru31** [comment]
Either in your config.xml or package.json you've got an invalid entry. the plugin's name is 
cordova-plugin-inappbrowser
