### ISSUE TITLE
force browser vs user being asked which app to use?

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-inappbrowser#815]
Is there any setting, using inappbrowser or other, that forces the browser to be used vs the phone asking which default app the user wants to open?

Example, I have a google.com/maps route link - its step-by-step route directions, created on google.com/maps.  When I add that link to my app, and have inappbrowser try to open it, the user gets asked to open it in Chrome or Maps.  If the user selects Chrome, the link opens up and the user can navigate the route.  But if the user choses Maps, the link route opens in Maps but the user cannot navigate the route - there is no option to navigate, just preview the route.

But I need users to be able to navigate this route.  Using these types of links, it doesn't look like there is a way to get the route map navigation to work in Maps, so I need to force the user to use chrome/safari.  Is this possible?

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

-

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
