### ISSUE TITLE
Can not open html file in ios

### ISSUE THREAD

**Issue by brunoPert** [apache/cordova-plugin-inappbrowser#829]
# Bug Report

## Problem

Trying to open an html file, which I tried to  locate it in the same file system of my cordova app and in a php server also, simply doesnt work nor logging anything.  Testing the same flow in the web works, so that's why I'm assuming it's a plugin issue.

### What is expected to happen?
The file should be open.

### What does actually happen?

App remains in white sreen:

![Captura de Pantalla 2020-12-01 a la(s) 09 32 35](https://user-images.githubusercontent.com/49445815/100740930-3ae4bc00-33b8-11eb-8362-2b352cd1fcd7.png)

### Command or Code
I'm oppening the inappbrowser like this:

` const ref = cordova.InAppBrowser.open(`${liveChatUrl}&startChat=true`, '_blank', 'location=no,hidden=no,fullscreen=yes,hideurlbar=yes');`

### Environment, Platform, Device
Device: iphone 8 emulator.
OS: macOs 10.15.5.
Xcode: 12.1

### Version information
Inappbrowser: 4.1.0
cordova-ios: 6.1.1
cordova: 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
How does the ${liveChatUrl}&startChat=true url looks like?

**Comment by brunoPert** [comment]
@jcesarmobile  it loos like this:

http://url.herokuapp.com/index.html?email=someEmail&startChat=true

**Comment by jcesarmobile** [comment]
that url doesn't help much, you said it was a local file
does the url open on the same device using safari browser?

**Comment by brunoPert** [comment]
@jcesarmobile  I tested it placing the html file on my local file system as well as hosting it on heroku. Testing it on  the cordoba web side (I mean, running my app in safari) works well, that's why I assume it's inappbrowser issue.

**Comment by zero-1** [comment]
This is definitely reproducible. I tried a similar flow on a brand new ionic app.

Following is my configuration:

`"plugins": {
      "cordova-plugin-inappbrowser": {},`
      ...
   `"cordova-plugin-inappbrowser": "4.1.0",`   

`this.iab.create('https://some-webpage.web.app', '_blank', this.options);`

My options are...
 
`options : InAppBrowserOptions = {
    location : 'no',//Or 'no'
    zoom : 'no',//Android only ,shows browser zoom controls
    hardwareback : 'no',
    hidden: 'no',
    clearcache: 'no',
    beforeload: 'yes',
    toolbar : 'no', //iOS only22952
  };`

Using _self and _system works as expected. When using _blank we end up with a blank page.
This does seem to work in an older app which is still on an older version of cordova-iOS and using the 3.1.0 version of IAB.

Another weird thing which might shed some light, when we open up the IAB window in the debugger in Safari, running something like Window.open("some-url") returns a null.

As this is a brand new ionic project, I am not using any other plugins at the moment (apart form the ones which come by default)

There are no warnings/errors in Xcode or in the browser console.

The 'loadStop' event listener is not executed as well.... (sort of expected)

Testing on Xcode 12.1 on an iOS simulator (multiple devices running iOS 14.1)

This does feel similar to 
https://github.com/apache/cordova-plugin-inappbrowser/issues/832
https://github.com/apache/cordova-plugin-inappbrowser/issues/802

I will try few more combinations... with IAB 3.1.0 .. and check whats going on with the 'beforeload' and 'loadstart' events. Will update description.

**Comment by zero-1** [comment]
going down to ios-cordova 5.0.1 and IAB 3.1.0 just gave me build errors.

There might be some compatibility issues with latest ionic but I didn't spend too much time looking into it.

Tried the ios-cordova 6.1.1 with latest IAB on iOS 13.7 in the simulator... got a similar issue.

Any tips on how to proceed would be appreciated.

**Comment by jcesarmobile** [comment]
Are you using cordova-plugin-ionic-webview? If so, make sure you are using latest version

**Comment by zero-1** [comment]
I am using 
"cordova-plugin-ionic-webview": "^5.0.0",

This seems like a "cordova-plugin-ionic-webview" issue rather than cordova InAppBrowser issue.
