### ISSUE TITLE
plugin doesn't compile on Xcode 10

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-plugin-inappbrowser#831]
The plugin engines are set to cordova-ios 4 or greater. Which I think supported Xcode 9 and greater, but latest changes on 4.1.0 of the plugin makes it not compile on Xcode 10 or older because it doesn't understand `defaultWebpagePreferences`

It can be easily be fixed by using `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000` macros around the code, but I've already merged a [breaking change](https://github.com/apache/cordova-plugin-inappbrowser/pull/821).

Should we revert the breaking change and do a patch release with the fix?

Also, we should be more aggressive bumping the engines to try to force people to always use the latest version of the platforms and also make more clear the Xcode version cordova-ios supports and drops support of. At the moment, we say cordova-ios 6 says it adds support for Xcode 11, but doesn't say it drops support of Xcode 10, despite Apple doesn't accept apps built with it, users can still complain if the code doesn't build there as we didn't say we don't support it anymore.

**Comment by brodybits** [comment]
I have added the **bug** label, and we should probably make the patch release if we want to be strictly "semver" compliant.

That said, I don't know how many people would be affected, and anyone affected could always pin the old version as a workaround. I suspect that time spent making the patch release could be better spent solving some other issues on Cordova.

> Also, we should be more aggressive bumping the engines

+1

I would favor that we avoid supporting old Xcode versions that are no longer supported by Apple itself, unless they are needed for some other reason.

**Comment by jcesarmobile** [comment]
closing as won't fix
