### ISSUE TITLE
Not allowed to navigate top frame to data URL

### ISSUE THREAD

**Issue by nitisha123** [apache/cordova-plugin-inappbrowser#837]
### Issue Type

- [x] Bug Report
- [x] Feature Request
- [x] Support Question

## Description
Getting issue of "Not allowed to navigate top frame to data URL" when trying to load payment html script using inAppBrowser

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
