### ISSUE TITLE
Check if inappbrowser is shown or hidden

### ISSUE THREAD

**Issue by nomaam** [apache/cordova-plugin-inappbrowser#842]
how do you check if inappbrowser is in hidden or shown status with only the object reference?

    inAppBrowserRef.hide();

Then ideally you could check the status by

    if ( inAppBrowserRef.status == 'hidden' )

I know you could set a global var whenever you call hide or show on the object, but I want to know how to check it based on soley the object.

Thanks

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
