### ISSUE TITLE
ReferenceError: rootName is not defined

### ISSUE THREAD

**Issue by hanifmhd** [apache/cordova-plugin-inappbrowser#843]
# Bug Report
ReferenceError: rootName is not defined 

## Problem
i want to close the inAppBrowser by using inAppBrowserRef.close() function, but it got error "ReferenceError: rootName is not defined "

### What is expected to happen?
inAppBrowser is closed and go back to the previous screen

### What does actually happen?
ReferenceError: rootName is not defined 

### Command or Code

inAppBrowserRef.close()

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information. Especially the version information and your code.

**Comment by jcesarmobile** [comment]
closing as the requested information was not provided, please, when you create an issue, have timbru31 comment into consideration
