### ISSUE TITLE
Open Barcodescan camera with Input file in InAppBrowser 

### ISSUE THREAD

**Issue by Samita907** [apache/cordova-plugin-inappbrowser#847]
# Feature Request

## Motivation Behind Feature

I should be able to scan barcode with the Camera opened in File chooser in InappBrowser.

## Alternatives or Workarounds

Please answer if we have solution for this, in detailed code to be implemented.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
