### ISSUE TITLE
Ios - How to share cookies between inAppBrowser and cordova webview 

### ISSUE THREAD

**Issue by tinni95** [apache/cordova-plugin-inappbrowser#851]
Hello,

I am experiencing issues with sharing cookies between the InAppBrowser and the cordova webView. 

What I am trying to achieve is doing an authentication via inAppBrowser; and after, closing it and continue on an iframe in the main ionic webview.
In android everything works and the cookies are shared out of the box, in Ios this does not happen. In fact, whereas the inAppBrowser correctly receives the login cookies; in the iframe of the ionic app we do not have any session cookie.

Is there a way to replicate the same behavior of android on IOS devices?

Thanks in andvance

**Comment by mattdsteele** [comment]
@tinni95 A few questions:

- Which version of the `inappbrowser` plugin are you using?
- Which version of `cordova-ios`?
- Is your Ionic app inside an iframe, or is it being loaded using a standard `file://` method?

**Comment by CarloDotlog** [comment]
Hello @mattdsteele. I'm in the same team with @tinni95. 

- inappbrowser:5.0.0
- We are using Capacitor, how can I check which version of cordova-ios we are using? 
- We use an iframe that point to website.

Thank you!

**Comment by CarloDotlog** [comment]
Hello @mattdsteele, are there any news about this issue? 
At this moment, we aren't able to access an entire private-area of our app due this problem. 

Is there a way to replicate the same behavior of android on IOS devices?

Thank you!

**Comment by deu-dev** [comment]
@CarloDotlog We fixed this with capacitor you can get the fixed Version here https://www.npmjs.com/package/@sirum/cordova-plugin-inappbrowser-capacitor

**Comment by NiklasMerz** [comment]
This plugin is not designed to work with Capacitor like that.

@deu-dev You fix looks interesting. We cannot fix this like that for Cordova in this upstream plugin but might not need to fork the entire IAB plugin. You could try to build a small plugin that just adds the WKProcesspool for capacitor projects.

**Comment by demym** [comment]
What if we don't use capacitor ? I have the same beahviour as someone else, authenticate using a inappbrowser, but the server cookies are not then available to the Ionic5 app....

With Ionic3 it worked.... This is causing me a big problem. Any chances to get this fixed ?

Thanks

**Comment by damianlluch** [comment]
> Hello,
> 
> I am experiencing issues with sharing cookies between the InAppBrowser and the cordova webView.
> 
> What I am trying to achieve is doing an authentication via inAppBrowser; and after, closing it and continue on an iframe in the main ionic webview. In android everything works and the cookies are shared out of the box, in Ios this does not happen. In fact, whereas the inAppBrowser correctly receives the login cookies; in the iframe of the ionic app we do not have any session cookie.
> 
> Is there a way to replicate the same behavior of android on IOS devices?
> 
> Thanks in andvance

I'm having the problem that I lose the session when I close the app on Android with inAppBrowser.
Can you share the configuration or tell me what you have done to avoid losing the session?

thanks
