### ISSUE TITLE
Method to force browser for map links?

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-inappbrowser#853]
Is there any method, or could any method be created, to force the phone to use the browser versus the phone asking the user to pick an app - particularly for map links?  IE: `Open link with Maps or Chrome` ?

We have multiple reasons as to why we need to force the link to a browser - but if the Android or iOS detects its a google maps link - it will ask the user which app to open the link with.  If the user chooses the Maps app OR has already defaulted to a particular app it will automatically just open in that app even though its not the best method for that link.  We have specific types of map links where we know the browser provides the consistent results whereas it is hit or miss using Google Maps app

Additionally, we have had users accidentally hit the wrong app, and then chose to make it the default (in a few cases, they chose the `Uber` app) and once its defaulted the wrong app opens up every time and doesn't display the intended info correctly or at all.  

We then have to explain to users that the issue isn't our fault, its because they defaulted those types of links to use the wrong app - but they don't care, all they see is the link doesn't work and blame our app for it.

**Comment by timbru31** [comment]
This is handled by the OS (for iOS it's called universal links) and we have no control over it.

For the future, I'd recommend asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io) - we use this issue tracker for bugs and not support :)
