### ISSUE TITLE
Inappbrowser takes part of html footer on iOS platform.

### ISSUE THREAD

**Issue by klochko7** [apache/cordova-plugin-inappbrowser#856]
Hi all ! Could anyone suggest please, if exist way to fix html problem when I open Ionic app with InAppBrowser ?
In InAppBrowser I see part of html footer from Ionic app.

I use such code.

`cordova.InAppBrowser.open("https://my.somesite.com, '_blank', "location=true");`

Problem exmple.

![7f6ff72aa4d6ea40b47ce58774342dc2](https://user-images.githubusercontent.com/8359280/109944323-caaf4480-7cde-11eb-9ea3-21b1b09cc70e.png)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
