### ISSUE TITLE
[ios]open window with hidden=yes, window can't close

### ISSUE THREAD

**Issue by boboxiaodd** [apache/cordova-plugin-inappbrowser#864]
# Bug Report

### What is expected to happen?
this is my code:

```
let ref = cordova.InAppBrowser.open(res.url, '_blank', "hidden=yes");
//...
ref.close();  
```

### What does actually happen?
in iOS , the browser don't close 
![image](https://user-images.githubusercontent.com/4714247/114201575-f03c0780-9988-11eb-9728-7ad957278516.png)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by boboxiaodd** [comment]
i use this solve this problem temporarily

```
ref.show(); ref.close();
```

**Comment by marshall86** [comment]
Can you provide a proper solution for this issue please?  as per issue opened here https://github.com/apache/cordova-plugin-inappbrowser/issues/844#issuecomment-815845661
