### ISSUE TITLE
cordova-plugin-inappbrowser for ios Plugin doesn't support this project's cordova-ios version. cordova-ios: 5.1.1, failed version requirement: >=6.0.0

### ISSUE THREAD

**Issue by DuaneQ** [apache/cordova-plugin-inappbrowser#866]
My issue is I keep getting rejected by the Apple store for having UIWeb in my plugins. So I've upgraded all of my plugins but my issue is Google Plus won't install with cordova-ios 6.x. I can only get Google Plus installed with cordova-ios 5.1.1. The conflict is that cordova inapp browser won't install on 5.1.1, it needs 6.x or greater. I'm not sure how to resolve this issue with two different cordova plugins requiring different cordova-ios versions.

Is there an alternative to inapp browser?

Is there a way to open browser links from ionic without inapp browser?

**Comment by NiklasMerz** [comment]
Looks like you already got a possible solution for this in Slack. This is more a support request.
