### ISSUE TITLE
[Android] intent:// not working on inappbrowser {ERR_UNKNOWN_URL_SCHEME}

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-plugin-inappbrowser#867]
# Bug Report

### What is expected to happen?
The inappbrowser plugin should handle intent:// properly.
So if the user try to open intent:// link to force open third party app, it should open that app, but current code for inappbrowser prevent third party apps to opening.

### What does actually happen?
If you try to open external intent:// link from third parties (which you have no any control for it) that have custom name, then the inappbrowser plugin generate an error message from cordova webview:
net::ERR_UNKNOWN_URL_SCHEME

## Information

Custom intent not work in inappbrowser.

### Command or Code

Try to open this using target: _blank :
intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;end

### Environment, Platform, Device

Android

### Version information

cordova-plugin-inappbrowser 5.0.0
cordova-android 9.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mosabab** [comment]
Any update !

**Comment by Pietfro** [comment]
Hey @mosabab ! Have you tried changing the target to `_system` when opening a new URL? I was facing similar issue when my target was set to `_blank`. This is obviously not a solution, but rather a workaround.

**Comment by mosabab** [comment]
> Hey @mosabab ! Have you tried changing the target to `_system` when opening a new URL? I was facing similar issue when my target was set to `_blank`. This is obviously not a solution, but rather a workaround.

Hi,
If you open in target _system this will open in your mobile browser, so this not even a temp solution.

Somebody fix the cordova-android code to handle this issue, but for inappbrowser plugin still not solved

**Comment by talktosanjay3** [comment]
I am still facing this issue. I am loading an angular app in the inappbrowser. And this application has a link to open google maps app. But i get the error 

"Webpage not available
The webpage at intent://maps.app.goo.gl/?link=https://www.google.com/maps/search/; could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME"

**Comment by tmilar** [comment]
@mosabab any news?
