### ISSUE TITLE
Videos are paused every second in iPad in inappbrowser

### ISSUE THREAD

**Issue by deepasolanki986** [apache/cordova-plugin-inappbrowser#868]
we have an html form which opens in inappbrowser. HTML page contains video file with embedded audio. when we play video the video get paused every second and it becomes very difficult to process video but if we mute the audio then video works perfectly fine. Ideally it should play without any pause. Any help will be appriciated.
Thanks in advance!

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
