### ISSUE TITLE
'InAppBrowser' refers to a value, but is being used as a type here. Did you mean 'typeof InAppBrowser

### ISSUE THREAD

**Issue by kumarmanishc** [apache/cordova-plugin-inappbrowser#873]
# Bug Report

## Problem
Inappbrowser is not initialising.
### What is expected to happen?
When I compile code it gives error as,
'InAppBrowser' refers to a value, but is being used as a type here. Did you mean 'typeof InAppBrowser

### What does actually happen?
'InAppBrowser' refers to a value, but is being used as a type here. Did you mean 'typeof InAppBrowser

### Command or Code

`// importing in app browser.
 import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';
// imported in constructor
 constructor(private iab: InAppBrowser, private router: Router) {}
// creating browser
 myfunction(){
    this.iab.create(URL.donate_url, '_self', browserOption);
 }`

### Version information

"cordova-plugin-inappbrowser": "^5.0.0",
Ionic:

   Ionic CLI                     : 6.14.1 (/home/swastik/.nvm/versions/node/v12.18.4/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1102.12
   @angular-devkit/schematics    : 11.2.12
   @angular/cli                  : 11.2.12
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.0

System:

   Android SDK Tools : 26.1.1 (/home/swastik/Android/Sdk)
   NodeJS            : v12.18.4 (/home/swastik/.nvm/versions/node/v12.18.4/bin/node)
   npm               : 6.14.13
   OS                : Linux 5.4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Callan003** [comment]
I am getting the same error. Did you manage to solve it?

**Comment by Callan003** [comment]
for me I had to add the import from here: import { InAppBrowser } from '@ionic-native/in-app-browser/__ivy_ngcc__/ngx';

**Comment by breautek** [comment]
`'@ionic-native/in-app-browser/ngx'` is not a package maintained by Apache.

Any typing issues would have to be raised against the maintainers of ionic-native.
