### ISSUE TITLE
Can't able to build app that use inappbrowser

### ISSUE THREAD

**Issue by stojankukrika** [apache/cordova-plugin-inappbrowser#898]
Hi,
We installed a new version of cordova-plugin-inappbrowser and can't build the ios(we didn't try the android yet) version of the quasar application anymore, the error we get:
`no such file or directory: '/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m'` 
Did someone had this issue and how to solve it?
cordova-ios - 6.2.0
cordova-plugin-inappbrowser - 5.0.0

**Comment by kerkzk** [comment]
Do you get the solution? Currently I am facing the same issue
