### ISSUE TITLE
Any plan of support to WKURLSchemeHandler?

### ISSUE THREAD

**Issue by ccykenneth** [apache/cordova-plugin-inappbrowser#917]
# Feature Request

## Motivation Behind Feature

Currently WKURLSchemeHandler are already supported for cordova-ios 6.2 already, which solves many local file assess problem. But unfortunately it is not supported in the in-app-browser plugin yet. 

## Feature Description
support for WKURLSchemeHandler in IOS device

**Comment by jcesarmobile** [comment]
WKURLSchemeHandler Is for loading local assets, InAppBrowser for loading external sites.
What’s your use case for wanting to load local assets in the InAppBrowser?

**Comment by jcesarmobile** [comment]
closing since there was no response

**Comment by ccykenneth** [comment]
> WKURLSchemeHandler Is for loading local assets, InAppBrowser for loading external sites. What’s your use case for wanting to load local assets in the InAppBrowser?

In our app we used to load local assets in the InAppBrowser with file:// protocol. But since we upgraded the cordova version fo ios, it doesn't work any more. In the Main webview we are able to fix the problem by using the WKURLSchemeHandler setting, but it is not supported in the new InAppBrowser yet. So that's why we asked in this thread.
