### ISSUE TITLE
how to hide statusbar in IPAD? 

### ISSUE THREAD

**Issue by Saqib92** [apache/cordova-plugin-inappbrowser#923]
How can i hide Statusbar in IPAD's whene using in-app-browser?

---

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
