### ISSUE TITLE
Does inappbrowser support standard HTML 5 autocomplete on input fields?

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-inappbrowser#942]
I think it used to but can't find the answer to this question anywhere?

I am trying to streamline my apps signup form.  But because webviews are not related to the phone browsers HTML 5 feature like `autocomplete` on input fields does not work.  So I have an idea where I would like to use inappbrowser to pop up signup form - that looks like its embedded in the app itself.  Then the user can autocomplete fields like `given-name`, `family-name`, `email`, `tel-country` etc and when they hit submit, pass that data passed back into my app somehow.

Could something like this work?  I think it could only work if inappbrowser does in fact support `autocomplete`

**Comment by NiklasMerz** [comment]
I think this is something the webview has to support and the InAppBrowser can do nothing about it.
