### ISSUE TITLE
What are the plans for updating this plugin?

### ISSUE THREAD

**Issue by bftcntyapps** [apache/cordova-plugin-inappbrowser#943]
Seriously....is there even a plan to update this plugin? Are there any alternatives? 

Can we just get it up to date with the current issues so it will even compile vs adding new features?

**Comment by ryward2331** [comment]
> Seriously....is there even a plan to update this plugin? Are there any alternatives?
> 
> Can we just get it up to date with the current issues so it will even compile vs adding new features?

I agree the issue on IOS header still exist.

**Comment by jcesarmobile** [comment]
The plugin is maintained by unpaid volunteers, we do what we can when we can.
The plugin compiles fine for me, if it doesn’t for you create a new issue and provide a sample app where the issue can be reproduced and provide more information about your environment (macOS version, Xcode version, etc.)
