### ISSUE TITLE
iOS App Crash when URL cannot be loaded

### ISSUE THREAD

**Issue by danielehrhardt** [apache/cordova-plugin-inappbrowser#944]
# Bug Report

### What is expected to happen?
When a URL is not available (404, 500, DNS old) the InAppBrowser should show a error message. 

### What does actually happen?
The App Crash.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can you provide a sample app that reproduces the issue?

**Comment by jcesarmobile** [comment]
Closing since no sample app was provided
