### ISSUE TITLE
[Android 12] Renders incorrectly

### ISSUE THREAD

**Issue by GertVen** [apache/cordova-plugin-inappbrowser#948]
# Bug Report

## Problem
InAppBrowser renders the web page incorrectly on both a physical device, and Andoid 12 emulator

### What is expected to happen?
Web page should show correctly

### What does actually happen?
![image](https://user-images.githubusercontent.com/14887631/170432358-626c3670-1b99-4865-9c39-903902070285.png)

### Command or Code
Open the InAppBrowser in an emulator

### Environment, Platform, Device
Angular 8
Ionic 4
Android 12
Using a PR build of InAppBrowser, located here: git+https://github.com/mosabab/cordova-plugin-inappbrowser.git 
URL: https://github.com/apache/cordova-plugin-inappbrowser/pull/886#issuecomment-1134983529
Not using this version gives me a different error

## Checklist

- [ X ] I searched for existing GitHub issues
- [ X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by jcesarmobile** [comment]
You are using a fork, so you should report the bug to the fork.

you say that not using that fork gives a different error, that’s the issue you should report here.
