### ISSUE TITLE
android 12 target _self close app

### ISSUE THREAD

**Issue by alextapia007** [apache/cordova-plugin-inappbrowser#970]
# Bug Report

## Problem
android 12 target _self close app

### What is expected to happen?
show in webview

### What does actually happen?
if target is _blank work well, but if target is _self the app close.

### Command or Code

ref = cordova.InAppBrowser.open('https://linnkup.com/pwa/index.php?wv=isWebView', '_self', 'location=no,hidenavigationbuttons=yes,hideurlbar=yes,hardwareback=yes,hidden=yes,fullscreen=no');

### Environment, Platform, Device
Android 12

### Version information

cordova 9.0.0
android 11.0.0
cordova-custom-config 5.1.0
cordova-plugin-add-swift-support 2.0.2
cordova-plugin-android-permissions 1.1.2
cordova-plugin-androidx-adapter 1.1.3
cordova-plugin-app-launcher 0.4.0
cordova-plugin-audiotoggle 1.0.3
cordova-plugin-background-mode 0.7.3
cordova-plugin-camera 5.0.2
cordova-plugin-compat 1.2.0
cordova-plugin-customurlscheme 5.0.2
cordova-plugin-device 2.0.3
cordova-plugin-file 6.0.2
cordova-plugin-geolocation 4.1.0
cordova-plugin-globalization 1.11.0
cordova-plugin-inappbrowser 5.0.0
cordova-plugin-iosrtc 8.0.0
cordova-plugin-media-capture 3.0.3
cordova-plugin-splashscreen 6.0.0
cordova-plugin-statusbar 2.4.3
cordova-plugin-vibration 3.1.1
cordova-plugin-wkwebview-file-xhr 3.0.0
cordova.plugins.diagnostic 5.0.2
es6-promise-plugin 4.2.2
onesignal-cordova-plugin 3.0.1
phonegap-plugin-media-stream 1.2.1

osx

## Checklist

- [x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by jcesarmobile** [comment]
I've tested loading your site and I can't reproduce.
