### ISSUE TITLE
Plans for compatibility with OAuth 2.0 where web views are not supported

### ISSUE THREAD

**Issue by odiseo42** [apache/cordova-plugin-inappbrowser#973]
I've been using cordova-plugin-inappbrowser successfully for 4 years to allow users authenticate via OAuth. My customers are enterprise and are starting to use tools like Intune to deploy apps. However, recently I got reports that default security rules on Azure SSO portals prevent in-app-browser from logging in, in particular because the user agent it is identified as a non native (i.e. Safari) browser.

The plugin [InAppBrowser for NativeScript states](https://openbase.com/js/a2c-nativescript-inappbrowser/documentation):

> Use in-app browser tabs (like SFAuthenticationSession/ASWebAuthenticationSession and Android Custom Tabs) where available. Embedded user-agents, known as web-views (like UIWebView and WKWebView), are explicitly not supported due to the usability and security reasons documented in [Section 8.12 of RFC 8252](https://tools.ietf.org/html/rfc8252#section-8.12).

My question is, is there a plan or alternative for cordova-plugin-inappbrowser so it does not use webviews, and instead use native Safari browser?

**Comment by jcesarmobile** [comment]
There are no plans, this plugin uses we views, switching to safari view controller and custom tabs would require dropping most of the plugin features (injecting js/css, browser events, etc.)

there is a 3rd party plugin that uses safari view controller and custom tabs
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller
