### ISSUE TITLE
Handle SSL Certificate Trust Error

### ISSUE THREAD

**Issue by dheeraj99099** [apache/cordova-plugin-inappbrowser#975]
Right now if cordova inappbrowser receives an error: SslError.SSL_UNTRUSTED, it's directly stopping the navigation with which couldn't proceed to the browser. Instead we can have something like asking user to confirm whether to proceed or not will be a great problem solver.

**Comment by breautek** [comment]
Cordova applications in debug mode are configured to ignore SSL certificates as it's expected that untrusted/self-signed certificates may be used in development environments.

Release builds are configured to reject invalid/untrusted SSL certificates. Google will test apps that accepts insecure connections and will mark apps as unsafe, and in some cases have been known to contact app developers who allows SSL bypass without justification. Apple has similar policies for their App Store.

For these reasons, Cordova cannot provide exception clauses for trusting SSL certificates.

It would be recommended to not rely on services that have untrusted SSL errors and instead correct the SSL configuration them. But if you wish to accept insecure SSL connections, you may do so at your own risk by forking the project and making the necessary modifications to allow untrusted SSL connections.
