### ISSUE TITLE
On first URL change, initiate JS callback. Only after the beforeload event, continue - BUG

### ISSUE THREAD

**Issue by andreydruz** [apache/cordova-plugin-inappbrowser#978]
# Bug Report

## Problem
beforeload event work every second call

### What is expected to happen?
beforeload event work on every call

### What does actually happen?
In this code
https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/android/InAppBrowser.java#L1176
sending sendBeforeLoad(url, method) on every second call
See video:
https://drive.google.com/file/d/1Sz5RetWWbBSMQG6LFDkL3lDm8m-xKit5/view?usp=drivesdk

Not clear what waitForBeforeload is for but if I comment out #L1176 - beforeload  working every time.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can you provide a sample app that reproduces the issue?

**Comment by jcesarmobile** [comment]
closing since there was no response
