### ISSUE TITLE
The inappbrowser fullscreen view in pixel 6 is broken

### ISSUE THREAD

**Issue by muneerkhan007** [apache/cordova-plugin-inappbrowser#980]
# Bug Report

## Problem
The inappbrowser fullscreen mode is not working in Pixel 6. Attached screen shot and code for more information.
### What is expected to happen?
inappbrowser should open in full screen and hide the bottom toolbar.

### What does actually happen?
inappbrowser opening not in full screen and it is not hiding the bottom toolbar.

## Information

![image](https://user-images.githubusercontent.com/15920456/194390874-818c756a-65c6-4af2-9224-29f497c5d098.png)

### Command or Code

import { InAppBrowser } from '@ionic-native/in-app-browser';

this.iab.create(url, '', 'location=no,fullscreen=yes');

### Environment, Platform, Device

Issue occurring only on android platform. Device: Google Pixel 6 device and Google Pixel 6 emulator.

### Version information

@ionic-native/in-app-browser version: 4.20.0
Cordova: 11.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
According to the docs, fullscreen hides the status bar, it doesn't mention anything about navigation bars, I've tested earlier versions and it's not hidden neither, so I think it works as expected.
