### ISSUE TITLE
InAppBrowser capturing Android device id

### ISSUE THREAD

**Issue by Prsnkmr7** [apache/cordova-plugin-inappbrowser#994]
# Issue Type
- [ ] Bug Report

## Description
We are using "cordova-plugin-inappbrowser" for our application. We are using the version 4.1.0. While submitting the application to one of the store there was a observation that InAppBrowser is capturing the Android device id at the load of the application.  

### Query
Please help us whether we are capturing the above information through InAppBrowser. If yes, then please help how can we avoid capturing this information .

Environment, Platform, Device
Android

Version information
cordova-plugin-inappbrowser 4.1.0

**Comment by sriamit84** [comment]
> # Issue Type
> * [ ]  Bug Report
> 
> ## Description
> We are using "cordova-plugin-inappbrowser" for our application. We are using the version 4.1.0. While submitting the application to one of the store there was a observation that InAppBrowser is capturing the Android device id at the load of the application.
> 
> ### Query
> Please help us whether we are capturing the above information through InAppBrowser. If yes, then please help how can we avoid capturing this information .
> 
> Environment, Platform, Device Android
> 
> Version information cordova-plugin-inappbrowser 4.1.0

We are facing this issue. Any help on this would be appreciated.

**Comment by breautek** [comment]
I think you might be referring to https://github.com/apache/cordova-plugin-inappbrowser/blob/8ee1d3882163ee1dedb86fb3d0d1f8b7e16c3e42/src/android/InAppBrowser.java#L467

Which seems to be there to gracefully handle an infinite loop. So I don't think we can simply remove this.

**Comment by jcesarmobile** [comment]
What that line does is to set some sort of "referral" to the browser app so it knows which app opened it, but it's not getting any device identifier, just passing the app's package name.
Could be removed as the infinite loop handling is the following line, not that one, but I don't think the line could produce that warning.

Can you provide more information about the message google is showing?
Also, can you try with version 5 of the plugin?

**Comment by jcesarmobile** [comment]
closing since there was no response
