### ISSUE TITLE
@capacitor/share displayed behind inappbrowser

### ISSUE THREAD

**Issue by oshevans** [apache/cordova-plugin-inappbrowser#996]
Currently testing on iOS.
I have an InAppBrowser showing a remote site.
I use @capacitor/share.
The share UI shows behind the IAB.
How can I fix this?

**Comment by cchafy** [comment]
Same problem here. 
But I found that navigator.share(data) method of ios webview does the same think and shows with correct z-index.

**Comment by oshevans** [comment]
Oh yeah.
I ended up hacking the share plugin and will submit a pull request (when I work out how) for them to include support for presenting on the topmost UIViewController and for iPad popovers.
