### ISSUE TITLE
-1202 Error 

### ISSUE THREAD

**Issue by nomori7010** [apache/cordova-plugin-inappbrowser#997]
# Bug Report

### What is expected to happen?

no error

### What does actually happen?

I received the following error in the "loaderror" event.
There is no problem with the certificate.
What could be the possible cause?

```
-1202: the certificate for this server is invalid. you might be connecting to a server that is pretending to be "xxx.xxx.xxx" which could put your confidential information at risk.
```

## Information

After waiting for a while, when I tried again, the error was resolved.

### Environment, Platform, Device

iOS16.1.1

### Version information

Cordova CLI Ver. 11.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
looks like the server has a bad certificate, can you provide a sample app reproducing the issue or the the url you are trying to load?

**Comment by jcesarmobile** [comment]
closing since there was no response
